### ISSUE TITLE
Issues editing helm templates

### ISSUE THREAD

**Issue by ZakharZakharov** [kubeshop/monokle#1003]
I use windows version of Monokle. Version 1.4.

1. When I am editing helm templates in Monokle, it highlights value variables.
![image](https://user-images.githubusercontent.com/1910974/149554347-b0f893c2-f3e1-474a-94f3-ddd92e6192f5.png)
2. When I click “Deplyment” tab in editor, touch some textbox with value (which is shown as [object Object]) and navigate back to “Source”, my file is being transformed to this:
![image](https://user-images.githubusercontent.com/1910974/149554420-ed4355ce-6b9e-4c14-868f-34419c5ba1cb.png)

3. If I click “Metadata”, the application shows a black screen. In this state, only closing application and opening it again helps.
4. If value variable is used for “name” attribute, it appears in Navigator like this:
![image](https://user-images.githubusercontent.com/1910974/149554859-021c803b-b7d5-416c-aa24-05296464d0f9.png)

I am also attaching my folder.
[sample.zip](https://github.com/kubeshop/monokle/files/7871999/sample.zip)

To reproduce 2-nd and 3-rd defect, open "mongo-express" deployment in editor.

Thanks.

**Comment by olensmar** [comment]
Hi @ZakharZakharov - thanks for this - there is definitely a lot that can be improved in Monokles Helm support - the issues you are describing are known and primarily targeted by #263 which we plan to tackle in version 1.6.0 - including with some of the other Helm related issues gathered in https://github.com/kubeshop/monokle/projects/12 - if any of those stand out to you (or there is something missing) please let us know so we can prioritize accordingly !

**Comment by ZakharZakharov** [comment]
I would start from getting rid of application crushes and files corruption. I didn't find it in Monokle issues list, but I think this can frustrate users a lot.
P.S. Yamls get corrupted after Isuue #2 and #3 reproducion, because the result is being saved.

**Comment by olensmar** [comment]
thanks @ZakharZakharov - we're wondering if you could try the nightly build at https://github.com/kubeshop/monokle/releases/tag/untagged-30d03d4a5006e5baf4f5 to see if your application crashes are fixed - in regard to corruption of Helm templates I recommend you add them to the file-exclusion list in the Monokle settings for now so Monokle doesn't load them at all

![image](https://user-images.githubusercontent.com/1917063/149571927-6d106b24-d608-448d-8ffc-d1bbcea2123b.png)

**Comment by olensmar** [comment]
until we add native support for helm templates (as described in #263) we should just ignore parsing files in a chart folder that contain {{ }} constructs? (don't know how we could otherwise identify a go template)
