### ISSUE TITLE
Usage analytics

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1022]
To understand which features that are most popular and collect error logs Monokle needs to integrate with some analytics platform. This should be anonymised and opt-in functionality. 

Acceptance criteria

- [ ] Create a unique id per installation
- [x] define analytics provider to use
- [x] define what actions/events to track
- [x] opt-in/out mechanics

**Comment by chlete** [comment]
We have decided to use nucleus.sh as a solution.

**Comment by erdkse** [comment]
There is no way to detect installation - instead, we keep a unique device ID to understand that Monokle is used on how many different machines #1431

**Comment by olensmar** [comment]
@erdkse could we measure first launch of the application? (i.e. when we show the welcome dialog)

**Comment by erdkse** [comment]
Yeah we can measure it by saving a flag in electron-store but It will be a one-time thing unless users don't delete electron-store storage - If they delete and re-install the application we can't detect it @olensmar

**Comment by olensmar** [comment]
thanks @erdkse - I think that's better than not measuring it at all... what do you think @chlete ?
