### ISSUE TITLE
Helm/Kustomize preview configurations

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1024]
As an extension to #586 - I would like to manage multiple preview configurations that I can select from when performing a preview, i.e.
- I configure a preview in line with #586 
- I select to save that configuration under a specific name
- When a run another preview I can select a saved configuration instead of having to reconfigure all properties

**Comment by devcatalin** [comment]
From the discussions in #ideas channel from discord:

- allow setting the cluster context for each preview configuration
- if the preview configuration has a file that follows the pattern `values-${kube-context-name}.yaml` and the selected context in Monokle is set to the corresponding one from the pattern, we should use that context when running helm
