### ISSUE TITLE
Disable left toolbar when showing Getting Started page

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1035]
The buttons in the left toolbar should be disabled when the Getting Started page is visible - now they are clickable/highlightable but don't do anything (which I found confusing)

**Comment by olensmar** [comment]
Or should at least the template/plugin buttons be active and work as intended?

**Comment by mortada-codes** [comment]
@olensmar when clicking on Templates or plugins, nothing happen. should we show the template or plugin pane?

**Comment by olensmar** [comment]
I think we should at least enable the plugins pane - so a user can install plugins before creating a project... @devcatalin what do you think?

**Comment by devcatalin** [comment]
I think there should definitely be a way to install plugins before creating a project.
Either by enabling the left pane (but I'm not sure how we sould open that in the getting started wizard)
Or, after we click on "start project using template", we could have a button there to open the PluginManager in a popup..
