### ISSUE TITLE
Component for showing full text when stripped with ellipsis

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1063]
I would like us to create a reusable component that renders text and strips it with ellipsis at the end if it's too long / overflown.
At the same time, while the text is hovered, the component should provide a small popup showing the full text.

**Comment by olensmar** [comment]
I think this is a duplicate of #1025 ?

**Comment by devcatalin** [comment]
No, this should be a Component that we can use for the items in our navigator/file tree so that when the item is hovered we show the full name or respectively full file path

**Comment by devcatalin** [comment]
Closed by https://github.com/kubeshop/monokle/pull/1513
