### ISSUE TITLE
Support Flux Kustomizations CRD

### ISSUE THREAD

**Issue by kingdonb** [kubeshop/monokle#1097]
Hello! Thanks for putting out monokle

I tried using this with FluxCD, and found a quirk worth reporting. There is generally good support for arbitrary custom resources, however the Flux CRDs include a resource called `Kustomization` in the `kustomize.toolkit.fluxcd.io/v1beta2` API group.

This differs from the `Kustomization` in SIG-CLI although it is closely related, it is a separate resource kind.

Unfortunately it looks like monokle treats all resources with the `kind` Kustomization as SIG-CLI Kustomizations, even when they are not in a file `kustomization.yaml` or one of the other magic filenames picked up by SIG-CLI Kustomize as a Kustomization.

In my example repo, https://github.com/kingdonb/bootstrap-repo I have a cluster root at `clusters/moo-cluster` which contains a bunch of Flux Kustomizations, most of which point to a target directory that contains a SIG-CLI Kustomization.

The SIG-CLI Kustomize Overlay looks good in monokle:

<img width="1314" alt="Screen Shot 2022-01-22 at 10 45 34 AM" src="https://user-images.githubusercontent.com/3286998/150645515-cc6f5894-bf0e-46ec-9d18-39ad437bc80f.png">

The Flux Kustomization is detected improperly and shows up as invalid, as it's not validated against the OpenAPI spec from the cluster CRD, but instead against the SIG-CLI Kustomize validation schema, I guess? It doesn't show up as a resource at all in Monokle. I haven't read the source code to explain it yet, but I hope this is an easy fix!

<img width="1315" alt="Screen Shot 2022-01-22 at 10 47 09 AM" src="https://user-images.githubusercontent.com/3286998/150645566-9d823cf1-ff0b-482f-b727-6ec040947453.png">

Thanks again for releasing Monokle!

**Comment by olensmar** [comment]
Hi @kingdonb - great thanks for reporting this - it should indeed be an "easy fix" (I'll regret that...) - will look into it over the weekend and let you know!

**Comment by olensmar** [comment]
Hi again @kingdonb! I've opened a PR to fix this - #1099 - there is a screenshot in it to show that FluxCD Kustomizations are now shown in the Navigator but not in the Kustomization pane - hope I got it right in all scenarios..

A couple of comments:
- what a great repo you have! It's going to be super helpful for testing :D 
- we are considering to add "native" support for Flux CRDs to Monokle so it correctly identifies/verifies links/relationships between Flux and native resources - does that make sense to you? Which CRDs would you suggest we start with? (as I'm guessing Flux has many...)
- thanks again for reporting! - the more bugs we can fix for the upcoming 1.5.0 release, the better!

**Comment by kingdonb** [comment]
> "native" support for Flux CRDs to Monokle so it correctly identifies/verifies links/relationships between Flux and native resources

💯 this makes great sense, absolutely!

I'm happy to help testing, if you are looking to natively support links between Flux resources and other Kubernetes resources, the best place to start is `flux tree` which can already connect those dots and outputs a visual tree or optionally json, as in:

`flux tree kustomization -o json flux-system`

I suggest the Flux Kustomization as the root resource, since it draws a label on all other resources that it creates, it will be easy to trace back from the resources to the Flux resource that created them, and if you gather information from `flux tree` you can hopefully easily put the resource in context with any other related resources based on the Flux parent.

I'm not sure how much help that will be in actual use, or if monokle can expect a `flux` cli binary to be present and shell out to it when needed for `flux tree`, maybe this fits the pattern of how you build monokle or maybe not. The latest versions of Flux maintain information about what resources they manage natively in the Kubernetes Flux Kustomization CR, so if you can't use `flux tree` for some reason, that's the source of truth for most information that `flux tree` draws upon.

This work already looks great! Please feel free to ping me for more help and I can be reached quickly in the CNCF slack at #flux practically any time. 👍

**Comment by olensmar** [comment]
@kingdonb there is a nightly-build available at https://github.com/kubeshop/monokle/tags with the Kustomization fix - if you want to give that a try... we hope to release later this week!

**Comment by kingdonb** [comment]
It looks like there is still an issue:

<img width="1207" alt="Screen Shot 2022-01-26 at 11 12 17 PM" src="https://user-images.githubusercontent.com/3286998/151290698-faae5de2-6d48-4fb3-ac59-9ac5f4af1b08.png">

The Flux kustomizations show up in the UI now, but they still have the ❣️ big gnarley alert that appears to be based on validating a SIG-CLI Kustomization, since it complains about the presence of `spec`

But the Flux kustomizations show up as Kubernetes resources in the UI, which is already an improvement, and the validation of their content appears to be according to the Flux CRD correctly, as well as the Kustomization tab that is populated with a form from the OpenAPI schema. This is frankly amazing, 💯 I'll be showing this off in front of people next chance I get.

I ran the `v1.4.1-nightly-2022-01-27.0` build 👍 

This is still great, I will use this and I look forward to seeing the final release!

**Comment by olensmar** [comment]
thanks @kingdonb for testing and getting back to us - i'll fix this for the final 1.5.0 release - my bad for not noticing!

**Comment by olensmar** [comment]
https://github.com/kubeshop/monokle/pull/1196

**Comment by olensmar** [comment]
I also discovered #1199 while playing around with this - fixed in #1201 !

**Comment by kingdonb** [comment]
This has been the best drive-by issue report in the history of reporting issues 👍 awesome. I'll look for it in the next nightly, (or in the final release if it gets there first!)

**Comment by olensmar** [comment]
hehe thanks @kingdonb - you've been very helpful - keep it coming!

**Comment by kingdonb** [comment]
Here's another quirk I was looking to explain, but now I think I've found it:

When I visit the Kustomization tab, or press the tab key:
<img width="428" alt="Screen Shot 2022-01-27 at 12 39 59 PM" src="https://user-images.githubusercontent.com/3286998/151413756-a1d70560-d5db-4c46-baf2-358c46a71a3c.png">

I return to find the resource has been updated in the filesystem. That's fine, but...

<img width="819" alt="Screen Shot 2022-01-27 at 12 39 54 PM" src="https://user-images.githubusercontent.com/3286998/151413856-d084fff1-ea98-4108-accd-f4def28fa16f.png">

now for some reason, my updated copy of the file includes its own `status` sub-resource. Not everything, just the default value that's in our CRD. (It's placed there as I understand it because a Kstatus check will consider resources "ready" before they've been reconciled once, unless they have an observedGeneration of -1. This is not a meaningful detail for any other purpose.)

At best it's noise, and at worst if I save and commit the file it's likely to cause an error down the line. This does not only happen for Flux kustomizations but also providers, alerts, receivers, etc. (no surprise as we do the same on every CRD.)

Second issue:
<img width="818" alt="Screen Shot 2022-01-27 at 12 39 05 PM" src="https://user-images.githubusercontent.com/3286998/151414010-7ea8eb64-c321-4f31-b636-23aca1689fe8.png">

I'm not sure what to make of this "incoming link" but it's not functional from what I can tell.

It disappears after a while, about the same time that the observedGeneration from status sub-resource shows up in the copy on my filesystem.

**Comment by olensmar** [comment]
thanks @kingdonb - digging in! Regarding the second issue - where you previewing a kustomization in the panel to the left when getting this? Or had you previewed one? If so - can you tell me which one?

**Comment by olensmar** [comment]
ok - just to keep you in the loop @kingdonb - I'm digging into the first issue and the reason this is happening is that the form component automatically generates default properties/values for any defaults it finds in the schema, to provide user with (hopefully) helpful default input in their forms... in this specific case the Kustomization CRD schema (and the other CRDs also) contains the following for the status object:

```yaml
  ...
  status:
    default:
      observedGeneration: -1
    description: KustomizationStatus defines the observed state of a kustomization.
  ...
```

which results in this default value being inserted into your resources as soon as you go into the Form editor (the fact that it subsequently gets inserted into any resource without you having to actually go into the Form editor is obviously a bug we have to fix separately) 

I'm not entirely sure what the right way forward is; technically speaking you should be fine here since the schema says this is a default value, but realistically i'm not sure you (or anyone else) wants values inserted into your resources - however default they might be. One solution could be to dynamically augment the schema and simply remove all object default values before passing the schema to the form component - which would probably (I have yet to try) solve this specific issue - but on the other in many cases having a default object might be a nice thing to have - for example when creating new items in an array of complex objects. If we opt to remove default schema values as described, we could allow the toggling of this behaviour via a setting in the UI ("Generate default values in Form editor") - default to false!?

What would be best for you? (which is what matters most right now..)

**Comment by kingdonb** [comment]
I think the default values getting added to resources when you edit them in monokle at-large is a helpful feature, I noticed `force: false` was inserted into some of my Kustomizations for example, and this is helpful as it would allow users to discover fields they aren't using more readily. I would suggest also providing an option that the editor will not reformat your files, or at least that it will not reformat them for you if you didn't make any edits.

I personally would like to get the expanded default values inserted in my files at the same time as they're going to be re-indented, both of those should be optional though IMHO. But I don't think anyone is going to be pleased by having the `status: observedGeneration: -1` added to their files, that field shouldn't occur in any Kubernetes yaml file. I don't really think it will harm anything, it's just noise and might confuse users who haven't internalized that status is a write-only section.

I would filter the entire status section since it's not writable (at least not by the user, only write by the operator/controller.)

The "Flux Kustomizations" are all in files called `flux-kustomization.yaml` – the good ones of this kind are all generally stored in `clusters/moo-cluster/*/flux-kustomization.yaml` and I'd continue to focus on those particular files when looking for strangeness in here.

**Comment by olensmar** [comment]
ok thanks - we're striving for a generic solution for 1.5.0 so we'll start with what is proposed in #1222 - a future improvement will be to allow CRD-specific behaviour related to immutable properties/objects - #1223. Please comment on this if you have any additional input! 

Thanks again for your input - these are the use-cases we really want to make sure Monokle handles correctly!

**Comment by kingdonb** [comment]
I mentioned in the other thread, it turns out that `observedGeneration: -1` thing is a hack, but a well-known hack that might not be going away any time soon. I'll commit some files with `status:` and `observedGeneration` defined so we can be sure it's definitely not going to hurt anything, when Flux users start to try out Monokle. But I'm already about 99% sure it won't.
