### ISSUE TITLE
Application crashes when trying to create resources from template

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#1105]
**Describe the bug**
Tried to create resources from the template. Received an error and the UI is locked.

**To Reproduce**
1. Open an empty project with an empty folder
2. Go to templates and select `RoleBinding and ServiceAccount`
3. Click `Start` when the modal pops-up

**Expected behavior**
Create the resource

**Screenshots**

<img width="721" alt="Screen Shot 2022-01-24 at 11 35 48" src="https://user-images.githubusercontent.com/2957624/150748612-27661da1-8d67-4017-b752-47beef6e39aa.png">

![Screen Shot 2022-01-24 at 11 36 14](https://user-images.githubusercontent.com/2957624/150748663-3215ae11-c926-4ada-8bbf-cb958686d993.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.4.0

**Additional context**

**Comment by olensmar** [comment]
this happens because #1098 hasn't been merged yet

**Comment by olensmar** [comment]
@erdkse is this working now?

**Comment by erdkse** [comment]
> @erdkse is this working now?

Yes, @olensmar everything seems fine now.
