### ISSUE TITLE
Videos to Update for 1.5.0

### ISSUE THREAD

**Issue by jfermi** [kubeshop/monokle#1154]
Two videos need to be replaced with updated 1.5.0 versions:

1. Monokle Walkthrough -- img/monokle-overview.gif)](https://youtu.be/9c80qj9NkQk) in index.md
2. Cluster Compare -- (img/cluster-compare.png)](https://youtu.be/9ha3-aPgSt8) in cluster-compare.md

**Comment by shaggyyy2002** [comment]
I would like to contribute is this issue still open?
