### ISSUE TITLE
Default cluster context setting

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1187]
I would like to be able to set which cluster context should be selected by default.
This should be a project setting.

**Comment by olensmar** [comment]
@erdkse isn't the selected cluster context already stored in the project?

**Comment by erdkse** [comment]
yes - it is stored in `.monokle`file

**Comment by olensmar** [comment]
thanks @erdkse  - @devcatalin can we close this?

**Comment by devcatalin** [comment]
Sure, looks like it works!
