### ISSUE TITLE
Confirm modal when replacing local resource with cluster resource

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#1205]
I would be nice to have a confirmation modal first when replacing a local resource with a resource from cluster when in diff modal. This should be for both `local resource diff` and `cluster resource diff`

![image](https://user-images.githubusercontent.com/47887589/151363981-7968e673-dad3-4e9d-a551-5b607126ef19.png)

![image](https://user-images.githubusercontent.com/47887589/151363555-0a3c770b-e1be-4921-b30e-a7295b4e8053.png)

**Comment by olensmar** [comment]
perhaps this relates to #930  ?

**Comment by topliceanurazvan** [comment]
true, we could do all of them in one PR.

**Comment by bhavyastar** [comment]
Could you guide me with this issue? I really want to work on this issue.

**Comment by topliceanurazvan** [comment]
Hello @bhavyastar and thank you for your interest in helping Monokle, it's great to see that our community is growing. 🎉 

For this issue we should use antd's `Modal.confirm`, which should be triggered when the user clicks on the buttons highlighted in the screenshots above. You can have a look in other components that are using a confirmation modal ( eg. `CheckedResourcesActionsMenu`, `QuickSearchActions` etc.. ) and do it in a similar way, with a suggestive text for it. Hope this was helpful for you and if you have any other questions please feel free to ask us.

**Comment by devcatalin** [comment]
Closed by https://github.com/kubeshop/monokle/pull/1540
