### ISSUE TITLE
Replace invalid values in .monokle file with default values 

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1232]
If i attempt to add an invalid value to one of the properties in the .monokle file I expect Monokle to replace that with the default value instead - now it keeps it until I actively set another value - which could cause internal errors

This might be required to handle future settings gracefully in older version of Monokle!?

**Comment by erdkse** [comment]
this can be handled pretty easy now - Shall we set it for 1.5.0

**Comment by olensmar** [comment]
@erdkse sure if you have time - we want to release tomorrow!
