### ISSUE TITLE
Disable Deploy, Cluster Compare, Diff actions if cluster is not available

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#1238]
We should disable these buttons if the selected cluster is not available ( can't connect to it ).

**Comment by sriniva7** [comment]
@topliceanurazvan I like to try this issue. Kindly assign me

**Comment by topliceanurazvan** [comment]
Hello @sriniva7, thank you for your interest in contributing to Monokle. I'm assigning this issue to you.

If you need any help, don't hesitate to ask us.

Good luck 🤞🏻
