### ISSUE TITLE
Show the file name to be created when adding a new resource and save to folder

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#1263]
We should show the file that is going to be created when saving to a folder a new resource and apply the same logic as for saving an unsaved resource.

![image](https://user-images.githubusercontent.com/47887589/152006042-374d20e9-23be-499e-9e5d-3cc3121e2024.png)

**Comment by jenil777007** [comment]
Hello contributors, a first time contributor here, wanted to pick up this enhancement, do we have a reference of what the final result should look like? We should be using what component?

**Comment by chlete** [comment]
Hi @jenil777007 thanks for contributing to Monokle! at this time we are closing a release, we are a bit busy, but we will get back to you!

**Comment by jenil777007** [comment]
Absolutely @topliceanurazvan , been waiting to contribute. 

I have already asked my doubts above.

**Comment by topliceanurazvan** [comment]
Basically, the name shown here should be similar to the one from saving an unsaved resource to a folder.

![image](https://user-images.githubusercontent.com/47887589/167147672-320cdaef-7de1-4a6d-8eec-fab1c538b4ad.png)

All the functionality it's in `SaveResourcesToFileFolderModal` component, especially `generateFullFileName` function which is taking care of generating the name for the resource you are trying to create. The naming convention is that, if the name already exists in the file system, it will just add the kind to the name ( e.g. `test-resource-secret` in our case ), and if this still exists, it will add some suffixes ( e.g. `test-resource-secret (2)`,`test-resource-secret (3)`, etc... ) until the generated name is unique.

About the label, having something similar like ( `File to be created:` and on the next row the actual name of the resource ), just like in the screenshot example.

Hopefully I was clear enough about what should be done and please reach out to us if you need more help and directions.

**Comment by topliceanurazvan** [comment]
Hello @jenil777007 , how is it going with this issue? Is there anything else we could help with?

**Comment by topliceanurazvan** [comment]
Great work @jenil777007 , don’t hesitate to ask us if you need any help.

**Comment by topliceanurazvan** [comment]
> Hello @topliceanurazvan , I'm working on the filename generation logic, should have an update in a day or two.
> 
> As of now, I'm able to render the filename as followed,
> 
> ![Screenshot 2022-06-15 at 11 15 30 PM](https://user-images.githubusercontent.com/8577729/173891813-e1f4d27e-1d73-4a1d-a276-ae62091c15a6.png) .

About the filename generation logic, we already have it implemented in [`SaveResourcesToFileFolderModal:48`](https://github.com/kubeshop/monokle/blob/main/src/components/molecules/SaveResourcesToFileFolderModal/SaveResourcesToFileFolderModal.tsx), you can maybe take a look in there and use the same function for generating the name.

**Comment by jenil777007** [comment]
Thanks @topliceanurazvan. I have referred to that file only. Please have a look at my PR, https://github.com/kubeshop/monokle/pull/1948

1. I have created a local state variable `exportFileName` 
2. Have triggered the logic `generateFullFileName` on `onFormValuesChange` 
3. `generateFullFileName` is the function where I have a doubt. `fsReaddirPromise` requires a path i.e. `selectedFolder` in our case, however this is resulting `<root>`. So **are we supposed to fetch the path from `fileMap`?** (for local testing I hardcoded my root path)
4. After fetching & filtering all the filenames from `selectedFolder`, name collision is being checked
5. A similar kind of implementation of function `generateFullFileName` from `SaveResourceToFileFolderModal` has been implemented in `createFullFileName`

**Comment by topliceanurazvan** [comment]
Hello @jenil777007 , I've reviewed your PR and left some comments. Great work so far!

**Comment by ayushlohmod** [comment]
hey i wanted to work on this
