### ISSUE TITLE
Not all helm charts are recognized

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1290]
Right now, Monokle recognizes helm charts when it finds a `Chart.yaml` and a `values.yaml` files in the same folder.

We should probably only check for the `Chart.yaml` file and find any other values files in subfolders (which we do already afaik).

For more complex scenarios, we should handle them after introducing Preview Configurations - see https://github.com/kubeshop/monokle/issues/1024

**Comment by olensmar** [comment]
thanks - seems like an easy fix to simply not require a values file in the same folder as the Chart.yaml !?
