### ISSUE TITLE
Adapt application for zoomed state

### ISSUE THREAD

**Issue by DmitryEremenko** [kubeshop/monokle#1293]
We need to change all font sizes from px to em to adapt them for zoomed in\out state

**Comment by kruczyna** [comment]
hey @DmitryEremenko !
I did not have any experience with FE before, but I'm keen to take this one. What's the base for `px` value now? 
Also, do I understand correctly I should change only `.css` files or the `.tsx` ones should also be converted to `em`?

**Comment by DivvSaxena** [comment]
I want to work on this issue.

**Comment by topliceanurazvan** [comment]
Hello @DivvSaxena,

Thank you for wanting to contribute to Monokle. The issue will be assigned to you.

If you have any questions just let us know.

Good luck 🤞🏻

**Comment by DivvSaxena** [comment]
Can you send me the location of the file

**Comment by topliceanurazvan** [comment]
@DivvSaxena there is not just one location of a file, we need to check all the files containing `css` with `px` size and convert them to `em`. We need to be careful so that the size in px will remain the same as it is right now in default zoom.

**Comment by topliceanurazvan** [comment]
Since this refactoring has a big impact on Monokle ( some things might become broken and would create lots of bugs ) and we would not benefit too much - even not at all - from converting `px` to `rem`, we will close the issue for now.
