### ISSUE TITLE
Monokle Desktop icon is not showing

### ISSUE THREAD

**Issue by kingsathurthi** [kubeshop/monokle#1296]
I have installed Monokle in my laptop and I see empty icon for the application please find below details.

Monokle Version: Monokle v1.5.0 release
Operating System: Ubuntu Desktop 20.04
![Screenshot from 2022-02-03 20-07-46](https://user-images.githubusercontent.com/24542711/152364127-631ed5d9-36b3-4b15-b5bc-7fc00df7c427.png)

**Comment by olensmar** [comment]
thanks for reporting @kingsathurthi - looking into it!
