### ISSUE TITLE
Unable to click "Next: Select a Template" button

### ISSUE THREAD

**Issue by alex-zavrazhniy** [kubeshop/monokle#1319]
**Describe the bug**
'Next: Select a Template' button on 'Create a Project from a Template' wizard is disabled when going back from the second step to the first one.

**To Reproduce**
1. Go to 'START A PROJECT'
2. Click on 'Start from a template'
3. Enter any 'Project Name'
4. Click 'Next: Select a Template'
5. Click 'Back'
4. See 'Next: Select a Template' button is disabled.

**Expected behavior**
'Next: Select a Template' button should be enabled because I already entered the project name and the location earlier

**Screenshots**
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/316736/153084747-9fc03383-f0cd-40de-b621-3dac5e03abc5.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.5.0

**Comment by olensmar** [comment]
thanks @alex-zavrazhniy - good find!
