### ISSUE TITLE
Make it obvious when the source is invalid

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1342]
Currently the source-editor does not save resources that are invalid yaml - which could be confusing for users since there is no indication of this... just as an experiment I made the editor background "red-ish" to indiciate when the content is invalid - see below - which made this behaviour much more clear and also enticed me to correct my errors.. 

not saying this is how we should do it but it would be great to give users a clear understanding... 

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/1917063/153582371-f3886279-9649-465f-872f-1188ee7ee73d.png">

**Comment by devcatalin** [comment]
I think we should try a red color that's closer to black if we want to change Monaco's background for this

And maybe we could also show something like this at the top:
![image](https://user-images.githubusercontent.com/20538711/153591763-bc0f6574-16ad-4ac6-9c29-050e1a7521dd.png)

**Comment by olensmar** [comment]
good suggestions @devcatalin - we could even show the errors in panel below the editor!? Could there be some "changes have not been saved" indication in/around the editor!? @tommywhitehead  ?

**Comment by devcatalin** [comment]
if we show the errors in the panel below editor, then the "Changes have not been saved" text can go to the top like in my screenshot
