### ISSUE TITLE
Visualisation map/graph of the k8s components and their relations

### ISSUE THREAD

**Issue by fog1985** [kubeshop/monokle#1349]
**Is your feature request related to a problem? Please describe.**
Yeah. I have not seen any good visualization tool on a market which shows real nice UI map of k8s components and how they are connected to each other. 

**Describe the solution you'd like**
I can check for example security visualization and see the UI map of roles, role bindings users etc. How they are connected and so on and so forth. 

**Describe alternatives you've considered**
You can split visualization based on the groups. Not all the objects together. It will be too complex and not readable. But let's say security things, network, pods, traffic flow etc. 

**Additional context**
No additional context. UI and visualization capability of k8s objects and their relations.

**Comment by chargio** [comment]
We are working on a graph visualization that will provide a solution for this.
It is currently available in the cloud app.monokle.com and it is being added to the Desktop.
Tests and comments are welcome, there are improvements that can be done to it

**Comment by olensmar** [comment]
@fog1985 we've added a Graph View to Monokle as of late - can you give that a try to see if it helps in this regard?

**Comment by fog1985** [comment]
> @fog1985 we've added a Graph View to Monokle as of late - can you give that a try to see if it helps in this regard?

Thanks @olensmar . Will check and get back to you with the feedback.
