### ISSUE TITLE
Allow scrolling and copying error messages

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1353]
**Is your feature request related to a problem? Please describe.**
When having a very large error message, it's not possible to scroll it, nor copying it to google the error message. 

**Describe the solution you'd like**
Scrollable and copyable error messages

**Describe alternatives you've considered**
N/A

**Additional context**
![2022-02-15 14 47 51](https://user-images.githubusercontent.com/27779735/154046993-612f5497-7c4b-46e1-82d5-24d78cec7f71.gif)

**Comment by devcatalin** [comment]
Thanks @aabedraba for reporting this. You should be able to copy the entire text from the Notifications pane, click on the bell icon in the top right.

But, we should still make the notification scrollable and maybe add the same copy text button to the popup.

**Comment by aabedraba** [comment]
> You should be able to copy the entire text from the Notifications pane, click on the bell icon in the top right.

Great! Thanks, didn't know that. 

I'd still wish to be able to copy specific parts as copying the entire messages in some occasions might not be useful.

But adding the copy button to the popup is also nice :) 

Thanks again

**Comment by aabedraba** [comment]
I'll close this issue as #725 has it all!
