### ISSUE TITLE
Namespaces are not listed when using template

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1372]
**Describe the bug**
When creating a resource from template that has a namespace dropdown, namespaces are not lised.

**To Reproduce**
1. Create a resource from the template
2. Try assigning a namespace
3. Only namespace option is "None"

**Expected behavior**
List my context's namespaces

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/154320171-90867b18-992d-4221-8cc7-2b58ca3565f9.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.5.1

**Additional context**

**Comment by olensmar** [comment]
thanks @aabedraba - this widget currently shows the existing namespaces defined in your local manifests - and not the namespaces in the currently configured cluster - which perhaps it should !?

**Comment by aabedraba** [comment]
Actually, while trying to debug this, I did create a Namespace through Monokle, and it still did not appear. 

> not the namespaces in the currently configured cluster - which perhaps it should !?

I would totally expect that, yes.
