### ISSUE TITLE
Manage namespaces for cluster context

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1377]
I would like to specify which namespace(s) Monokle should work with for a specific cluster context - either for security reasons (i.e. I don't have access to all namespaces) or for performance reasons. These would be managed on a per-context basis.

**Comment by tommywhitehead** [comment]
Ok, here's a good start I think. It covers many use cases–including scalability–without creating too many window-on-window interactions. 

I don't know how easy this will be to implement. Let's discuss in tomorrow's UX call.

https://www.figma.com/file/DMoJNw20e0m1Pr1HqTXx3B/%231377-Manage-namespaces-for-cluster-context?node-id=0%3A1

**Comment by devcatalin** [comment]
This was done in 1.6
