### ISSUE TITLE
Monokle alerts when an update is available 

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1397]
**Describe the enhancement you'd like to see**
As a user, I'd like to see an indicator that there's a new version for Monokle ready to be installed - it was downloaded in the background. Pretty much like Spotify or Chrome.
Another issue, is that after the auto update is executed, a pop up warns me to install, but this is not possible, actually a restart is needed since the patch has been applied already and there is no need from the user to install it

##Acceptance criteria
- [ ] I can see (blue dot or akin) there is an update when Monokle is open
- [ ] After I restart Monokle, the update is applied

**Comment by julioramosest** [comment]
Per UX discussion, we provide a floating popup that informs the user they can enjoy a new version
- Restart CTA installs new version and restarts right away
- dismissing the message: the update would be installed anyway the next time the user starts the app.

Figma file: https://www.figma.com/file/Ec6B8EsjP2yfrgViPRRGwh/%231397---restarting-Monokle-to-install-new-version?node-id=2%3A9421
