### ISSUE TITLE
Can't install the downloaded .deb file.

### ISSUE THREAD

**Issue by Rohan749** [kubeshop/monokle#1401]
After downloading the Monokle-linux-1.5.1-arm64.deb, I tried to install the file. 
It says- "The following packages have unmet dependencies".
I downloaded the required dependencies: helm and kubectl, but it didn't work. 
Need help.
![Screenshot from 2022-02-23 18-38-55](https://user-images.githubusercontent.com/90546860/155326711-3ef6b674-a3c4-433c-ba72-4add7deb9a87.png)

**Comment by erdkse** [comment]
Thank you @Rohan749 for reporting this issue! We will check what is wrong and inform you back as soon as possible.

**Comment by olensmar** [comment]
judging by https://www.electron.build/configuration/linux#debian-package-options we need to need to remove some dependencies for the deb linux target in package.json

**Comment by devcatalin** [comment]
I tested this by installing Monokle using the following command:
```
sudo dpkg -i Monokle-linux-1.5.1-arm64.deb
```
and it threw me a similar error, which told me the `libxss1` package must be installed
thus, I installed it with the following command:
```
sudo apt-get install libxss1
```
and then I ran the first command again, which now worked without any errors and Monokle was installed and works correctly

**Comment by andreiv1992** [comment]
Same for me

**Comment by olensmar** [comment]
I installed Monokle using the appImage on Ubuntu which worked without any errors - does the appImage include this dependency? or perhaps it's not actually needed but incorrectly set as required in the .deb image? 

https://www.electron.build/configuration/linux#debian-package-options doesn't list libxss1 as a default dependency for .deb packages though!?

**Comment by andreiv1992** [comment]
Yes, it seems that libxss1 is for deb packages.

**Comment by chlete** [comment]
@Rohan749 have you you tried the new version of Monokle (1.6.3) and installed the dependencies?
`sudo apt-get install libxss1`
