### ISSUE TITLE
Define a static title for resource form editor

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1404]
**Describe the enhancement you'd like to see**

Currently the Form Editor Title will hold the name of the type of the resource edited. In this case "Service".
![Screenshot 2022-02-23 at 18 21 45](https://user-images.githubusercontent.com/1978959/155373075-b101fc5a-f35d-44bc-a5b9-092a9991480e.png)

[](url)
Please change it to a generic static name, so it's easier to reference to. Suggestion:
"Resource Form Editor"

**Additional context**

**Comment by olensmar** [comment]
I think "Resource Form Editor" is too long (it will get truncated) - how about just "Form" as we had it initially?

**Comment by chlete** [comment]
> I think "Resource Form Editor" is too long (it will get truncated) - how about just "Form" as we had it initially?

It makes sense. Form sounds good to me 👍
