### ISSUE TITLE
Can't deploy manifest on Ubuntu

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1408]
**Describe the bug**
While clicking the button `Deploy`, it doesn't execute the expected action. Keeps loading indefinitely.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Ubuntu Desktop ( 20.04.3 LTS)
2. Click on Deploy button'
3. Returns `ENOENT` error

**Expected behavior**
The manifest is deployed into Kubernetes after clicking the deploy button.

**Screenshots**
![image](https://user-images.githubusercontent.com/1978959/155761320-1c3a7e80-5dc3-4bf5-80c0-4586b01db5d6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version  20.04.3 LTS

**Comment by olensmar** [comment]
this should be working now!
