### ISSUE TITLE
Plugin import: invalid URL reported when it's valid

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1414]
**Describe the bug**
Trying to import a plugin with the repository url for the second time (after failing once) reports invalid repository URL on a valid URL. 

**To Reproduce**
1. Try importing a plugin with invalid `package.json`
2. Close import window, and open it again (url is still there)
3. Import the same link again
4. "Invalid repository URL shown"

**Expected behavior**
Trying to import again the plugin should import successfully or show error message. 

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/156331807-f1e25882-b85f-4846-9f03-d8f7e8689f61.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.5.1

**Additional context**

**Comment by aabedraba** [comment]
> In this case I'm thinking we are not very good at showing the error, you probably have an invalid URL in the repositoryUrl field from the package.json file, could you check and confirm?

Actually the screenshot is wrong. I uploaded the wrong one. 

This is the correct one: 
![image](https://user-images.githubusercontent.com/27779735/156851841-a996cd8b-4655-4623-b1dc-3c2264472cf2.png)

**Comment by aabedraba** [comment]
You can replicate the error with this repository's tree here https://github.com/aabedraba/monokle-templates-plugin/tree/860bb2be971adde85694b9456c39b6f08ccc95b2

**Comment by erdkse** [comment]
@aabedraba Can you try with this branch and tell me if you still experience the problem please - I updated the handling this kind of stuff - You can now directly install and update plugins from the branches rather than the main

https://github.com/kubeshop/monokle/tree/erdikose/feature/handle-plugin-url

**Comment by aabedraba** [comment]
Hi @erdkse 
This branch does not report an error when importing the plugin, so I can't test if it works or not. 

Monokle 1.5.1 behavior:
![image](https://user-images.githubusercontent.com/27779735/156874036-4430021e-cde2-42be-a5b3-edea9cafec95.png)

Fix branch: 
![image](https://user-images.githubusercontent.com/27779735/156874052-1b1d5bb1-537e-44ff-be4a-6985a90df701.png)

I should also remind that the error happens when
1- Invalid import happens (something wrong in the plugin config)
2- Fix is done to github repo with the plugin
3- Subsequent imports report "Invalid URL repository"

Only way to fix it for me has been force closing Monokle and opening again.

**Comment by erdkse** [comment]
@aabedraba Ok I will improve error showing - planning to print [file name]: ERROR

And will test in order of you wrote - thank you for your feedback

**Comment by aabedraba** [comment]
@erdkse awesome! Please let me know if I can help with testing or anything else 😊

**Comment by erdkse** [comment]
Hey @aabedraba! You can try again with my PR. I solved your issue and am showing a better error message right now. And If any JSON file is invalid I just don't the plugin is saved

**Comment by aabedraba** [comment]
Great error handling! Thanks a lot for that!

Although the reported problem still persists. Once the error is shown once, the following attempts to import the repository all fail.

Previously it used to reported invalid URL (when it was actually valid), now it does not report it. 

![2022-03-06 23 52 44](https://user-images.githubusercontent.com/27779735/156939757-4a7cd55d-e157-4064-a136-5ec681358491.gif)

**Comment by erdkse** [comment]
hey @aabedraba It was a cache issue - The input wasn't showing the same error message for the next tries - Here it is solved

https://github.com/kubeshop/monokle/pull/1440

**Comment by aabedraba** [comment]
Thanks @erdkse !!
