### ISSUE TITLE
Updating plugin on github, does not update Monokle's

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1415]
**Describe the bug**
When trying to update plugin or importing after fixing bugs, Monokle does not fetch the latest version. 

I suspect it caches the github results, as they're GET requests...

**To Reproduce**
1. Update plugin in github repo
2. Try updating the plugin in Monokle's interface
3. "No updates available"

Another situation when this happens is when trying to import plugin after a failed one:
1. Try to import an invalid plugin (maybe an invalid package.json)
2. Fix the bug and import again
3. "Invalid package.json" is shown

After waiting for some minutes and fetching, it does accept it...
 
**Expected behavior**
Fetching of the latest github repo updates.

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/156331409-0f1a519f-2421-415a-9497-ebbba62bf519.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.5.1

**Additional context**

**Comment by devcatalin** [comment]
Just to make sure, have you updated the `version` field in the `package.json` ?
I think I had this happen to me a couple of times and I had to wait a few minutes before Monokle recognized the update, but we can look further into it.

**Comment by aabedraba** [comment]
> Just to make sure, have you updated the version field in the package.json ?

I have and it still doesn't fetch the latest version. 

On the other hand, I do see the benefit on making the update be trigger by a version bump, but I'd really expect not to do that, and that by clicking on refresh Monokle picks it up directly. 

![image](https://user-images.githubusercontent.com/27779735/156851630-44a4b4dd-3a9e-4b12-83f9-be0dd290ddf7.png)

![image](https://user-images.githubusercontent.com/27779735/156851659-bdaad396-d312-4491-ba25-0f7719f29989.png)

**Comment by erdkse** [comment]
https://github.com/kubeshop/monokle/issues/1414#issuecomment-1059690361

It takes some time for Github to update the file content we download and check - You can see it by visiting raw content of the package.json file

I suggest we handle plugin installation and updates by git command. Wdyt folks @olensmar @devcatalin @andreiv1992

**Comment by aabedraba** [comment]
> It takes some time for Github to update the file content we download and check - You can see it by visiting raw content of the package.json file

Huh, @erdkse , I wasn't able to replicate this. 

Is this what you mean happens?:
1- Make a change to a file, commit it
2- Open raw file and I will see the old version of the file?

**Comment by aabedraba** [comment]
Oh, never mind, I have checked this actually happens!!
When uploading from git cli, the raw version it gets outdated. 
When doing the update from github's website, it get updated instantly. (this was my first way of testing :))

**Comment by olensmar** [comment]
@erdkse @aabedraba can we close this? or is it still an issue?

**Comment by erdkse** [comment]
@olensmar yeah we solve this one - forgot to close, sorry
