### ISSUE TITLE
Show file saved status when updating YAML

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1416]
**Describe the enhancement you'd like to see**
When updating a YAML in Monokle, show an "Autosaved" checkmark, or force user to save manually, like with Postman. 

The feeling when updating a YAML in Monokle is that I'm really not sure what's going on, is it actually saving the file underneath, will I lose the changes if I close the tab/Monokle?

**Additional context**
![2022-03-02 13 53 55](https://user-images.githubusercontent.com/27779735/156338333-4ae35ce0-3d03-42ba-ba89-9b3242aefe46.gif)

**Comment by devcatalin** [comment]
We have an autosave indicator next to the logo
