### ISSUE TITLE
Follow and change kubeconfig context

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1418]
**Describe the enhancement you'd like to see**
As a user, I'd like to be able to "follow" the context of `kubeconfig` and be able to modify from Monokle, in order to keep a consistent experience. 

## Acceptance criteria

- [ ] Use the current context of kubeconfig in Monokle
- [ ] I can switch the context in Monokle and save its state in Kubeconfig
- [ ] When I open `kubectl` or any other tool that reads kubeconfig, I will get the last context used in Monokle
- [ ] Make this behaviour optional with checkboxes: follow kubeconfig state, save current state of kubeconfig

FYI @aabedraba

**Comment by chlete** [comment]
#1418 overrides #1367.

**Comment by aabedraba** [comment]
Sounds great! 

> Make this behaviour optional with checkboxes

Wonder why you believe this should be optional.. Backwards compatibility? There's value in current way of doing it?
