### ISSUE TITLE
Misleading error: Loading kubeconfig file failed - tries to detect presence of kubectl instead of kubeconfig

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1475]
**Describe the bug**
On 1.5.2 nightly, after opening it and selecting a project, an error of not being able to find kubeconfig pops up but the message itself relates of not being able to find kubectl. Which is by the way installed and not missing.

**To Reproduce**
1. Open Monokle
2. Open a project
3. Check the bell/alerts symbol
4. See error:
```
Title: Loading kubeconfig file failed. Description: Command failed: kubectl auth can-i --list --namespace=default
/bin/sh: kubectl: command not found
```

**Expected behavior**
- Kubeconfig's presence should be detected independently from `kubectl` presence
- Kubectl is actually installed and not sure the reason why `kubectl is not found`
- Helm is also installed, shouldn't error

**Screenshots**
![Screenshot 2022-03-16 at 15 53 36](https://user-images.githubusercontent.com/1978959/158618985-3aacd5be-ea73-47c8-9ab2-a0e5fc78ca7f.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.3
 - Version 1.5.2 - nightly-2022-03-15.0

**Additional context**

**Comment by andreiv1992** [comment]
> Kubectl is actually installed and not sure the reason why kubectl is not found
I don't know why this errors out.. maybe it's installed but it's not in the proper path

I'll fix the first part of the expected behavior
> Kubeconfig's presence should be detected independently from kubectl presence
