### ISSUE TITLE
Improve cluster changes and triggers

### ISSUE THREAD

**Issue by andreivinaga** [kubeshop/monokle#1480]
At this time we have two listeners for for cluster related changes:
- https://github.com/kubeshop/monokle/blob/main/src/App.tsx#L246-L252
- https://github.com/kubeshop/monokle/blob/main/src/redux/services/kubeConfigMonitor.ts#L27-L30

If we make any cluster related changes(changing cluster) both or those are triggered. Ideally we should have just one in kubeConfigMonitor and trigger changes across all windows open from the main process

**Comment by devcatalin** [comment]
Related to #1816 and #1794

**Comment by devcatalin** [comment]
Closed the above two referenced issues in favor of: https://github.com/kubeshop/monokle/issues/1418

**Comment by devcatalin** [comment]
Watching the Kubeconfig file has been reworked
