### ISSUE TITLE
Develop a way to send bug reports from the app

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1507]
It would be nice to have a way to send bug reports from within Monokle.

I'm thinking that there should be an option under the system menu, which when clicked it will open a browser and navigate to [Create new Issue](https://github.com/kubeshop/monokle/issues/new). Additionally, it should auto-fill the description issue with some information about what environment and state the app was in.

This idea is inspired from the following website: https://go.dev/tour/welcome/1
Click on the bug icon from the top right of the page and it will send you to create an issue on their GitHub page.

**Comment by erdkse** [comment]
https://github.com/sindresorhus/electron-unhandled#reportbutton
