### ISSUE TITLE
Missing or non standard keyboard shortcuts 

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1521]
**Describe the bug**
Monokle doesn't have some actions mapped to keyboard, or they are assigned to non-standard.

Missing:
~~- New Window~~
- Find
- Replace

~~Assigned to non standard shortcuts~~
~~- Zoom in / out~~

**To Reproduce**

<img width="477" alt="Screenshot 2022-03-28 at 10 32 32" src="https://user-images.githubusercontent.com/1978959/160364814-dda8becd-3bea-4027-b348-6f6c8c0525ad.png">

**Expected behavior**
Use standard keyboard short cuts for zoom in.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version 1.6.0

**Comment by jmelnych** [comment]
Fixed: zoom in/zoom out,
add new shortcut for opening new Monokle window.

Still no functionality for:
- Find
- Replace
Needs more discussion as it is a new feature.

**Comment by julioramosest** [comment]
Find design for the modal popup showing shortcuts list here: https://www.figma.com/file/fDfEVnJE9tnEFGEREjW4mg/Keyboard-shortcuts-modal?node-id=0%3A1

<img width="1440" alt="About Monokle- modal" src="https://user-images.githubusercontent.com/97731654/161968051-6190b810-0766-4569-8131-02f96bf7512f.png">

**Comment by devcatalin** [comment]
I think that we have to remove the `Save` shortcut since we have auto-save everywhere. We just need to check if the shortcut is still used anywhere or not.

@julioramosest if we remove that shortcut, I think you would have to remake the illustration from the top
