### ISSUE TITLE
PATH / environment is not read

### ISSUE THREAD

**Issue by scalp42** [kubeshop/monokle#1538]
**Describe the bug**

It cannot interact with the remote cluster.

**Screenshots**
![Screen Shot 2022-03-30 at 20 52 35](https://user-images.githubusercontent.com/1475276/160973126-af508acf-04e7-4659-9241-f1b9ca9d8fa5.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version `1.6.2` (Monokle-mac-1.6.2-universal)

**Additional context**
Seems that a fix was shipped here: #1285 

When I try to update kube config by specifying `aws` path, I get a bit further but now it won't read my `.aws/config` correctly until I also specify full path. If I do, it still won't work as it won't interpolate an ENV variable I need for MFA:

```
[profile main]
include_profile = example
credential_process = sh -c '/opt/homebrew/bin/aws-vault exec main --mfa-token=$(/opt/homebrew/bin/oathtool --totp --base32 --digits=6 $AWS_MAIN_IAM_TOTP_KEY) --duration=1h --json'
```

In that case `$AWS_EXAMPLE_IAM_TOTP_KEY` is empty and of course it won't work.

Let me know what you think, thanks folks!

**Comment by erdkse** [comment]
Thank you @scalp42 for reporting this issue. We are aware of and working on this PATH/environment issue. We are planning to release 1.6.3 with this fix.

**Comment by scalp42** [comment]
sweet, thanks for the quick response 🙌

**Comment by erdkse** [comment]
hey @scalp42 could you please try this release and tell us if you are still receiving the issue?

https://github.com/kubeshop/monokle/releases/tag/v1.6.3-nightly-2022-04-05.0
