### ISSUE TITLE
Integrate Trivy into Monokle

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1539]
## Description
As a user, I would like to validate my manifests so they follow best security practices and protect me against misconfigurations. Trivy is a tool that solves that, but is not yet integrated into Monokle. It'd would be nice to get an output of such recommendations on Monokle

## Idea
- Trivy is independently installed from Monokle
- Monokle, warns me through Trivy, about possible misconfigurations
- Monokle based on the feedback from Trivy, suggests me corrective actions - but won't apply them 

## Acceptance criteria
- [ ] Trivy can be installed and run on MacOS/Windows/Linux and can run mostly offline after downloading the database
- [ ] Monokle reads the report from structured output from Trivy (JSON)
- [ ] Monokle can find and execute trivy seamlessly across the platforms above
- [ ] Monokle shows a warning or highlights possible misconfiguration errors 
- [ ] Monokle suggest fixes for the user based on the output from Trivy

**Comment by chlete** [comment]
Hi @pentago thanks a lot for the feedback! 
We compared a few options, including Kubescape. We are in favour of Trivy since it has a richer output and would allow a better UX in Monokle. Plus, it needs an active network connection, and we are a bit hesitant to ask our users to keep an active connection for a core functionality - validation. Nevertheless, Im interested to understand your preference:
- What do you find cooler in Kubespace than in Trivy?

**Comment by pentago** [comment]
First and foremost, I think that scanning for NSA/MITRE/DevOps Best practices frameworks is ideal for users who are 
 maintaining compliance with any or all of those frameworks. Haven't used Trivy extensively but either way, scanning with ARMO is just an request away so not a biggie :)

**Comment by chlete** [comment]
Got it @pentago, thanks!
Speaking about biggies, is there any biggie Monokle is missing? :)

**Comment by pentago** [comment]
Hey @chlete not sure about biggies, current feature set is decent for a lot of use cases.

What I personally would like to have is Kustomize environment diffs as I work with Kustomize exclusively.

For example, selecting 2 overlays and having a diff button/context menu/shortcut could help me to easily spot differences in the Navigator column. `git diff` style of differneces comes to mind where differences could be highlighted in green/red/+/-  so I see immediately what is extra/missing from compared environment.

Additionally, even more helpful would be added compare an arbitrary number of overlays, for example, comparing 5 overlays at the same time.

Also, does Monokle supports [Kustomize Components](https://kubectl.docs.kubernetes.io/guides/config_management/components/)?

**Comment by chlete** [comment]
Hi @pentago 

Sorry for the late answer and thanks a lot for the detailed reply :)

>Hey @chlete not sure about biggies, current feature set is decent for a lot of use cases.

👍  glad to hear we have covered most of your needs!

>Additionally, even more helpful would be added compare an arbitrary number of overlays, for example, comparing 5 overlays at the same time.

Thats a great idea! We are thinking to have a unique pane that allows to diff, no matter if its kustomize, helm or local vs cluster output.

>Regarding this, could there be a Monokle extension for VS Code?

At the moment we don't have it planned. I understand the practicality of having one tool for everything. However, with Monokle we focus on the workflows that a developer may need to go through editing/using manifests and makes it easier to implement in a different application.

> Also, does Monokle supports [Kustomize Components](https://kubectl.docs.kubernetes.io/guides/config_management/components/)?

We do support Kustomize output preview, meaning you can read the output of kustomize command, see the yaml generated and grouped by type of resource. Does this help? 

It's really great feedback that you gave us. Thank you! We are working now on improving the UX/UI as well. Stay tuned for our 1.7.0 Release! by the way we just release [1.6.3](https://github.com/kubeshop/monokle/releases/tag/v1.6.3), in case you want to give it a spin :)

**Comment by pentago** [comment]
Great! Really like the project, it helps a lot to see entire Kustomize project from above instead opening file by file.
Looking forward to see where it's going :)
