### ISSUE TITLE
SealedSecrets schema should be evaluated in a better way

### ISSUE THREAD

**Issue by pentago** [kubeshop/monokle#1543]
Currently, when I load my Kustomize project containing SealedSecret, I get this:

![](https://i.imgur.com/MbDaulm.png)

Tooltip at the bottom tells me that I'm wrong with using Opaque type for the secret while that's not true.
[Official doccumentation](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) states that Opaque type is for `arbitrary user-defined data` which this is actually.

Can we detect secret types properly?

**Comment by olensmar** [comment]
thanks @pentago - looking into it!

**Comment by olensmar** [comment]
@pentago is your repo public so I can work with the same resources?

**Comment by pentago** [comment]
hey @olensmar , I made a dummy repo for you to be able to test the issue, here it is https://github.com/pentago/monokle-sealedsecrets-test

**Comment by pentago** [comment]
Amazing, thanks for quick support @olensmar !

**Comment by olensmar** [comment]
thanks for your feedback @pentago! super helpful!
