### ISSUE TITLE
Missing editor error highlighting

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#1573]
**Describe the bug**

During https://github.com/kubeshop/monokle/pull/1571, we noticed the editor no longer shows error highlighting.

**To Reproduce**

1. Open a resource with an error.
2. The bug is that the error no longer is highlighted.

**Expected behavior**

1. The error should be highlighted.

**Screenshots**

**Additional context**

- This is a regression. It works in Monokle v1.5.0.

**Comment by WitoDelnat** [comment]
The missing highlighting seems to be related due to a dependency issue.

```
"monaco-editor-webpack-plugin": "4.2.0",
"monaco-yaml": "3.2.1",
"react-monaco-editor": "0.46.0", // monaco editor ^0.28.1
```

to

```
"monaco-editor-webpack-plugin": "4.2.0",
"monaco-editor": "0.31.1",
"monaco-yaml": "3.2.1",
"react-monaco-editor": "0.47.0", // monaco editor ^0.33.0
```

I suspect we added the peer dependency because of another problem. I’m quite sure we are not within the supported version matrix as seen [here](https://github.com/microsoft/monaco-editor/blob/d0010709380c2f7976dec7966a45e8c34c103b3d/webpack-plugin/README.md): monaco-editor >= `0.31.0` should use monaco-editor-webpack-plugin `7.*.*`.The problem with upgrading is that we use an internal method that is no longer available. 

```
// src/components/molecules/Monaco/editorHelpers.ts:4
import {getDocumentSymbols} from 'monaco-editor/esm/vs/editor/contrib/documentSymbols/documentSymbols';
```

---

update: I managed to downgrade with the following versions and now it works again. This confirms my hypothesis.

```
"monaco-editor-webpack-plugin": "4.2.0",
"monaco-editor": "0.28.1",
"monaco-yaml": "3.2.1",
"react-monaco-editor": "0.46.0",
```

**Comment by devcatalin** [comment]
Thanks for investigating this @WitoDelnat. Let's downgrade for now so we can have the highlighting working for 1.6.3 and keep this issue open so we know to properly to the upgrade for 1.7 or later.

**Comment by WitoDelnat** [comment]
Hello @remcohaszing 👋 Much appreciated for letting us know you found a solution. Also great work on `monaco-yaml` - it's working excellent for us!
