### ISSUE TITLE
Ability to remove recent projects from side bar when opening Monokle

### ISSUE THREAD

**Issue by kylehodgetts** [kubeshop/monokle#1585]
**Describe the enhancement you'd like to see**
Sometimes I create test projects to test out ideas and open them in Monokle.
After I'm done testing, I delete them but when I open Monokle, it still shows them in my recent projects.

It would be nice to be able to remove them so my recent projects side bar doesn't get too cluttered or if the project doesn't exist anymore, Monokle doesn't show it in the recent projects.

**Additional context**
<img width="459" alt="Screenshot 2022-04-08 at 13 28 39" src="https://user-images.githubusercontent.com/6544380/162435583-4b5e9b0a-2d38-4145-b890-45b4f448443e.png">

TLS test doesn't exist anymore but still shows in the side bar and I cant remove it

**Comment by devcatalin** [comment]
Thanks @kylehodgetts , we can definitely add a `remove` button for the projects in that list.
Additionally, we could also check if the folders still exist to remove the ones that do not.
