### ISSUE TITLE
Prompt for target namespace when deploying Helm chart directly

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1626]
When I select the "Deploy" button for a selected Chart.yaml file I expect to be prompted for the target namespace (as when I deploy individual resources) - now I just get a confirmation dialog which will install in whatever namespace is configured in the chart 

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/1917063/164000009-15ec4a81-f0bd-4389-9fb9-d93b57046e50.png">

**Comment by devcatalin** [comment]
I think this might be an outdated issue. At the moment the deploy button for Chart.yaml files is disabled and only available for values files.
Should we re-enable it? If so, should we have a modal where the user selects the desired values file or preview configuration and then the namespace?
