### ISSUE TITLE
Deploy button prompts to deploy wrong chart

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1632]
Steps to reproduce:
- select a values-file in a Helm Chart
- select the Install button but cancel the install
- select a Chart.yaml file in a different Helm Chart
- select the Deploy button
Expect to see the deploy modal for the selected chart - but I see the install modal for the previously selected values file

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/1917063/164169174-a3a21287-b544-433d-9d5c-4d4a7827d6c0.png">

**Comment by devcatalin** [comment]
Fixed in https://github.com/kubeshop/monokle/pull/1666
