### ISSUE TITLE
Handle deletion of .monokle file

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1641]
**Describe the bug**
If the `.monokle` file is deleted from the project, the application turns black and it's in an error state.

**To Reproduce**
1. Create a new empty project
2. Go to the File Explorer
3. Click on the 3 dots for the context menu next to the `.monokle` file
4. Click on delete and confirm deleting the file

**Expected behavior**
We should probably return to the homepage and fix the state after the `.monokle` file is deleted.

**Comment by erdkse** [comment]
This is a general issue I suppose. It is not only related to .monokle file. If you remove any other file you will see this error.

**Comment by erdkse** [comment]
Fixed already!
