### ISSUE TITLE
Wrong button alignment

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1642]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/20538711/164489608-1e9ab505-a1bb-4f6d-a369-92cb828ae5c6.png">

The Deploy and Diff buttons are no longer aligned to the right. This should be consistent with the Navigator title bar, having the actions aligned to the right.

**Comment by stan-gabriel** [comment]
From the component implementation, I can see that buttons and arrows should be aligned to the right. Is this correct?

![image](https://user-images.githubusercontent.com/12400110/165478536-36857414-9fc7-41ac-856e-533b031651e6.png)
