### ISSUE TITLE
.monokle not being created when starting from a template

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1643]
When I create a new project using a template, I can see the generated resources in the navigator, but I cannot see the `.monokle` file being created in that folder, which works well when I create an empty project.

**Comment by erdkse** [comment]
Is this really an issue since .monokle file is created whenever you change a setting's value? If the .monokle file doesn't exist the application will use the default file anyway.

But anyway, we can create a blank .monokle file even if all the values are default. @devcatalin ?

**Comment by devcatalin** [comment]
Yes, let's create a blank `.monokle` file in order to be consistent

**Comment by erdkse** [comment]
looks like already fixed!
