### ISSUE TITLE
Provide more information if Cluster access failed

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1645]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/20538711/164499891-2c646e46-e539-44f5-8d34-c1b673f9c62c.png">

See the notification above.
It would be nice to provide more information to the user to know what this alert means, how it affects them and what they can do about it.

At the same time, the Cluster Selector still shows that the Cluster is "Configured" which might confuse the users if they had this alert show up.

**Comment by chargio** [comment]
This is supposed to be fixed
