### ISSUE TITLE
Character removed from the values file name

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1647]
We have two users that reported the following bug:

> On m1 mac os monterey 13.1 and macbook pro, when I open a chart (in this case NATS helm) and go to "Helm Charts" I see that the values file is called alues.yaml. Exactly the same behaviour on both laptops.

At the moment of writing we were not able to reproduce the error but we should investigate it further.
One way to handle this would be to add logging for every function related to values files, enable the logging in a Monokle build and then ask the users that reported this bug if they'd like to help us debug the problem.

**Comment by olensmar** [comment]
this seems to happen when the folder containing the values file is the root folder of the project 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1917063/164704745-6ba3039a-a989-4ca7-a1a4-eb7fa1021c43.png">
