### ISSUE TITLE
Clicking on Install update does not work

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1655]
**Describe the bug**
![2022-04-22 15 15 31](https://user-images.githubusercontent.com/27779735/164704347-cc077ff6-d801-4969-a768-794e8f7c0890.gif)

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Monokle version: 1.6.2

**Comment by andreiv1992** [comment]
This part of the app was changed in #1397, let us know if the problem persists.
