### ISSUE TITLE
When rejecting Telemetry, options are not changed

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1656]
**Describe the bug**
After rejecting Telemtry by clicking "I'm not", the options show that the telemtry is still active

**To Reproduce**
1. Install Monokle from ground up 
2. Receive notification on Telemetry
3. Click "I'm not"
4. Go to Telemetry options in settings 

**Screenshots**
![2022-04-22 15 20 05](https://user-images.githubusercontent.com/27779735/164704991-3cb538be-eb33-4f99-bb0a-6a5f5bc02f3d.gif)

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Monokle version: 1.6.3

**Comment by erdkse** [comment]
I think that It just opens the settings pane to allow users to disable the options. It doesn't do automatically. There is no code implemented for this purpose. Would you like to have it? @aabedraba @chlete

**Comment by olensmar** [comment]
I agree that it's confusing - if I click "i'm not" i would expect Monokle to automatically disable telemetry - not require me to (figure out how to) do so...

**Comment by erdkse** [comment]
Ok, that makes sense. So I believe the best way is to disable 2 options at 1 time. Preparing the PR.
