### ISSUE TITLE
Black screen when changing projects

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1670]
**Describe the bug**
Black screen when changing projects.

Try changing projects multiple times to replicate this issue.

**Screenshots**
![2022-04-27 13 27 40](https://user-images.githubusercontent.com/27779735/165487783-49ccba42-081d-42ce-aff6-c7b95bd21b80.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] 1.6.3

**Comment by WitoDelnat** [comment]
This is no longer reproducible. @aabedraba and I had a look together, but it seems gone. This was tested on 1.6.3 and I think I might've fixed a related bug. For now we're closing and should he run into it again we will spend additional effort to thoroughly test for infrequent race condition.
