### ISSUE TITLE
Add relations-pane at the bottom of the Object Navigator

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#169]
For quickly identifying resources related to the currently selected one, the "relations pane" would contain those in a "shortlist". 

Mockups:
<img width="1440" alt="#169 Add relations pane 2" src="https://user-images.githubusercontent.com/4236167/129988088-89f5288f-cccb-49dd-9567-13874f636b66.png">
<img width="1440" alt="#169 Add relations pane 1" src="https://user-images.githubusercontent.com/4236167/129988091-12b3d19e-c4a9-464e-a46b-11b5451e9fac.png">

Figma link:
https://www.figma.com/file/F5ocBmTaEBQ51FcdS4bDrk/169-Add-relations-pane-at-the-bottom-of-the-Object-Navigator?node-id=0%3A1

**Comment by kambydyne** [comment]
- [ ] make the navigator self contained
- [ ] create a vertical split view
- [ ] move pane split view width/height info to redux
- [ ] implement basics of the extension framework to support relations box as a bundled extension
- [ ] implement relations box

**Comment by devcatalin** [comment]
Closing this because of the new Smart Pane: https://github.com/kubeshop/monokle/issues/3807
