### ISSUE TITLE
Improve UX of app crash

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#1700]
**Is your feature request related to a problem? Please describe.**
When the application crashes I see a black screen and I must restart the application.

**Describe the solution you'd like**
I'd like a warm animation and a button that takes me home. Maybe we could include a link to our GitHub to make it easier to report an issue.

**Comment by erdkse** [comment]
I believe somehow related #1507

**Comment by WitoDelnat** [comment]
Closing this in favour of https://github.com/kubeshop/monokle/issues/1700.
