### ISSUE TITLE
Create a button to "Check for updates" 

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1703]
**Describe the enhancement you'd like to see**
Monokle 1.7 was just released! 🥳 

But when opening Monokle 1.6.3, I haven't received any notification to update. 

Could we create a "Check for updates" button to search and download new versions?

**Comment by devcatalin** [comment]
Hi @aabedraba , we didn't have the builds for updates ready yesterday so that's why the modal didn't appear.
We will create them today as soon as possible

**Comment by aabedraba** [comment]
Thanks @devcatalin 

I still think it's a good idea to have a proactive way of looking for the updates 🤔 

But if we're sure that it's always displayed when a new release is there, maybe it's not an important issue, so feel free to close it :)
