### ISSUE TITLE
Mark resources that exist in current cluster

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#171]
When loading / previewing resources it would be nice to easily identify which already exist in my configured cluster - some kind of visual marker!?

Perhaps red = doesn't exist, orange = exists but different, green = exists

**Comment by catalinhoha** [comment]
@olensmar should we close this now that we have the Cluster Compare feature?

**Comment by chargio** [comment]
Closing this as it looks like finished

**Comment by olensmar** [comment]
thanks - the Cluster Compare does the trick so we can close it
