### ISSUE TITLE
Informing the user some change is being saved

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#1712]
Our system autosaves some changes, such as code changes and others. As a user I would like to be shown a label informing me that some change is being autosaved, so that way I don't look further for saving CTAs and I understand the logic. That label must float just for some seconds, not being persistent or intrusive, and show no further interaction.

**Acceptance criteria**
- [ ] Add "saving" label to the UI

**Comment by devcatalin** [comment]
As an idea maybe we should have a loading spinner somewhere in the UI as most of the auto-save features still take at least 1-2 seconds to actually save.
