### ISSUE TITLE
Diff Panel

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1713]
Two column panel where you can diff two sets of resources
Each column can be configured to show one of the following sets of resources:
- Local resources
- Resources from a Helm or Kustomize preview
- Cluster resources (with selected context, so we could support diffing two clusters as well)

See images for more details:

![image](https://user-images.githubusercontent.com/20538711/166466303-45b9ed9c-967c-4469-8f83-631a8a28e20c.png)

![image](https://user-images.githubusercontent.com/20538711/166466323-fcdda9fa-6a8f-4b8f-923a-0f74fd739184.png)

**Comment by julioramosest** [comment]
This is UX/UI ready - figma file: https://www.figma.com/file/1ffWvrDGoBQU5F5avlG4f6/%231713-Improving-Diff?node-id=0%3A1
