### ISSUE TITLE
Navigation history

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#172]
to quickly move back and forward between resources that I've worked on - back/forward links !?

**Comment by tommywhitehead** [comment]
Mockups:
<img width="1440" alt="#172 Navigation history 1" src="https://user-images.githubusercontent.com/4236167/129991838-e9443aab-4301-4db0-ad40-1b2acd48a33b.png">

Figma link:
https://www.figma.com/file/X38xen59C39kKzjVaxXdsl/172-Navigation-history?node-id=0%3A1
