### ISSUE TITLE
Error handling: Setup global error handling to recover from bugs/crashes

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1721]
As a user, I would like that Monokle, whenever possible, recovers after minor errors and crashes
- [ ] Monokle should be able to recover gracefully from bugs and crashes
- [ ] Gather the error information and send it back (?)
- [x] #1722

**Comment by julioramosest** [comment]
Design for this: https://www.figma.com/file/fq8nw9sPHl6AVaa12R75Z4/%231721-Add-top-level-error-boundary?node-id=0%3A1

**Comment by WitoDelnat** [comment]
Closed by https://github.com/kubeshop/monokle/pull/1715
