### ISSUE TITLE
New Resource action/wizard

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#176]
The possibility to create new resources - with support for resource-type specific templates/wizards.

Initial version for all resource kinds should ask for:
- kind of Resource to create - required
- name - required
- Advanced: (optional)
  - version - required, we will set initial value automatically
  - target namespace (select from existing in project - and cluster?) - optional

This would create an unsaved resource - when the user saves we will prompt for a file/folder (which must be under the current root folder)

**Comment by tommywhitehead** [comment]
@catalinhoha @olensmar Here's a start for this, though we'll probably have to work out more details as you begin building it. 

Mockups:
<img width="1440" alt="#176 New resource action wizard 1" src="https://user-images.githubusercontent.com/4236167/130668155-6d594911-149b-48df-8bee-a0fa95b0a7fa.png">
<img width="1440" alt="#176 New resource action wizard 2" src="https://user-images.githubusercontent.com/4236167/130668160-4acf17fc-57b1-449c-8ddb-0e8fa014f906.png">
<img width="1440" alt="#176 New resource action wizard 3" src="https://user-images.githubusercontent.com/4236167/130668163-af53e907-aed4-417b-8395-6c1dc0962a2a.png">
<img width="1440" alt="#176 New resource action wizard 4" src="https://user-images.githubusercontent.com/4236167/130668164-c1eccfb3-ba3a-40f2-97cc-e21b8cc4f8e1.png">

Figma link:
https://www.figma.com/file/RJ4EeFFVvuja6aZbMyQBiv/176-New-resource-action-wizard?node-id=0%3A1

**Comment by olensmar** [comment]
Thanks @tommywhitehead - this should definitely get us going!
