### ISSUE TITLE
Namespaces list is not in sync with the cluster

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1760]
**Describe the bug**
I have a clean new cluster. I deleted `kubectl`'s cache and cleaned the config file. But still, when I list the namespaces to choose from, Monokle shows me namespaces from old clusters.  

**To Reproduce**
Not sure how to do this, but perhaps try creating a new cluster with a new namespace, have monokle sync that, and then delete the cluster and start a new one without any namespace but the default one.  

**Expected behavior**
Monokle is in sync with my cluster's namespaces.

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/167603493-09ce8fb8-cda3-490b-8318-0a2267445135.png)
![image](https://user-images.githubusercontent.com/27779735/167603843-703787bb-5f14-4842-b619-816724da62df.png)

Kubens showing only one namespace ⬇️ 
![image](https://user-images.githubusercontent.com/27779735/167603911-914b2d9a-e384-48b1-8622-54b1b1940846.png)

`~/.kube/config` ⬇️ 
![image](https://user-images.githubusercontent.com/27779735/167603997-f8cc2a45-abb4-4c74-96c3-2b0b426612f1.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs 
 - Version [e.g. 22] 1.7.2

**Comment by erdkse** [comment]
@aabedraba Can we check this one please, if possible

**Comment by aabedraba** [comment]
Works wonders 😍  @erdkse Thank you!

**Comment by erdkse** [comment]
Thank you @aabedraba !! It now listens to the cluster for all namespaces. I also like the implementation
