### ISSUE TITLE
Saving predefined filter for later usage

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#1766]
**Is your feature request related to a problem? Please describe.**

When working on K8s product I usually need to debug some subset of resources many times
As a software engineer I want to quickly get such subsets with ease. 

**Describe the solution you'd like**
Some easy to use Save/Load option for filters

**Comment by devcatalin** [comment]
Thanks @exu, we had an issue for this for some time https://github.com/kubeshop/monokle/issues/468 , but we didn't know how useful the feature would be. We'll discuss it in the next planning session.

**Comment by topliceanurazvan** [comment]
https://www.figma.com/file/U4DOn5y9MgmdZtN5udL3Qx/Resources-Filter?node-id=0%3A1
