### ISSUE TITLE
Allow to select multiple Kinds on select control 

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#1768]
**Describe the enhancement you'd like to see**
As software engineer I often need to track only some small subset of resource (not single and not all) 

Would be nice to have possibility to select multiple `Kinds`

**Comment by devcatalin** [comment]
@exu just to make sure I understand this enhancement, would you like to be able to filter by multiple resource kinds?

**Comment by exu** [comment]
Yes 

The reason is usually you want to look at some subset of resources in some long debug sessions. 

It could also allow to speed up reloads - as currently they are quite slow
