### ISSUE TITLE
Resume Cluster sessions

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#1772]
**Describe the enhancement you'd like to see**

When I'm not designing manifests I usually debug some resources in K8s. 
The issue is that I want to have everything reloaded right after Monokle start, 
and see last session where I ended - perfectly with recent resources.

It's also about faster reloading of resources (previous issue about use filters when reloading) 
Maybe we could start listening on K8s events somehow and reload stuff in background to make Monokle feels more "real-time" with cluster resources.

**Comment by devcatalin** [comment]
This is related to https://github.com/kubeshop/monokle/issues/708
I like the idea of saving the session to get back where you ended, thanks for the feedback!

**Comment by devcatalin** [comment]
This could be done as a follow-up to https://github.com/kubeshop/monokle/issues/2087

**Comment by chargio** [comment]
Closing as it has been addressed with cluster mode
