### ISSUE TITLE
Project mgmt functionality

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#178]
Allow for switching between different projects - each project containing settings for:
- root folder
- default cluster
- preferences
- k8s version - see #321 
- git-repository - ahead of #720 
- ?

**Comment by devcatalin** [comment]
![image](https://user-images.githubusercontent.com/20538711/147232975-4953330d-1e4d-481b-96fb-dd577a816fac.png)

Related issue: #619

**Comment by mortada-codes** [comment]
https://user-images.githubusercontent.com/20525304/151194885-7f6cecba-50d4-4fb5-ae70-355fa5f2a796.mp4
