### ISSUE TITLE
Enable the graph-view 

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#181]
Before enabling the graph-view we need to fix:
- Auto-layout algorithm
- Coloring / UX

**Comment by tommywhitehead** [comment]
**Part 1: Layout and enablement**

Mockups:
<img width="1440" alt="#181 Enable the graph view 1" src="https://user-images.githubusercontent.com/4236167/129993633-1c2c65c8-b84e-431c-8141-e3667687da8b.png">

Figma link:
https://www.figma.com/file/MpVWN2LRtfwg2Egz7RIQXm/181-Enable-the-graph-view?node-id=0%3A1

**Comment by tommywhitehead** [comment]
Next steps: can we talk about the functionality of the graph? I don't know its capabilities for customization...

**Comment by chargio** [comment]
Closing this, as we have the graph view in this release
