### ISSUE TITLE
Monokle follows current KUBECONFIG context

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#1816]
**Is your feature request related to a problem? Please describe.**

When changing contexts in shell I assume that all tools around are following it.

**Describe the solution you'd like**

Monokle should follow current context from kube config

<img width="1140" alt="Zrzut ekranu 2022-05-20 o 09 35 21" src="https://user-images.githubusercontent.com/30776/169477666-c91f44da-fa4c-4cfd-a05c-2b4cc7b50974.png">

**Comment by devcatalin** [comment]
Duplicate of https://github.com/kubeshop/monokle/issues/1418
