### ISSUE TITLE
Changing clusters keeps loading

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1819]
**Describe the bug**
![2022-05-20 13 34 11](https://user-images.githubusercontent.com/27779735/169500494-4e1542ec-4df1-41ff-99b7-d9fd7220f7ed.gif)

**To Reproduce**
1. Change between two local clusters

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] 1.7.3

**Comment by devcatalin** [comment]
Maybe we should have a maximum timeout for this. @andreiv1992 what do you think?
