### ISSUE TITLE
Analyse my cluster deployed resources with OPA

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#1822]
I love the OPA feature so much! 😍

Would it be possible to have OPA rules in the cluster view so I can debug the issues with my deployed resources? 

[popeye](https://github.com/derailed/popeye) or  [Kubeaudit](https://github.com/Shopify/kubeaudit) currently help me with this. 

This is a `popeye` example 

```sh
$ popeye

SERVICES (13 SCANNED)                                                        💥 0 😱 11 🔊 1 ✅ 1 15٪
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
  · default/hello-world-svc........................................................................😱
    🔊 [POP-1102] Use of target port #8080 for service port TCP::8080. Prefer named port.
    😱 [POP-1109] Only one Pod associated with this endpoint.
  · default/kubernetes.............................................................................✅
  · kube-system/default-http-backend...............................................................😱
    🔊 [POP-1102] Use of target port #8080 for service port TCP:http:80. Prefer named port.
    😱 [POP-1109] Only one Pod associated with this endpoint.
    🔊 [POP-1104] Do you mean it? Type NodePort detected.
  · kube-system/kube-dns...........................................................................🔊
```

Would be cool to have that with Monokle directly

**Comment by olensmar** [comment]
this should already be possible in the latest release!? 

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/1917063/169764160-9663462c-e983-4ede-abe2-efd0e39af53b.png">

**Comment by aabedraba** [comment]
@olensmar great! Thanks for that Ole! I didn't find it.

**Comment by olensmar** [comment]
@julioramosest @chlete perhaps we should figure out why @aabedraba wasn't able to find this - I'm sure others will have the same problem...

**Comment by julioramosest** [comment]
@olensmar @chlete this has to do with choosing the level of disgregation for the error highlighting. @WitoDelnat and myself were considering this when working on the OPA. Options were:
- Have everyhting under a red icon/badge: errors, OPA issues, etc... all under a common "error" icon. User needs to hover to learn about the type. Or:
- Have a different icon for OPA issues and more to come. It gets it all more crowded but gives more info out of the box
What you guys think?

**Comment by julioramosest** [comment]
other idea would be tags. we can work on design options for this

**Comment by olensmar** [comment]
The way I understood @aabedraba was that he had a hard time finding how/where to use OPA in cluster mode - not finding the actual icons/badges!?

**Comment by chlete** [comment]
Hey @aabedraba good to see you here :) would you mind sharing, what made it hard the feature to be found for you?
