### ISSUE TITLE
show resource metadata on hover

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#184]
with the immediate possibility to filter navigator on a resources namespace, annotations, labels, etc.

**Comment by tommywhitehead** [comment]
@olensmar could I get an example of a resource with its metadata to mock up? This should be quick once I have an idea of what info there will be.

**Comment by olensmar** [comment]
@tommywhitehead - sure - the resource metadata we could show in this popup is
- namespace (string)
- annotations (name-value pairs)
- labels (name-value pairs)

there would be a "filter on" action for each - which would add the corresponding value to the resource filter
