### ISSUE TITLE
Having all Monokle Validation methods highlighted in the Validations tab

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#1845]
As a user I would like to see all our Validation methods (already integrated with Monokle) highligthed in the innital space of the Validations tab, modular way, so users are aware of what Monokle is offering validation-wise out of the box. 
- Order of the modules TBD
- Name of the validation method, short description and more info link (if available) required for UI work.

**Comment by olensmar** [comment]
I think the following built-in validation methods could be added:
- YAML Syntax - validates that your manifests have correct YAML syntax. 
- K8s Schema - validates that your manifests have the correct properties/values defined in the schema for their resource kind/version. Configuration option: "K8s Version" (currently under project settings)
- Resource Links - validates that references to other resources are valid. Configuration option: "Ignore optional unsatisfied links" (currently under project settings)

"Read more" links for all of these would initially go to https://kubeshop.github.io/monokle/resource-validation/ - we should perhaps have separate documentation pages for each type of validation!?

**Comment by julioramosest** [comment]
UX ready. Figma file: https://www.figma.com/file/PJDKaMjo95XCMA4Ek8Ttxp/%231539-Integrate-Trivy-into-Monokle?node-id=0%3A1
