### ISSUE TITLE
Showing if OPA validation is active without needing to open the Validations tab

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#1846]
As I user I would like to see if OPA validation is active (and how many rules I have enabled) right away, without needing to open the Validations tab.

**Comment by olensmar** [comment]
duplicate: #1734

**Comment by julioramosest** [comment]
![image](https://user-images.githubusercontent.com/97731654/170984061-52849e3d-a8d4-4ec0-bf1d-5c1254000efe.png)

![image](https://user-images.githubusercontent.com/97731654/170983997-151e5807-3fe7-46ce-9795-5f7546854063.png)


this is UX ready: https://www.figma.com/file/PJDKaMjo95XCMA4Ek8Ttxp/%231539-Validators-tab?node-id=0%3A1
