### ISSUE TITLE
The namespace field in NewResourceWizard should be hidden for cluster-scoped resources

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1870]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/20538711/171157778-e9c590c1-f94a-413f-ae75-d0f79fd87f61.png">

If we're creating cluster-scoped resources (Namspace, ClusterRole, etc.) the namespace field should be hidden.

**Comment by olensmar** [comment]
afaik there is a isNamespaced property on the ResourceKindHandler that can help in determining if the field should be enabled for the selected resource kind
