### ISSUE TITLE
Deploy directly for cluster-scoped resources

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#1871]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/20538711/171158338-af68879a-5521-4062-afd3-9898d5bff8a9.png">

Cluster-scoped resources (the ones that do not have a namespace) should be deployed directly when clicking on "Deploy", the above modal should not appear.

**Comment by olensmar** [comment]
shouldn't we still have a confirmation dialog!?

**Comment by devcatalin** [comment]
Indeed, we should keep having a confirmation modal but hide the namespace related fields

**Comment by topliceanurazvan** [comment]
@olensmar @devcatalin how should we approach the multiple resources deploy if we have some that have the kind namespaced and some that don't?
