### ISSUE TITLE
Deploy fails with different kubeconfig

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1893]
I've configured my project to use a different kubeconfig than the default one and I am able to browser my cluster accordingly - but when I try to deploy changes to one of my resources I get the following error: 

Title: Applying my-postman-collection to cluster gke_testkube-328312_us-east1-c_testkube-workshop failed. Description: error: context "gke_testkube-328312_us-east1-c_testkube-workshop" does not exist

It seems like the deploy is not using my custom kubeconfig but the default one!?

**Comment by WitoDelnat** [comment]
I fixed some minor related bugs in [this PR, ](https://github.com/kubeshop/monokle/pull/1905)but I cannot reproduce your problem.

What I did was create two Minikube clusters with two separate kubeconfigs (default _.kube/config_ and _custom-context.yaml_).  Afterwards I updated the project settings to use the custom one and I tried to deploy both through the button found on the editor and through the compare modal.

Can you please give additional context (pun intended?)?

**Comment by WitoDelnat** [comment]
_from discussion with Ole_

We decided to put this on hold for a bit. It's probably not a major issue since I cannot reproduce.

**Comment by WitoDelnat** [comment]
I think [my fix for multiple resource sets in cluster compare](https://github.com/kubeshop/monokle/pull/1910/commits/9fbb6eb390ac318075dbeb7e734d08c09fd42200) will also fix this.

The bug is very subtle, but before my fix when config is not a string it will ignore the passed context.

```
export function createKubeClient(config: string | AppConfig, context?: string) {
  const kc = new k8s.KubeConfig();
  const path = typeof config === 'string' ? config : config.projectConfig?.kubeConfig?.path || config.kubeConfig.path;
  if (!path) {
    throw new Error('Missing path to kubeconfing');
  }

  kc.loadFromFile(path);
  let currentContext =
    typeof config === 'string'
      ? context
      : config.projectConfig?.kubeConfig?.currentContext || config.kubeConfig.currentContext;
```

Combine that with src/redux/thunks/previewCluster.ts:47 and it likely causes your bug:

```
const kc = createKubeClient(thunkAPI.getState().config, context);
```

**Comment by olensmar** [comment]
nice catch @WitoDelnat 💪

**Comment by WitoDelnat** [comment]
The browse and diff works now. The deploy still fails. No idea why but at this point I'd like to throw out the `kubectl apply` and replace it with the [apply through Kubernetes NodeJs client](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/apply/apply-example.ts).

I think that will be equally much effort, a bit cleaner to use consistent client and it will likely solve this problem as well.

**Comment by devcatalin** [comment]
This is an old issue, can we still reproduce it?
