### ISSUE TITLE
Cluster environments

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#1915]
**Is your feature request related to a problem? Please describe.**
I have multiple clusters in my kubeconfig. Some of them are local and development clusters, but others are production cluster. When I am working within Monokle, I've had multiple times accidentally applied resources that were intended for my dev cluster to my production cluster. Now I'm a bit anxious to use the feature as its not always easy to undo these applies.

**Describe the solution you'd like**
Database management tools allow you to tag a database connection with an environment. I really like TablePlus' solution. You can see [here](https://docs.tableplus.com/gui-tools/manage-connections) how you can give a status color and tag to the connection, and afterwards the the bar becomes that status color. It makes it immediately very clear how cautious I should be. We could do something similar with the cluster selector?

TablePlus also has a [safe mode](https://docs.tableplus.com/gui-tools/code-review-and-safemode/safe-mode). While I think the color will already solve most of my worries it's also worth considering.

**Comment by julioramosest** [comment]
This is UX ready. Find design and workflow logic in this figma file: https://www.figma.com/file/sOd5POCqcXa2BAU2CCHIr2/%231915-Cluster-environments?node-id=0%3A1

![image 2](https://user-images.githubusercontent.com/97731654/177153876-5b61d81b-f1b8-4b6b-8548-182ea72c0b01.png)
