### ISSUE TITLE
Deleting/Appending a resource will not update file content on Monaco editor

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#1934]
If you have a file containing multiple resources selected, when deleting or appending a resource, the content of the file should be updated right away, instead right now you have to reselect the file in order to see the changes. 

## Screenshots

Before deleting `my-role` resource:

![image](https://user-images.githubusercontent.com/47887589/173505358-2df917c4-2f7e-448b-85ef-b5163e1fb6c2.png)

After deleting `my-role` resource:

![image](https://user-images.githubusercontent.com/47887589/173505431-92f2f955-0327-4d44-8bd2-ed48ec39de70.png)

**Comment by devcatalin** [comment]
This should get fixed by the refactor that @jmelnych is doing in the "find and replace" PR, where we will start storing the file's content in a `.text` field which should be updated by the file monitor.
