### ISSUE TITLE
Integrate validation tools

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#194]
Integrate https://github.com/zegl/kube-score with Monokle;
- automatically validate all resources when loading/parsing
- show errors/warnings in a dedicated tab!?

(this might be a good plugin contender?)

**Comment by olensmar** [comment]
@devcatalin @WitoDelnat should we close or rephrase this given the nature of our current validation subsystem?

**Comment by devcatalin** [comment]
Closing this issue. Validation related issues should probably be created in the `monokle-core` repo
