### ISSUE TITLE
Change location of new update notification

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1962]
So far, we get a pop-up telling that a new update is available. As we will be releasing more often, this could be annoying for the user. 
As a user I would like to get hinted if new updates are available in a discreet, yet noticeable way. Suggestion is to add a small circle in the upper right, like in Spotify, to let the user know there is a new update already downloaded. By clicking on it, a suggestion to restart is presented, and if clicked, the action will be executed.

**Comment by julioramosest** [comment]
This is UX ready. Some notes:
- We go with option 4 from this figma file: https://www.figma.com/file/Iy2Buz4xGaByfPmcwIoBcW/%23-1962-silent-middle-updates?node-id=0%3A1
- Some extra info on the middle release (feature oriented) can be added to the notification.
- This is valid only for middle releases. Major ones stay as they are (bottom-right floating dialogue + splash popup etc.)
