### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by chlete** [kubeshop/monokle#1963]
As a user I would like to submit feedback in an easy way. Typically via a form. Suggestion is to incorporate a link "Feedback" which may point to a typeform.com style website, or other suggestions are welcome.

**Comment by julioramosest** [comment]
This is UX ready: https://www.figma.com/file/XaXDGujJSre089Bg6IHA9v/%231707-Header-rework?node-id=0%3A1

Apart from adding the "feedback" element to the three dots menu, please rework the width of the menu when displayed, so there is a bit more space on the right of the labels, as seen on design:

![image 2](https://user-images.githubusercontent.com/97731654/174760363-5c26183d-a214-4af0-b104-736967cc22f2.png)

**Comment by julioramosest** [comment]
@topliceanurazvan this is the widget Wito proposed and I think is the best option: https://feedback.fish/ With the regular plan we should be good to go

**Comment by chlete** [comment]
Form: https://49x902y6r6t.typeform.com/to/vkFBEYYt
