### ISSUE TITLE
Error handling for renaming file to same name

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#1970]
We should not do the renaming if the new name is the same as the current one.

![image](https://user-images.githubusercontent.com/47887589/174631020-765617f7-376a-4ad7-9b35-a5456162f383.png)

![image](https://user-images.githubusercontent.com/47887589/174631236-f0d6ff01-7c53-4d11-b214-c005f197207c.png)

**Comment by topliceanurazvan** [comment]
Hello @AdrianSK75 and thank you for your interest in contributing to Monokle. 🥳 

Your approach seems right, we are already checking for that in `RenameEntityModal` component at line 119, but we want to have the new name case sensitive, and only if the names are exactly the same, throw an error with something like `Name can't be the same as the current one`.

Don't hesitate to ask us if you need any help.

Wishing you good luck!

**Comment by srini51293** [comment]
Hi,
I like to try, can I?
