### ISSUE TITLE
Helm/Kustomize panels should be disabled in cluster view

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1982]
When I load resources from my cluster I expect the Helm / Kustomize panels to be disabled since they don't reflect any content in my cluster - currently I can still see the kustomizations/helm-charts of my last viewed local resources and preview them (which exits cluster mode)

**Comment by devcatalin** [comment]
what about this other issue https://github.com/kubeshop/monokle/issues/1983 ? 

or maybe the ability to quickly compare a chart / kustomization with the cluster resources? 

I'm thinking of the following workflows:

1. Load Cluster Mode
2. Go to Helm pane
3. Hover a values file and see a "Compare" quick action
4. Click on it and then the Compare modal opens up
5. One side would be the cluster resources that were loaded and the other side would be the preview resources

What do you think?

**Comment by olensmar** [comment]
thanks @devcatalin - good point - that's a really nice workflow that would work for both kustomize and helm - i guess we should only remove the "preview" action for kustomizations/helm-charts to avoid my above scenario?

In regard to #1983 - could that be in a separate "Cluster Content" panel? Or should we add info about deployed helm-charts to the helm panel somehow!? @julioramosest what do you think?

**Comment by devcatalin** [comment]
I don't think going with a separate panel will be the right way to go, because we might have other features or panel affected by the Cluster Mode.
Maybe we should look into how we can [inform the user which panels are affected by Cluster Mode](https://github.com/kubeshop/monokle/issues/2023) and then continue with this issue.

**Comment by julioramosest** [comment]
agree with @devcatalin - I proposed something for https://github.com/kubeshop/monokle/issues/2023 (see comment there)

**Comment by chargio** [comment]
Is this already fixed?
