### ISSUE TITLE
Right menu buttons stop working after clicking graphview

### ISSUE THREAD

**Issue by kambydyne** [kubeshop/monokle#200]
**Describe the bug**
When feature flag is enabled, the right menu graph button only works once for enabling the view, then the menu stops responding (events not firing). The logs button can be pressed multiple times with no issue.

**To Reproduce**
1. Enable feature flags for right menu and graphview
2. click on graph button
3. click on it again

**Expected behavior**
Should toggle the right side

**Comment by devcatalin** [comment]
Closing this as we haven't re-enabled the graph view for quite some time.
That will probably need to be re-implemented from scratch.
