### ISSUE TITLE
Highlighting "Choose" option in Compare Anything when content is still not selected

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#2009]
As a user I would like to see more clearly that "choose..." selector when there is still nothing selected in the Compare Anything feature is actually the main CTA to start the process. It needs to look more prominent, as defined in the figma below (both prior to any selection and with anything already selected).

Figma file: https://www.figma.com/file/1ffWvrDGoBQU5F5avlG4f6/%231713-Improving-Diff?node-id=4%3A4901

<img width="1440" alt="New Diff" src="https://user-images.githubusercontent.com/97731654/176188052-af9c36d9-1e39-4e2c-96a2-b497ab6cc493.png">

**Comment by sriniva7** [comment]
You want to make these placeholder too highlighted ?

![placeholderDoubt1](https://user-images.githubusercontent.com/35147480/180214446-a316c2b2-0c1d-48c3-8c17-6165a9520eea.png)
![placeholderDoubt2](https://user-images.githubusercontent.com/35147480/180214470-10588853-85c7-4c62-9f8a-0b896a9bef32.png)

**Comment by julioramosest** [comment]
@sriniva7 the only thing I would change is the text color of the dropdown that is active (can be selected) so it's not perceived as muted/not selectable. So light grey (almost white) for the text that is selectable, medium grey for the one is still not selectable. No change over other stylings (text weight, size, etc.) Thanks!

**Comment by sriniva7** [comment]
@julioramosest kindly check PR and let me know.

**Comment by julioramosest** [comment]
@sriniva7 as I can see, color of 2nd and 3rd level selectors when clickable is still medium grey. They should get the color of the main "choose" option. Thanks! (just to make sure I'm checking them right, you can share a screenshot if that's ok)

**Comment by sriniva7** [comment]
> @sriniva7 as I can see, color of 2nd and 3rd level selectors when clickable is still medium grey. They should get the color of the main "choose" option. Thanks! (just to make sure I'm checking them right, you can share a screenshot if that's ok)

I need to change those selectors color. I will work on them tomorrow ☺️

**Comment by julioramosest** [comment]
@sriniva7 nice! regarding the color of the 1st level "Choose", that was just perfect. Thanks again for your work on Monokle!

**Comment by sriniva7** [comment]
@julioramosest kindly check and let me know
