### ISSUE TITLE
Inform the user that some feature is affected by the "mode" they are in

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2023]
How should we visually "inform" the user that some features are affected by the "mode" they are in?

At the moment we use different colors in the header of the app if we are in Preview or Cluster mode.
But, this doesn't affect all parts of the app.

For example, when I am in cluster mode, the following things are affected:
- Navigator
- Images tab

And the following are not affected:
- Files tab
- Kustomizations tab
- Helm tab
- Templates tab

In the above example, I'm wondering if we should add some border using the same color to the top of the Navigator and to the left/right of the Images tab?

We could also think about similar scenarios for Preview mode.

**Comment by julioramosest** [comment]
I understand the need. My take: The overall bar with color works fine to communicate that sense that you are in a kind of different mode now. Having also individual bars/borders for the top of the navigator and left or right on the images tab would hinder the understanding of it all. The user can say (are these areas ALSO affected or are these areas the ONLY ones affected). A bit confusing visually. So I think in terms of visual element the top bar alone is fine and makes its job.

What I would have is something **inside** those elments that advises of the modified status. A simple text label would make it. Something like "Resources list is affected by Cluster mode" and even adding a text link with "exit mode". That text can ideed go in the cluster mode color. Same for the images tab. Some text on top once you are within the tab.

I can work on design for this.

**Comment by julioramosest** [comment]
UX ready: https://www.figma.com/file/gDuMrycg59hODDqRpcH6Kw/Main-areas-rework?node-id=0%3A1 
<img width="1440" alt="Monokle desktop - cluster mode" src="https://user-images.githubusercontent.com/97731654/176734433-f23b7274-c957-43dd-949c-32c2a0909fa3.png">
<img width="1440" alt="Monokle desktop - cluster mode 2" src="https://user-images.githubusercontent.com/97731654/176734460-240aaea1-a219-46f4-be36-cb61344343db.png">
