### ISSUE TITLE
Improve rendering of name-value pairs in form editor

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#204]
as it can look somewhat odd currently - for example in a config-map:

![image](https://user-images.githubusercontent.com/1917063/128711778-65d0a80f-8f2e-4e53-b79b-47402082835c.png)

**Comment by julioramosest** [comment]
Design for the whole forms layout is provided here: https://www.figma.com/file/jYePBzrgyP3ubZ7VjMDmoL/Improving-forms?node-id=0%3A1
