### ISSUE TITLE
Changing kubeconfig path freezes the application

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#2052]
If you change the kubeconfig path to something not valid and then change it back to the valid path, the application freezes. Looking in dev mode console log, it seems that the `updateProjectConfig` keeps calling infinitely.

![image](https://user-images.githubusercontent.com/47887589/177494790-7685fd22-dafc-4852-bf20-3949ccb8a28b.png)

**Comment by erdkse** [comment]
Can you try this in this branch too? https://github.com/kubeshop/monokle/pull/2033
