### ISSUE TITLE
Cluster selection - on edit items are not vertically aligned

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#2053]
We should align all the items vertically when editing a context

![image](https://user-images.githubusercontent.com/47887589/177497703-ea1ab819-2e0d-4dfa-bb9e-bfa124b7a1eb.png)

**Comment by devcatalin** [comment]
As a note, these should be aligned to the top, not centered vertically

**Comment by szmski** [comment]
Fixed in #2060
