### ISSUE TITLE
Improve visual readability of Navigator pane.

### ISSUE THREAD

**Issue by fog1985** [kubeshop/monokle#208]
When looking into Navigator Pane it's hard to see the difference between main sections like Workloads or Storage and their sub-resources like deployment setc. Everything is white and just difference in small-big phont. Hard to navigate.

**Comment by chargio** [comment]
Working on a new design that will make this more clear in all ways, the new design will be work better to show resources and how they work
Closing this now as it will be covered
@julioramosest for awareness.
