### ISSUE TITLE
Scale & restart actions for Deployments

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2084]
While in Cluster Mode, we should have quick actions for:
- Scaling, which would open a modal to change the number of replicas and it will deploy the change automatically
- Restarting, which would restart the deployment (with a confirmation modal)

**Comment by julioramosest** [comment]
This is UX ready: https://www.figma.com/file/bJkMhjGXWa5NXfmxdIgZyB/Show-age-and-status-in-cluster--mode-%232083-%232084-%232085?node-id=0%3A1
