### ISSUE TITLE
Logs tab for Pods

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2085]
In the Editor view to the right we could have an additional tab for Logs.
We should start by showing the logs from Pod objects and then for other kinds of objects.

**Comment by julioramosest** [comment]
This is UX ready: https://www.figma.com/file/bJkMhjGXWa5NXfmxdIgZyB/Show-age-and-status-in-cluster--mode-%232083-%232084-%232085?node-id=0%3A1
