### ISSUE TITLE
"Rename Resource" refactoring

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#211]
When renaming a resource I would like Monokle to automatically update any incoming references to the resource based on the name - so for example changing the name of a configmap i would like any references to that configmap to be automatically updated. 

This could be via a dedicated "Rename Resource" action in the navigator - with a corresponding hotkey and action in the editor itself

**Comment by olensmar** [comment]
@tommywhitehead any thoughts on this? we would need to prompt the user for a new name - guessing we would do this as discussed for file-explorer actions previously?

**Comment by tommywhitehead** [comment]
I think a right-click menu ([context menu](https://ant.design/components/dropdown/#components-dropdown-demo-context-menu)) would be a good way to access a rename option. Once clicked, maybe a modal window would show with rename options.

I can mock up the modal window, what options are needed? 
- New name
- Optional replace all links?
- What else?
