### ISSUE TITLE
Telemetry modal doesn't render Markdown

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2134]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/20538711/180986787-0e1d34e9-9f78-4407-ab2e-e3d03350f339.png">

The Telemetry modal which can be opened by clicking on the "See more" link in the telemetry notification, doesn't render the markdown.

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle/pull/2140
