### ISSUE TITLE
Plugin Manager

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#216]
Once we have https://github.com/kubeshop/monokle/issues/177 in place we should add a Plugin-manager to the UI where users can:
- search for and add plugins from a central repository 
- add plugins from a local folder
- enable/disable installed plugins
- remove installed plugins
- get notified if updates are available for installed plugins

**Comment by erdkse** [comment]
Can we close this @devcatalin ?

**Comment by olensmar** [comment]
closed since we have an initial plugin-manager in place
