### ISSUE TITLE
Form editors should be disabled in preview mode

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2163]
When I preview a kustomization or a Helm chart I am still able to edit the generated resource in their corresponding Form editors - while the source editor is read-only; guessing the form editors should be read-only also!?

**Comment by topliceanurazvan** [comment]
@olensmar I was wondering, should we disable only the button so you can't see the form editors at all in preview mode? 🤔
 
![image](https://user-images.githubusercontent.com/47887589/182318876-70f80e1f-aa0d-45e8-ab95-11ce2522a6de.png)

**Comment by olensmar** [comment]
hm... the Form editors show additional descriptions/context that might be helpful even in read-only mode so I'm thinking we still show them!? What do you think @julioramosest ?

**Comment by julioramosest** [comment]
@olensmar @topliceanurazvan we can leave them and communicate very easily that content in the form fields is read-only. Enough with taking the text color inside from gray-9 (editable) to gray-6 or gray-5 (non-editable)
