### ISSUE TITLE
Add additional context to the yaml editor

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2168]
**Describe the enhancement you'd like to see**
When navigating through a yaml file for K8s, in many cases there is a need to understand the hierarchy,  and now exactly where you are in the file. Adding the context to the editor can help you edit the yaml file easier

**Additional context**
Some other editor present a breadcrumb so you know exactly where you are (filename -> spec -> template -> spec).
A more visual component that represented the navigation point could also be good (i.e. a vertical line showing where you are in the file so you can identify things at the same level).
That would complement the capability to show / hide hierarchy levels in the current solution

**Comment by olensmar** [comment]
seems similar to https://github.com/kubeshop/monokle/issues/786

**Comment by chargio** [comment]
You are right. Closing it
