### ISSUE TITLE
Empty editor for Helm templates

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2188]
When trying to select a Helm template in the Helm panel this is not shown in the editor (any more) - and I see an error in the console: 

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1917063/183412781-70464382-5b23-4dd6-ba10-1a7ea03febb7.png">

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle/pull/2189
