### ISSUE TITLE
Filter on folder does not apply to kustomizations

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2193]
If I filter on a folder in the File explorer any kustomization outside that folder is still shown in the Kustomize planel - I would expect only the kustomizations in the selected folder to be visible - i.e. filtering to apply to the Kustomize (and Helm) panels also

**Comment by topliceanurazvan** [comment]
I am just thinking here, couldn't this be kind of confusing? 🤔 As you can also filter by name, kind, namespace etc... in the same group of filters, but they don't apply to Kustomization/Helms. Maybe we can think of a way to make this more intuitive and apply the filters also on them. Another idea might be to separate the filters somehow ( resources and then Kustomization/Helm ) and have some that apply to all (some general filters )? @julioramosest what is your thought on that?

**Comment by olensmar** [comment]
hm.. name/kind/namespace don't really apply to kustomizations or helm charts since these aren't really resources/deployable artifacts... my use-case was that I had a project with a lot of kustomize examples (the examples folder of the kustomize repo) and I wanted to see only one of them - perhaps there is some other way to "narrow down" - or we move the file/folder-filters to the file-explorer somehow!? (so they don't confuse with resource-based  filters)

**Comment by topliceanurazvan** [comment]
I totally like the idea of moving the `file/folders` filter in the File explorer section since it would make much more sense to be there. We should give it a try...

**Comment by olensmar** [comment]
thoughts on this @julioramosest ?

**Comment by julioramosest** [comment]
@olensmar @topliceanurazvan I'm perfectly fine with having file-related filtering options in the file pane, looking and behaving the same way in both places. I would also add an open search field. So I would have a dedicated line in top of both listings with an open search box and a filtering icon that opens options below. That's a power combo that boosts the searching/filtering capabilites. I can work on UI for that and show you.

**Comment by topliceanurazvan** [comment]
@julioramosest what do you mean by "looking and behaving the same way in both places" ? we will keep the filtering both in the `File explorer` and in the `Resource filter` ?

**Comment by julioramosest** [comment]
@topliceanurazvan I mean something like this: https://www.figma.com/file/piYTewRAVtQJRQreG6CECh/Filter-for-Resources-and-Files?node-id=0%3A1 - what do you think? pros and cons?

**Comment by olensmar** [comment]
@topliceanurazvan @julioramosest just to go back and solve my initial problem (showing kustomizations that i was expecting to be "filtered away") perhaps we could start this off by greying out kustomizations that are not included in the current file/folder filter?

**Comment by topliceanurazvan** [comment]
Sounds good to me. We could make it disabled with no possibility to interact with it. @julioramosest ?

**Comment by julioramosest** [comment]
@devcatalin @topliceanurazvan greying the element out and having it non-clickable should be enough. You can also consider to use a tooltip to explain that status ("filtered away") but maybe even not needed.
