### ISSUE TITLE
Change "Compare resources" to "Compare & Sync"

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2218]
In places where we might have the labels "Compare resources", "Cluster Compare" or anything similar, we should set the proper name: "Compare & Sync"

**Comment by ADITYADAS1999** [comment]
Hey [devcatalin](https://github.com/devcatalin) this issue is resolve or not ? . If not I interest to work on it 🤠

**Comment by AgniveshChaubey** [comment]
Hey @devcatalin I wanna work on it! Please let me know if it is resolved
