### ISSUE TITLE
Invalid resource ref

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2219]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/20538711/184174570-4344e463-ce9a-4b6f-af82-f4a8b45f3c40.png">

In the picture above I noticed we have an `Incoming link` from the `argo-rollouts-dashboard` Service on line 6, but there isn't any link on that line.

Looking at the other resource, there is actually a link on an annotation:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/20538711/184175055-f0e37f06-a707-4578-adc9-35546e4e4d00.png">

Not sure if this is working properly, probably needs to be revisited.

**Comment by chargio** [comment]
I believe this is related to the fact that inputs and outputs are changed (inputs are outputs and outputs are inputs)

**Comment by chargio** [comment]
Related to #2515
