### ISSUE TITLE
Setting new kubeconfig file don't change available contexts list

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#2230]
**Describe the bug**

When setting up new kubeconfig file in configuration contexts list don't change. 

<img width="776" alt="Zrzut ekranu 2022-08-12 o 07 17 46" src="https://user-images.githubusercontent.com/30776/184289512-c5087222-8bc3-43c7-a73b-70b64224abdf.png">

<img width="1074" alt="Zrzut ekranu 2022-08-12 o 07 18 07" src="https://user-images.githubusercontent.com/30776/184289519-a8c99518-951d-46ca-91ba-a159cb1c2053.png">

In this file there is only one context

**Desktop (please complete the following information):**
 - OS: iOS 
 - Version 1.9.1

**Comment by erdkse** [comment]
It is fixed on version 1.10.0, Now we are getting new release @exu
