### ISSUE TITLE
Restart Monokle don't work

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#2249]
**Describe the bug**

Shen trying to install recent version from notification message 

**Screenshots**

https://user-images.githubusercontent.com/30776/185578297-a0753176-718d-4e71-9e1b-b17da4dd8d4e.mov

**Comment by chargio** [comment]
Exu. Did you manage to make this work? We've launched several fixes and versions so this should not happen anymore

**Comment by chargio** [comment]
Closing issue because it is stalled. We think it is fixed
