### ISSUE TITLE
Generate resources from template

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2250]
**Is your feature request related to a problem? Please describe.**
 When creating a resource currently you have two options: create the resource as it is or create it cloning from an existing resource. However, Monokle have templates that can also be used to speed up creation of resources.

**Describe the solution you'd like**
I would like to have an option in the context menu that shows "use template" added.
The option should show releveant templates (i.e. creating a Deployment should show templates that generate Deployments)

**Describe alternatives you've considered**
Currently you can go to the template itself and generate it from there

**Additional context**

**Comment by devcatalin** [comment]
I'm thinking that this might require to have the "create resource" modal in two steps.
On the first step you would have to choose which type of resource you want to create, set it's name and then have two options to either fill the basic properties as normal, or choose a template.
