### ISSUE TITLE
Monokle freezes when opening specific folders

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2260]
**Describe the bug**
Monokle freezes when trying to open the git clone for helm (helm/helm)

**To Reproduce**
1.  Clone helm helm into a local folder
2. Open Monokle
3. Point it to the local folder with helm
4. See it freeze

**Expected behavior**
It should open the folder without any problem

**Screenshots**
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/7500590/185959057-0dd0d619-eae1-4460-b4c4-3fe686d97116.png">
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/7500590/185959125-e6c23027-080c-4bbc-babc-02f37041d4f8.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.5.1 (M1 Max)
Monokle 1.10.1

**Additional context**
Open Developer tools is not working, the console gets frozen too.

**Comment by olensmar** [comment]
See #2263 - Monokle doesn't lock up - but it still takes a while to render due to rendering performance issues when there are 123 (!) Helm Charts.. waiting for @devcatalin

**Comment by olensmar** [comment]
perhaps https://github.com/kubeshop/monokle/issues/1719 is related?

**Comment by starcraft66** [comment]
This seems to still happen. Opening my infrastructure repo (https://github.com/starcraft66/infrastructure/) causes the app to freeze. I let it run for like 20 minutes and the UI eventually unblocked but it still didn't show anything more than what's visible in the issue's screenshot.

**Comment by starcraft66** [comment]
I think that what is happening is that it is scanning my `.direnv` folder which contains symlinks to huge checkouts of `nixpkgs` and other repositories that are just meaningless noise. Is there a way to make it ignore folders? It finally loaded after a long time and it says it processed 34000 files in my repo when there are only few hundred relevant yaml files.

**Comment by olensmar** [comment]
thanks for getting back to us @starcraft66 - yes, there is a setting for this under the global settings (as shown below) and then under project settings where they can be overridden... perhaps we should add `.direnv` to the default list of excludes?

<img width="1280" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/6d20095f-fafc-4812-86a5-d232db1dcee6">

**Comment by olensmar** [comment]
another thought could be to use any found .gitignore files to further ignore - would that have helped in your case!?

**Comment by starcraft66** [comment]
I attempted to add `.direnv` and `/.direnv` to the list of excluded files after writing my post, but the app still seems to try to process that regardless when I re-open it. The only fix to make things snappy was to temporarily delete the .direnv folder.

**Comment by olensmar** [comment]
Ok - thanks for giving that a try and getting back to us - will have to try to reproduce and get back to you asap

**Comment by olensmar** [comment]
sorry for the delay - bug confirmed - https://github.com/kubeshop/monokle/issues/3943
