### ISSUE TITLE
What to test before a big release so first time use is seamless

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#2264]
As a new user (or a recurring one about to enjoy a new version) I would like to have a seamless experience in the first minutes using Monokle. From version to version we have detected that some of the dialogues and procedures "break", so UX is not optimal. We must set up some testing around first use experience (manual or automatic) that checks out the following aspects - prior to any big release:

**Bottom-right restart dialogue (in the old version)**
- [ ] Make sure the Restart CTA works
- [ ] Inform the user visually that something is happening (spinner...)
- [ ] New version needs to actually launch itself without further user interaction

**Telemetry** 
- [x] seamless, whereas it is accepting or rejecting

**Tooltip guide**
- [ ] We add new ones for new feagures and we deprecate previous version ones
- [ ] New users see the whole bunch (permanent + new)
- [ ] Recurring users see only the new ones

**Order of dialogues**
- [ ] Dialogues and popups happen in the correct order

**OS testing**
- [ ] Test all of this for iOS 
- [ ] Test all of this for Windows

**Comment by chargio** [comment]
Hey. Can we do this as a recurrent element for all versions?
Also, it did not work as expected. What can we do to improve it for next release
