### ISSUE TITLE
Create wrappers around IPC

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2283]
While I was implementing some new logic which required to use multiple ipc calls, I was thinking that we could create wrappers around `ipcMain.on`, `ipcMain.emit`, `ipcRenderer.on` and `ipcRenderer.send` which would have better TS typings for the parameters.

For the event name, I'm thinking we could follow the following naming pattern: `${module}.${method}` and `${module}.${method}.result`

Then we would have types for each mentioned method, for example:

```ts
type MainListenerEvents = 'shell.resize' | 'shell.init' | 'git.cloneRepo';
type MainSenderEvents = 'git.cloneRepo.result';
```

Using those types in wrappers would help us to not make mistakes when writing the event names and it will add auto-complete support.

Furthermore, we could have methods to help us "await" the events, for example:

```ts
export function promiseFromIpcMain<Payload = any>(
  sender: string,
  receiver: string,
  senderPayload?: any
): Promise<Payload> {
  return new Promise(resolve => {
    ipcMain.once(receiver, (event, receiverPayload) => {
      resolve(receiverPayload);
    });
    ipcMain.emit(sender, senderPayload);
  });
}
```

which could be used like this:

```ts

promiseFromIpcMain('git.cloneGitRepo', 'git.cloneGitRepo.result', {/* args */}).then(() => { /* do something */ });

```

**Comment by olensmar** [comment]
I think the updated electron documentation suggests something similar - https://www.electronjs.org/docs/latest/tutorial/ipc
