### ISSUE TITLE
Clear command in terminal doesn't clear history

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2289]
When I run the `clear` command in the Terminal, the content that I currently see in the view gets cleared, but I can still scroll and see that content. I'm thinking that right now it just adds a few new lines and scrolls to the bottom?

**Comment by erdkse** [comment]
This is the default terminal behaviour, no?

**Comment by olensmar** [comment]
I thought so too!?

**Comment by devcatalin** [comment]
you guys are right, my bad! closing this 😅
