### ISSUE TITLE
[git#1] Search & checkout remote branches

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2294]
At the moment, in the Branch Select dropdown we only show the local branches, but we already have access to list the remote branches.

We should allow users to search for remote branches and checkout them locally. This should probably be in a separate dropdown or a modal which needs to be designed.

**Comment by julioramosest** [comment]
UI for this: https://www.figma.com/file/ysPkVjIsd1JA4cttEWcVJM/Git-for-Desktop?node-id=1%3A700
