### ISSUE TITLE
[git#5] Initial logic for pushing commits to remote branch

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2299]
For an initial implementation we should aim to do this for simple cases where the push works without receiving any merging errors.

If there are merging errors, then we should catch the errors and show them to the user.
After that, the user would have to use the Terminal or other tools to fix the conflicts.

We need a place to enter the URL of the remote git repository if it's not already set (could be set externally via the terminal using Git commands).

**Comment by julioramosest** [comment]
find design here: https://www.figma.com/file/ysPkVjIsd1JA4cttEWcVJM/Git-for-Desktop?node-id=100%3A726
