### ISSUE TITLE
[git#6] Create new local branch

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2354]
I would like to be able to create a new Git local branch

This option could appear in the Branch Select dropdown:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/20538711/191006739-8965c848-b3a0-49c9-a0f8-90893fd13fae.png">

Clicking on the button would probably open a modal with an input for the name of the branch.
We also need design for showing errors in that modal, in case there is already a branch with the same name.

**Comment by julioramosest** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/97731654/191222262-c0e6450d-eedb-4cb7-8ec5-e261c7339e6c.png">

Let's have it like this, an icon + text link at the bottom of the list.
