### ISSUE TITLE
Opening a subfolder of a git repo in Monokle

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#2357]
We should handle the case where we open a folder as a project that is a subfolder/subdirectory of a git repo. 

Showing the absolute path of the files changed but not contained in the current project could be a solution ( similar to the screenshot below ).

![image](https://user-images.githubusercontent.com/47887589/191043866-12167d94-dce6-48e9-974f-6d14c00c8e29.png)

**Comment by devcatalin** [comment]
We should also add the 3 states from the right: Deleted / Untracked & Modified

**Comment by julioramosest** [comment]
design for 3 statuses: https://www.figma.com/file/ysPkVjIsd1JA4cttEWcVJM/Git-for-Desktop?node-id=0%3A1

<img width="1440" alt="three statuses" src="https://user-images.githubusercontent.com/97731654/191247872-d07b381a-c221-41a5-b4b7-e95fa4a85230.png">

**Comment by julioramosest** [comment]
also, as commented around the paths - we avoid repearting the name of the file in the paths. We only show the path itself.
