### ISSUE TITLE
Diff all resources against selected cluster

### ISSUE THREAD

**Issue by catalinhoha** [kubeshop/monokle#236]
**Describe the enhancement you'd like to see**
It would be nice to have a `Diff` button in the Navigator's title bar which would open a Modal containing two navigator-like panels.
Using those panels, we should easily see the differences across all resources from the folder and cluster.

**Comment by olensmar** [comment]
nice - i'm thinking you could use this to both diff your local/preview manifests against a cluster - and also to diff two clusters against each-other!?

**Comment by catalinhoha** [comment]
That would be really cool!

**Comment by olensmar** [comment]
How about the following:
- left cluster tab shows a separate navigator for all cluster resources (similar to the file explorer showing files)
- the middle navigator shows "local" resources as today (with kustomize/helm previews)
- selecting a cluster resource to the left highlights the corresponding local resource in the middle and vice-versa
- a "sync filter" shows in cluster resources that also exist in the middle navigator

**Comment by tommywhitehead** [comment]
Here's the next mockup (v3) for this idea:
https://www.figma.com/file/zvPjzhHgqZtYrzXqB9m02m/236-Diff-all-resources-against-selected-cluster?node-id=18%3A2218
<img width="1440" alt="#236  Diff all resources against selected cluster 3" src="https://user-images.githubusercontent.com/4236167/135539655-183a9a97-1c34-4ac3-9dd2-11778fd89be8.png">
