### ISSUE TITLE
Fix extraction of some Helm templates

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#2381]
**Describe the bug**
Helm templates are shown in Resource Navigator.

So for instance the ConfigMap.yaml template is not shown, but the Role.yaml template is shown. This seems unintentional behavior. It's likely because the Role does not contain Helm syntax.

**To Reproduce**

1. Clone kubeshop/helm-charts
2. Open the repository
3. Validate that you see what is in the image

**Expected behavior**
It should not parse Helm templates.

**Screenshots**

<img width="1140" alt="Screenshot 2022-09-22 at 12 28 02" src="https://user-images.githubusercontent.com/7761005/191723977-b9872b30-371e-401a-b60e-ee7a7d84be8a.png">

**Comment by chargio** [comment]
It should identify the template and ask for previsualization

**Comment by olensmar** [comment]
@WitoDelnat this works better now - see screenshot below - ok to close? 



![Image](https://github.com/kubeshop/monokle/assets/1917063/6407de5c-be7b-4265-9a1c-11937a316c91)

**Comment by WitoDelnat** [comment]
Awesome! Closing the issue
