### ISSUE TITLE
Improve unsatisfied links popup content

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2389]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/20538711/191785772-702b037e-3fdf-40a5-87f6-ce125cd39f50.png">

Right now, when we hover an unsatisfied link in the editor, we see two things:
- Quick action to create the resource with that name
- The definition from the schema

We should add a message at the top that explains what the yellow highlight is, something like "This is an unsatisfied link. We couldn't find any resources of kind X with the name X."

**Comment by ADITYADAS1999** [comment]
this issue is still open, can i work with it ?

**Comment by ADITYADAS1999** [comment]
@devcatalin please assign me in the issue

**Comment by topliceanurazvan** [comment]
Hey @ADITYADAS1999 , how is it going with the issue? Anything that we can help with?

**Comment by ADITYADAS1999** [comment]
> Hey @ADITYADAS1999 , how is it going with the issue? Anything that we can help with?

sry for late reply, I working with some hacktoberfest issue.

I already download all the dependencies and packages still  I  stuck to run the code in my local system.  Are free to  discuss on discord to solve this issue ?

**Comment by topliceanurazvan** [comment]
Sure. You can write in our discord channel and we’ll be glad to help you.

**Comment by ADITYADAS1999** [comment]
> Sure. You can write in our discord channel and we’ll be glad to help you.

thanks @topliceanurazvan

**Comment by devcatalin** [comment]
This is now handled by the monokle core validation package
