### ISSUE TITLE
Improve resource-save mechanics

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#243]
We currently require users to save changes explicitly to a resource before they leave the corresponding editor - we should improve this:
- update resource.text/content on each debounced change in editors, with corresponding recalculations of links
- add an isDirty flag to K8Resource
- show if a resource is dirty in navigator
- add a save-all action somewhere - to save all dirty resources

**Comment by olensmar** [comment]
@tommywhitehead I think we need two things from you:
- how mark dirty resources/files in navigators
- where have a "Save all" action

**Comment by catalinhoha** [comment]
There are two other issues related to this one:
https://github.com/kubeshop/monokle/issues/180
https://github.com/kubeshop/monokle/issues/213
