### ISSUE TITLE
Remove file/folder filters when loading a new project 

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2437]
When loading a new project the current file/folder filters are kept from the previous project - which can result in the old filters selecting folders that do not exist in the current project - which in turn results in the filter button getting disabled since there are no resources to filter on - which in turn makes it impossible to remove the filter :D 

Suggest to automatically reset all filters when loading a new project!?

Below I first opened the argo-rollouts project and filtered on the manifests folder - then I switched to this project which doesn't contain such a folder - now no resources are shown (because of the filter) - and the filter button is disabled..

<img width="1773" alt="image" src="https://user-images.githubusercontent.com/1917063/193018280-68a70301-dbef-49c4-a717-0ea7a1727766.png">

**Comment by olensmar** [comment]
also - perhaps we should always have the filter button enabled? even if there is nothing to filter on?

**Comment by devcatalin** [comment]
Fixed in https://github.com/kubeshop/monokle/pull/2438
