### ISSUE TITLE
CI: Replace Husky with a workflow build for running tests.

### ISSUE THREAD

**Issue by kambydyne** [kubeshop/monokle#244]
Pre-commit hooks are proving slow. Let's move the tests and sanitation to CI.

**Comment by olensmar** [comment]
i think we should keep pre-commit hooks for linting/formatting - to avoid pure formatting related changes!?

**Comment by kambydyne** [comment]
> i think we should keep pre-commit hooks for linting/formatting - to avoid pure formatting related changes!?

Cant we just use Prettier all of us? So it formats on file-save?

**Comment by olensmar** [comment]
we can - but external contributors might not.. i'd prefer to be explicit about this one - formatting doesn't take any time afaik

**Comment by kambydyne** [comment]
> we can - but external contributors might not.. i'd prefer to be explicit about this one - formatting doesn't take any time afaik

Good point. I'll leave the linter in!

**Comment by kambydyne** [comment]
Resolved
