### ISSUE TITLE
Enhancements to the git clone functionality

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2491]
As a user, when I am cloning a repo, I would prefer to have some improvements to the experience:

1. When selecting the repository URL, I need to copy and paste the full repo. The current placeholder states ("https://github.com/kuebshop/monokle"), but I am expecting to be able to do things like in the SaaS.
- Full address using http
- git clone with a git address git@github.com:kubeshop/monokle.git
- search using git address (kubeshop/monokle). SaaS works this way, showing the repo and cloning it

When selecting the location, I expect Monokle to clone the repo into the base folder I use for my code, but the dialog complains that the folder is not empty. I expect it not to be empty (i.e. ~/workspace or ~/work/Configurations/), and this confuses me. Should I use an empty folder? Will the code be cloned into a folder inside the empty folder or will the files be cloned directly into the empty folder?

<img width="522" alt="image" src="https://user-images.githubusercontent.com/7500590/194097715-5f194320-8327-43ba-a12c-612609dea693.png">

When trying to clone, if the end repo is going to be overwritten (i.e. the folder where it is going to be cloned is helm-repo and that folder already exists), the message we show today makes sense, but the text should be updated from
"Folder contains files! Please provide a path to empty folder". The Location should be updated with the actual final result (i.e git clone <repo> <folder> where folder is prepulated with prefix + repo name

**Comment by chargio** [comment]
If you create the folder manually, it will clone into it, so I understand that we are doing git clone <repo> <folder>, that is something good, but I was expecting the result of git clone <repo> as it is not telling me otherwise

**Comment by devcatalin** [comment]
This is somewhat related to https://github.com/kubeshop/monokle/issues/2459
