### ISSUE TITLE
Monokle should be able to open files by default that are not binary (and support markdown)

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2498]
**Describe the bug**
I can't open Dockerfile or LICENSE or nay other file wihout amn extension
When I am opening markdown files, I can't see the results of markdown, so I can't work with documentation

**To Reproduce**

**Expected behavior**
I would expect any file to be suitable to be open, even if we don't use context highlighting for them.
I also expect github markdown to be used and recognized

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by devcatalin** [comment]
We need to have a list of file names that should be supported to be opened without having an extension.

So far I think we should enable editing for:
- Dockerfile
- LICENSE
- .gitignore
- .monokle

What other file names should we add to the list?

**Comment by cerebro1** [comment]
Probably files with .md extension also because most of the projects use markdown format to store documentation. It would be then an all in one solution to manage a project along with it's documentation and without losing the focus that Monokle is a kubernetes manifest management environment.

**Comment by chargio** [comment]
As a user, I want to be able to open any text file in Monokle, even if highlighting is not enabled.

Currently, it is not possible to open some files that are text, like .gitignore or LICENSE or .helmignore database.env

It is preferable to open binary files than not allowing the user to open text files that they can modify. In those cases where the configuration is stored in a file that is not recognized, you can't edit it, and the user needs to go into the terminal or other tools to use it


I will add support for context highlighting for other types in another issue

**Comment by cerebro1** [comment]
> 

Yeah makes perfect sense. 
Whenever you guys fix this, make sure to mention the PR link in the issue. It helps to get brief overview of how the issue was fixed or what actions were taken. Just a suggestion. 
Thanks!
