### ISSUE TITLE
editor decoration wrong after preview

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2524]
I have a kustomization that has a reference to a file - correctly decorated:

<img width="1622" alt="image" src="https://user-images.githubusercontent.com/1917063/194817860-6050fa37-9b46-440e-b6ec-15bce66b8d7d.png">

but when I preview the kustomization with the preview link in the file explorer (shown above) - the first 2 comment lines in the file are removed and the decoration "moves down" two lines:

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/1917063/194817966-31d2ddc0-f098-4f29-8a32-1dfd7940c59b.png">

**Comment by topliceanurazvan** [comment]
After investigating a little bit, it looks like this happens because the first comment is deleted in preview mode from the editor ( not sure if it's deleted from the content because it reappears when you exit preview and select the kustomization again ).
