### ISSUE TITLE
Git: possibility to revert changes to latest branch version

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2525]
I'd like to be able to revert my changes to the latest branch version - for example in this popup:

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/1917063/194840987-05c0b1a8-901a-45d9-b6c5-22f071a3c77b.png">

**Comment by chargio** [comment]
You can do a checkout of the file (so it becomes the version in the last commit), or a stash (that you can recover later)... I would definitely add the first one, and then keep the other as a new issue part of conflict resolution

**Comment by olensmar** [comment]
this is just when I've made some changes locally during testing/debugging that I don't want to commit to git - it's a common 
maybe the word "revert" is misleading - as it is not the same as a "git revert" - perhaps "discard changes" is better (VS Code)? or "rollback" (Intellij) ?
