### ISSUE TITLE
Notifications panel does not have a close button

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2569]
**Describe the bug**
Opening the notifications panel does not show a button to close it

**To Reproduce**

**Expected behavior**
An x to close the panel is present

**Screenshots**
<img width="462" alt="image" src="https://user-images.githubusercontent.com/7500590/195621584-6aba0c2f-a328-4a5d-9dae-e5603afa8f46.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by topliceanurazvan** [comment]
This is a drawer similar to the settings one. You have to click on outside of it to close it. 

Should we add a close button for both drawers? @julioramosest

**Comment by julioramosest** [comment]
@chargio @topliceanurazvan yes, let's add an "x" to both drawers. Clicking out still fine, but the X is missed.
