### ISSUE TITLE
Walkthrough tooltips deprecated

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#2618]
Currently, we are still showing the `Compare anything` and `View images` tooltips. We should update them accordingly to our latest release ( with Git, Preview commands, etc... ).

Also the `View images` appears 2 times ( tested on Windows 10 ):

![image](https://user-images.githubusercontent.com/47887589/197465113-656c3b51-406f-4eea-a2b6-fe5cb722e11d.png)

**Comment by chargio** [comment]
1. Find the list of tooltips
2. Fix the duplicated ones
3. Add tooltips for cluster mode

**Comment by chargio** [comment]
Fix for duplicated ones is done
