### ISSUE TITLE
Add OPA active rules count and k8s schema version to the header

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2620]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/20538711/197533427-f110e0bc-11c8-4d8b-a253-729a0a9a4230.png">

**Comment by julioramosest** [comment]
find additional design for this here: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=749%3A4130&t=ACDAhNyvlu45fOvK-1
