### ISSUE TITLE
Tutorial page

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2621]
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/20538711/197533776-886530f2-ba19-460b-a453-1b2f1911e224.png">

**Comment by devcatalin** [comment]
We're thinking this should show up once per project, when you create a new one (from folder, git, scratch, template).
@julioramosest what do you think?

**Comment by julioramosest** [comment]
@devcatalin let's discuss that on the UX meeting - not sure if that could get a bit tiresome each time - It may be something that the user can configure. But still not sure about it, let's discuss

**Comment by julioramosest** [comment]
because for those blue buttons it was intended that they trigger not only opening the project in a certain way, but also launch some quick guide tooltips, and in that case of doing it for each project, that would be too much

**Comment by chargio** [comment]
UI part is done.
The funcationality part is still ongoing. Paused to after templates
