### ISSUE TITLE
New Validation tab

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2623]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/20538711/197534049-a63c5e08-e695-4bd0-8dcb-c8028e0429c2.png">

We will replace the current Validation panel with the new design from the image.

This panel should show all errors (OPA, schema validation) per file.

**Comment by devcatalin** [comment]
I think this panel will be more useful if it allows us to actually edit the files/resources in order to fix the errors.

What happens when you have an error selected and you just fixed it?

**Comment by chargio** [comment]
Trying to find the way to show validation levels

**Comment by chargio** [comment]
Pending on some refactoring being done before

**Comment by chargio** [comment]
@WitoDelnat @DzoQiEuoi We are building this in the core packet. We have an ETA of end of week, so we will be able to integrate it in the Cloud next week

**Comment by chargio** [comment]
Still missing the editor on the right

**Comment by chargio** [comment]
@WitoDelnat @DzoQiEuoi the PR has been merged in desktop
