### ISSUE TITLE
Refactor Explore page

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2626]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/20538711/197726702-97a4ef6e-041f-4fdd-a9e0-22e63afe7496.png">

Combine the 4 panels we have now: Files, Helm Charts, Kustomizations, Images into a single Explorer page that has all inventories as an accordion.

**Comment by chargio** [comment]
Thomas was always working on this.

**Comment by chargio** [comment]
Data structures are different, so we will need some implememtation work

**Comment by devcatalin** [comment]
Closing this in favor of [#3071](https://github.com/kubeshop/monokle/issues/3071)
