### ISSUE TITLE
Create new TitleBar component

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2627]
We should have a reusable `TitleBar` component that follows the following designs:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/20538711/197728618-be803ada-36aa-4365-abea-73c87422e79e.png">

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/20538711/197728692-48f73cd1-3c46-49bb-ac81-0b756ca3baca.png">

<img width="680" alt="image" src="https://user-images.githubusercontent.com/20538711/197728749-a4dcfe99-4a08-4e5d-8c69-209ad81aa2e4.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/20538711/197728836-c4db2826-bef6-455d-ac5c-4a6195cc78fd.png">

**Comment by olensmar** [comment]
Will this be reusable in Monokle Cloud also?

**Comment by devcatalin** [comment]
sure, we can create it in `monokle-core`

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle-core/pull/38 - created in `monokle-core` and used successfully already in 2.0 refactor
