### ISSUE TITLE
Redesign left menu and logo

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2628]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/20538711/197729222-e3e290c7-0b7c-477c-a1e9-4bf25df2fea8.png">

The left menu should be redesigned with the new icons. It should also show the white circle with double arrows for collapsing the panel.

Lastly, the logo now shows only the icon, without text.

**Comment by topliceanurazvan** [comment]
The new left menu was implemented in `monokle-core` as ActivityBar and integrated into 2.0 refactor - https://github.com/kubeshop/monokle-core/tree/main/packages/components/src/molecules/ActivityBar
