### ISSUE TITLE
Helm Enhancements

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#263]
The initial Helm support is nice but also somewhat limited; suggest the following improvements:
- Show the Chart.yaml file in the Navigator, with some metadata (apiVersion?)
- Source/Form editors for the Chart.yaml file
- Support for template files/syntax in source editor
- Validate references to values in templates
- Somehow separate templates in the Navigator from regular resources - today it's confusing to see them side-by-side

**Comment by olensmar** [comment]
see https://github.com/kubeshop/monokle/issues/1003 for issues we need to support by implementing this

**Comment by devcatalin** [comment]
I suggest we add templates and charts to the Helm pane instead of the navigator, that would allow editing/creating templates while in preview mode. We could also have an "auto-reload" settings for the preview of a chart.

**Comment by olensmar** [comment]
thanks @devcatalin - see also #590

**Comment by olensmar** [comment]
for the go-template syntax highlighting perhaps we can be inspired by https://github.com/jinliming2/vscode-go-template ?
