### ISSUE TITLE
Opening sub-folder of git-enabled project 

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2641]
When opening a sub-folder of a git-enabled project in my file system Monokle does not detect that the folder is already under git control - resulting in corresponding actions not being available - we should either detect this and enable corresponding actions or disable them with some kind of message - perhaps "This folder is under git control for the parent folder ... Open that folder instead to enable git functionality?"

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle/pull/2642
