### ISSUE TITLE
Implementing missing OpenShift schemas

### ISSUE THREAD

**Issue by natlibfi-jonollil** [kubeshop/monokle#2651]
BuildConfig, DeploymentConfig, ImageStream and Route schemas are rated as "Unknown Resources".

BuildConfig: https://docs.openshift.com/container-platform/4.11/cicd/builds/understanding-buildconfigs.html
DeploymentConfig: https://docs.openshift.com/container-platform/4.11/applications/deployments/what-deployments-are.html
ImageStream: https://docs.openshift.com/container-platform/4.11/openshift_images/image-streams-manage.html
Route: https://docs.openshift.com/container-platform/4.11/networking/routes/route-configuration.html

**Comment by olensmar** [comment]
I've found the Route CRD at https://github.com/openshift/api/blob/master/route/v1/route.crd.yaml - if you download that and add it to the CRDs as described in the docs you should be good to go..

will continue looking for the others...

**Comment by natlibfi-jonollil** [comment]
I tried to find missing ones too. No luck here

**Comment by olensmar** [comment]
thanks @natlibfi-jonollil - i got some insights into this on the Kubernetes Slack #openshift-users channel - please check out the conversation at https://kubernetes.slack.com/archives/C6AD6JM17/p1667378584550939

**Comment by natlibfi-jonollil** [comment]
I don't have account to join there. It is invite only slack group.

**Comment by olensmar** [comment]
anyone can join - go to http://slack.kubernetes.io to get an invite
