### ISSUE TITLE
Browse Cluster from Start-screen

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2656]
I would like to be able to browse a cluster directly from the start screen - without having to select/create a project first.. In this mode I could either select another cluster - or exit Cluster mode, which would take me back to the start screen

**Comment by julioramosest** [comment]
Find design here (ongoing): https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=0%3A1
