### ISSUE TITLE
Improve handling of failed cluster connections

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2658]
See below - when trying to connect to GKE I get an error related to my local setup - but Monokle doesn't seem to handle/notice this and gets stuck in a "connecting..." mode 

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/1917063/199919139-874047ec-4bfb-4845-a754-fcf2cbe645b1.png">

**Comment by chargio** [comment]
It seems that we caught every error in code 
@olensmar Can you provide more information about how to reproduce the error?

**Comment by olensmar** [comment]
I had an old gcloud client - after I upgraded the error went away - so I guess you would have to install an older version of gcloud (perhaps the error message can help you understand which one..) to reproduce!?
