### ISSUE TITLE
Reload cluster filter aware

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#2659]
**Describe the enhancement you'd like to see**

When doing cluster related debugging I would love to see that reload will be aware of currently applied filters.  
For now, refreshing in the busy cluster is just a "no-go" for me as I would prefer to speed up getting feedback about what's changed in the cluster.

**Additional context**

https://user-images.githubusercontent.com/30776/199983167-68a9a757-8c2c-4e49-9693-cd36d5138b35.mov

**Comment by chargio** [comment]
Hey. We added a PR that should fix the problem you were having. It will be available in the next version of the tools
