### ISSUE TITLE
Broken git behaviour if authentication is needed

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2667]
If I need to authenticate with GitHub it seems this prompt is ignored by Monokle - resulting in broken git behavior... for example the below project should detect that I already have a git repo configured for this folder - but the prompt to sign in is ignored by Monokle:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1917063/200799768-dfea6652-ae4d-4918-8334-f70fd2c56591.png">

<img width="887" alt="image" src="https://user-images.githubusercontent.com/1917063/200799793-5c8a5756-9f2e-41be-9308-3a92380b4817.png">

**Comment by olensmar** [comment]
Easy workaround is to authenticate from the command-line or using something like https://github.com/GitCredentialManager/git-credential-manager before running Monokle

**Comment by chargio** [comment]
Need additional investigation
