### ISSUE TITLE
New header design for editor and resources

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2683]

**Comment by chargio** [comment]
Hey @mortada-codes I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/monokle-620a8eb717b2fa0010645831/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by chargio** [comment]
@julioramosest Please link the designs here

**Comment by julioramosest** [comment]
Find design for the new editor here: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=939%3A9720&t=vQiO3Hmzx1gquGYW-1 Have in mind release of this needs to be in sync with the release of the new project selection and settings UI
