### ISSUE TITLE
Create a dedicated panel for cluster management

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2716]

**Comment by julioramosest** [comment]
design: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=8%3A348

**Comment by julioramosest** [comment]
I'm fine with that @olensmar but check our the pods listing for example here: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=61%3A126&t=d0Unlf8btPCDXUbd-1 - Our listing contains the full list of resources below every title type in the same column all together, so what we would show  on the right when user clicks on a particular resource already in the list? What Rancher, Lens and others do is listing the type of cluster resource in the left and then the particular resources in a table on the right, with all the data for each.

**Comment by olensmar** [comment]
ok - let's stay your course 👍
