### ISSUE TITLE
Handle custom CRDs in real-time updates

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2736]
The current real-time update handling from a connected cluster is fantastic - I would like this to extend to support custom CRDs also:
- For each CRD we find in a cluster we need to listen for corresponding objects created/deleted
- When a new CRD gets added we need to 
   -  create a corresponding section in the navigator (we probably already do that)
   -  add an event listener for that kind of object so that we can detect new objects and show them in the navigator
- When an existing CRD gets removed we need to
   -  remove that section from the navigator
   - remove the corresponding event listener

For example:
- Browse a cluster without Cert-manager installed
  - Monokle shows all resources in that cluster
- Install Cert-manager
  - Monokle should detect the CRDs installed by Cert-manager (Issuer, etc) and add corresponding sections/listeners
- Create some objects for Cert-manager
  - Monokle should automatically add these to the navigator
- Uninstall Cert-manager (including its CRDs)
  - Monokle should  automatically remove those sections and listeners

**Comment by olensmar** [comment]
@chargio @julioramosest not sure how this relates to the upcoming Cluster panel - do we show CRDs and their corresponding objects there also?

**Comment by chargio** [comment]
Yes, we should show CRD, any extension of the object type needs to be shown

**Comment by julioramosest** [comment]
confluence: https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/697991196/CRD+management
