### ISSUE TITLE
Changes in editor makes all decorations dissapear

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#2738]
When doing some changes to a file, all the decorations just disappear.

Before:

![image](https://user-images.githubusercontent.com/47887589/202170653-baaf4ec0-77b2-4edf-9759-74e59f982f72.png)

After changes:

![image](https://user-images.githubusercontent.com/47887589/202170717-fb5ef023-ff2d-482c-86b5-0b7cd31f65c3.png)

**Comment by chargio** [comment]
See if some of the fixes that Wito is adding will also impact this (bigger refactoring)
