### ISSUE TITLE
Speed up resource processing using RTK listeners

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2741]
If we process resources a lot of times, Monokle starts to lag because the processing is done synchronously and there's no way to abort.
We could try using RTK listeners to make processing asynchronous and to be able to abort if a new processing is triggered.
The only thing we need to be mindful of is that we actually want processing to finish at some point even if it keeps being re-triggered. Maybe we could use a debounce for that.

**Comment by chargio** [comment]
We need this for live CRD management

**Comment by chargio** [comment]
Workaround  that could be possible in 1.13
