### ISSUE TITLE
Disable Deploy action in cluster mode

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#2753]
See below - when in cluster mode I don't think it makes sense to show the "Deploy" action for resources (since they are already deployed)!? Perhaps disable this action until one has made changes in the YAML - and then name the action "Update" ? (same would go for the button on top - which is correctly disabled)

wdyt @julioramosest ?

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/1917063/202416576-59968fc6-9d49-4e60-8144-c2030337f899.png">

**Comment by julioramosest** [comment]
@olensmar I'm fine with that. so the button on top is not disabled in your screenshot, that's just it's secondary (I pushed to have actions there one as primary and the rest as secondary, it's bad UI  when all of them are the same level), see here how they are in fact disabled:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/97731654/202435110-87883b7b-c104-448e-9622-8fb874bcdabb.png">
So yes, we need to have deploy disabled in both the right-click menu and on top, and change it to update once some change is made. Update label is ok? User will understand that that would save the change up there in the cluster? Or would deploy still work? idk, maybe update is just ok.
