### ISSUE TITLE
Implement the design of the new Audit Panel

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2755]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/20538711/202437274-e8b95d2e-efe5-402c-a25c-f9737d37975d.png">

Design can be found in the 2.0 figma file:
https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=0%3A1&t=UINHJ2z1sWf5eq0m-0

**Comment by chargio** [comment]
Duplicate
