### ISSUE TITLE
Copy cluster configuration to local project or branch

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2759]

**Comment by olensmar** [comment]
I think this is possible by selecting all/desired resources in cluster mode and using the "save to file/folder" action... or where you thinking of something else?

**Comment by chargio** [comment]
I was thinking on the case where there is no local project. It should be easy to do, and the CTA can be used in other situations.

- Create project from cluster (local copy of all configuration). Select namespaces
- Create copy of cluster into existing  project and commit to a new branch. Select namespaces to copy

Acknowledging that the use case is important enough to have its own workflow
