### ISSUE TITLE
The number of resources is higher than the actual number of resources in the comparison pane

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2774]
Currently we show the different options for comparison in the left and right pane, meaning:
- Some resources are listed more than once (to enable specific comparisons)
- Some resources are listed even if they don't exist in the configuration to enable the comparison

<img width="518" alt="image" src="https://user-images.githubusercontent.com/7500590/203078393-939a3001-23ac-41bd-95ca-a29f9c62d765.png">

In the image, there are actually no HelmChart, so the number should be 0 and not 2 (there are two resources in the cluster, but not on the config)

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle/pull/2791
