### ISSUE TITLE
Improve readability of notification after multi-deploy

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2778]
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/20538711/203141775-fb6c957f-43a4-435e-8efe-89d9080ab3a9.png">

I deployed 5 resources to the cluster using the multi-select actions and I feel like the output from the notification is not very readable..

**Comment by devcatalin** [comment]
We could start by just adding new lines after each deploy result. Notifications support markdown no I'm guessing it shouldn't be difficult

**Comment by raunak111** [comment]
Hi @devcatalin can you assign me this issue

**Comment by topliceanurazvan** [comment]
Hello @raunak111, thank you for your interest in contributing to Monokle. I will assign you the issue.
If you have any questions or need help just let us know.
