### ISSUE TITLE
File explorer sort folders first

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2782]
I just noticed a difference between our File Explorer and the one in VSCode.
It looks like we're sorting the files & folders alphabetically together, while VSCode shows the folders first and then the files.

Should we apply a similar sorting like VSCode does?

**Comment by devcatalin** [comment]
Let's add this as a setting and use the default the same as in VSCode

**Comment by devcatalin** [comment]
<img width="989" alt="image" src="https://user-images.githubusercontent.com/20538711/203288789-ce6bf3b4-7015-4c49-af0e-a10e776edbb3.png">

**Comment by chargio** [comment]
@WitoDelnat
