### ISSUE TITLE
Compare subdirectories

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2792]
Some customers will have different folders for different environments.

As a user, I want to compare the content and resources defined in one folder with those defined in another folder.

**Comment by bygui86** [comment]
this feature would be extremely useful when the folder structure is quite complex and when different repos are used instead of kustomize overlays

**Comment by topliceanurazvan** [comment]
Hey @bygui86, this feature was implemented and you can try it using our nightly build ( https://github.com/kubeshop/monokle/releases/tag/v1.12.1-nightly-2022-11-28.0 ) until we officially release the next version that will include it.

Please let us know if everything works as you expect it to.
