### ISSUE TITLE
Cluster mode UX review

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2826]
- [x] Rename code in details to "Manifest"
- [ ] Implement index nagigation (< > buttons)
- [x] navigate from error popup directly to code editor
- [x] add "Deploy" button to code editor
- [x] Add storage to cluster info [CPU / Memory / Node attached storage]
- [x] Delete performance box in the dsahboard
- [x] Add API version to Status (kubernetes version) (check out Julio comment below) +  # CRD installed instead of performance
```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.3+k3s1
```
- [x] Change icon of cluster mode to a Kubernetes cluster icon
- [x] Activity "pause" button does not work. Hide it
- [x] Yellow icon does not follow up, there is no list of warning and there is no list of warnings in the manifest.
- [x] Scape key gets out of the cluster mode unexpectedly
- [x] Sometimes it fails to show the replicas required (when the number of running replicas is 0)
- [x] When the info / manifest panel is shown, the artefact that is being shown should be highlighted, so you can know what are you modifying in the list of artefacts
- [x] Update the information details with incoming links and outgoing links, not only in the description as a hover, but in the description of the artefact.
- [x] In cluster modes, links should be a navigation to the object, not the files
- [x] Some links are showing the forbidden sign instead of doing things, hide them
- [x] Overview looks exactly equal to Access Control or others that are resources. (needs design)
- [x] Add nodes lists
- [x] Make the elements in Inventory and info (in Overview), links to the actual resources
- [x] Add namespace list to the inventory and link to the namespace detail
- [x] Add namespace table with details of the namespaces
- [x] Add an underline when there is a link to be clicked in the error popup, so the user knows that is a link
- [x] In the manifest editor, substitute the dot (red) for an error with an underline, and enable the link so you can navigate
- [x] the resource number should not be a blue circle (see Julio comment below)
- [x] hide resource kinds that do not exist
- [x] change colors when the link does not follow anyplace  because they are not links
- [x] dashboard: delete the links that are not doing anything today
UI comments:

**Left bar**
- [x] Blue header on top of the bar with cluster name: take away the dropdown arrow on the right.
- [x] Filter icon next to the search bar: it does nothing, take it away
- [x] Hovering resources row bg color: it must be lighter grey instead of blue, same as on regular file browsing.
- [x] Added a dashboard icon right to the "overview" label (check out figma: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=8%3A348&t=pDHbz3hYsA6VOJ9D-1)
- [x] Take away blue circles for resource count and have the number in just darker grey (check out figma: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=8%3A348&t=pDHbz3hYsA6VOJ9D-1)

**Overview**
- [x] Top title bar ("overview") and modules title bars ("status", "utilization"...) add more padding to the left of the label, check out mentioned figma.
- [x] Modules titles bars: take away blue links aligned right if they don't do anything.
- [x] Inventory and Info module: no need to have space between the 3 sub-areas, all the content can just be still divided with the grey lines but all aligned top, with regular space above and below the dividing lines (check out mentioned figma). Also, have the grey dividing lines 1px width (now they have 2px or so)
- [x] Inventory and Info module: have there the schema/API version, in the middle section (check out mentioned figma)
- [x] Utilization module: there is a "glow" on original design to blue part of the bars, can we have that? (check out CSS in the figma)
- [x] Utilization module: the info icon next to each of the bar main labels (CPU...) should show some explaining tooltip on hover (with what is that info).
- [x] Status module: 3 text labels can be increased in size correspondingly a couple of nods.

**resources listings**
- [x] Hovering a row: bg color is fine. Clicking a row: bg needs to go same light blue as in left pane selection.
- [x] It looks like there is no bulk actions available - therefore we can take away the left checkboxes if that's the case.
- [x] Inbound and outbound icons color needs to be the same as the resource label (check out https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=61%3A126&t=pDHbz3hYsA6VOJ9D-1 )
- [x] Pods status tag colors: they are not exact (need to look at border color, bg color, text color). Find colors for 4 status here (let me know if there are more status) https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=61%3A126&t=pDHbz3hYsA6VOJ9D-1 
- [x] Namespaces status tag colors: for active tag lets have same colors as Completed status in previous issue.
- [x] Namespaces list: labels column: tag color: let's have the same colors as in Running (previous).
- [x] Allow the user to select more than one namespace
- [x] When you enter the cluster for the first time (or disconnect and connect to it), you should be in the overview panel, not the last one used
- [x] Change tooltip in the Utilisation panel in the Dashboard (CPU: Used CPU / total CPU in cluster) (Memory: Used memory / Total Cluster Memory) (Storage: Used Storage / Node Storage)

<img width="673" alt="image" src="https://user-images.githubusercontent.com/7500590/204340930-1487473c-822e-4eba-b01e-6ec8e3566c57.png">
<img width="222" alt="image" src="https://user-images.githubusercontent.com/7500590/204341572-a044c8ba-cfd5-4ebf-9948-ff96d76cce70.png">
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/7500590/204341695-eb8ad2c8-ffca-4219-8f84-eb7842587f22.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/7500590/204343233-2a810a77-1270-4aa6-9c5b-c3cb57379f90.png">
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/7500590/204344053-ab5cb23f-e654-4a80-af0d-fd55efc0606a.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/7500590/204344983-30efe572-fba1-46fc-95b0-de93a33d05b6.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/7500590/204346825-49369bad-5a97-4b7a-895d-05733d95f82e.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/7500590/204347409-99d1df3d-8602-4f6c-a4d3-9c9000e68957.png">
<img width="165" alt="image" src="https://user-images.githubusercontent.com/7500590/204352727-7acc85a8-a3a3-4bfd-98e9-b29625728b71.png">

**Comment by chargio** [comment]
- [ ] Rename code in details to "Manifest"
- [ ] Implement index nagigation (< > buttons)
- [ ]

**Comment by olensmar** [comment]
- [ ] navigate from error popup directly to code editor
- [ ] add "Deploy" button to code editor

**Comment by chargio** [comment]
- [ ] Cluster mode with real time updates still shows reload (and reload disconnects / connects taking lots of time)

<img width="643" alt="image" src="https://user-images.githubusercontent.com/7500590/204347409-99d1df3d-8602-4f6c-a4d3-9c9000e68957.png">

**Comment by chargio** [comment]
- [ ] Add nodes lists
- [ ] Make the elements in Inventory and info (in Overview), links to the actual resources

**Comment by chargio** [comment]
- [ ] Add an underline when there is a link to be clicked in the error popup
- [ ] In the manifest editor, substitute the dot for a underline, and enable the link
- [ ] the resource number should not be a blue circle (see updated designs)
- [ ] PR make the list of resources "kind" clickable and show a summary of resources
- [ ] make the resources kinds expandable
- [ ] hide resource kinds that do not exist
- [ ] PR show number of CR in each CRD
- [ ] PR add link to CRD definitions as part of the Dashboard definition
- [ ] change colors if they are not links
- [ ] dashboard: delete the links that are not doing anything today
- [ ] PR make activity panel

**Comment by julioramosest** [comment]
UI comments:

**Left bar**
- [ ] Blue header on top of the bar with cluster name: take away the dropdown arrow on the right.
- [ ] Filter icon next to the search bar: it does nothing, take it away
- [ ] Added a dashboard icon right to the "overview" label (check out figma: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=8%3A348&t=pDHbz3hYsA6VOJ9D-1)
- [ ] Take away blue circles for resource count and have the number in just darker grey (check out figma: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=8%3A348&t=pDHbz3hYsA6VOJ9D-1)

**Comment by chargio** [comment]
- [ ] Allow the user to select more than one namespace
