### ISSUE TITLE
Additional UX improvements for the cluster mode

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2838]
Addtional bugs and improvements required for cluster mode after the release.

- [x] Add a tab to access to logs like in the navigation panel
- [x] The activity log does not have a "pause scrolling" (button or stop scrolling when you are not at the bottom of the list)
- [x] The activity should be accessible in an activity panel, where the user will be able to filter events, and see details for one specifically
- [x] Add link to CRD definitions as part of the Dashboard definition.
- [x] Make the list of resources "kind" clickable and show a summary of resources as a table in a different page. The list will show all resources with the number of instances, including those that are 0, to understand what is possible to install in the cluster and the number of resources associated
- [x] Connection indicator that the cluster is being loaded should 
- [x] Add terminal connected to the pod in the pod

**Comment by julioramosest** [comment]
UX and UI for scrolling help in the Activity module: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=639%3A5626&t=4A3neKElAFtaRU8P-1 
<img width="1440" alt="2 0 - activity scrolling 1" src="https://user-images.githubusercontent.com/97731654/212725062-ab94f062-fb7a-45e3-9a8d-3514bf29600c.png">
<img width="1440" alt="2 0 - activity scrolling 2" src="https://user-images.githubusercontent.com/97731654/212725094-273cb273-7fd6-4c97-aaea-a505e39059fc.png">
