### ISSUE TITLE
Fix connecting stops without reloading

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2839]
Monokle will disconnect from the cluster without notifying the user, and will miss some updates, when connecting again, the list of resources is not valid.

- [ ] Show message specifying that the cluster is disconnected. Show message if the network is unreachable
- [ ] Connect automatically if the server is disconnected (try x times)
- [ ] Show message telling the user that we are trying to connect again (if network is up)
- [ ] Update the list of resources in the background, don't delete the list of resources to create the new one until the processing has been done. Tell the user that the list has been updated.

**Comment by julioramosest** [comment]
Find UI and UX notes in files:
https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=604%3A5101&t=F0obj3qvEzH1fgm8-1 (notifying / showcasing connection error)
https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=606%3A5218&t=F0obj3qvEzH1fgm8-1 (notifying connection is back)

<img width="1440" alt="2 0 - cluster - connection error 1" src="https://user-images.githubusercontent.com/97731654/209804048-54a47a34-f826-46c5-b525-55e3a01823f2.png">
<img width="1440" alt="2 0 - cluster - connection error 2" src="https://user-images.githubusercontent.com/97731654/209804059-68cd5129-919b-4282-a22d-3086426a8a77.png">

**Comment by chargio** [comment]
Test if this still applies after the refactoring
