### ISSUE TITLE
Apply validations in cluster mode

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2841]
Validations are not shown in cluster mode when a project is not selected.
As a user, I want to see the validations applied when I connect in cluster mode.

- [x] Validations are not shown in cluster mode when a project is not selected
- [x] Navigation is restricted to those parts of the interface that works with clusters and configuration, everything else is disabled.
- [x] Validation is shown using the configuration defined
- [x] K8s schema used for validation is the version installed in the cluster.

**Comment by topliceanurazvan** [comment]
Update: currently we fixed having validation inside the cluster mode when there is no project selected.

**Comment by chargio** [comment]
Pending on the validation core

**Comment by chargio** [comment]
Can we close this?
