### ISSUE TITLE
2 issues in review of main with Windows

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#2863]
**Describe the bug**
- I load main and click on the "quick cluster preview" button on my getting started page. I get the full pane version with zero resources count on the resouces pane. Shouldn't it get me to the empty status with text+image pointing me top right  to cluster connection?
- 3 dots menu > new in X.X - update to 1.13

**Comment by topliceanurazvan** [comment]
Tested and both problems are working as expected
