### ISSUE TITLE
Refactor usage of Templates in 2.0

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2865]
In 2.0, we will change the way we're using Templates within Monokle.

---

For context, read about [Plugins](https://kubeshop.github.io/monokle/plugins/) and [Templates](https://kubeshop.github.io/monokle/templates/) in the documentation.

Currently in 1.x , Templates can be found in the left menu as a dedicated panel:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/20538711/206172413-fa3a0208-3843-494a-a72b-5364d10f4c7b.png">

Templates can be used by clicking on the `Use Template` links which will open a Modal where the user has to complete one or multiple forms that will generate resources at the end.

---

For 2.0, we will remove the panel from the left menu entirely.
Instead of the Panel, we will create a new dedicated Modal that will handle both displaying the list of templates that are available and at the same time allowing the user to use the templates.

This is how that modal will look like:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/20538711/206172739-5a4c2387-172c-439b-8315-d893521e7a50.png">
Figma link: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=778%3A4339&t=yKjR3U7U2gmpM6Y3-4

In the left part, we see the list of available templates, grouped by the Plugin they installed from.

Then, clicking on one of the templates will mark it as selected in the left menu and it will open it on the right part:
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/20538711/206173221-e53ae649-c0d4-4959-b44c-d94bdbcc7ecf.png">
Figma link: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=793%3A5112&t=yKjR3U7U2gmpM6Y3-4

On the right part, **we will directly see the first Form step** , while before in 1.x we would see an information step.
The information step will not be needed anymore because we have the information card at the top that will be visible for all steps.

The information card at the top uses the new **TitleBar** component from 2.0.
We should set it as collapsible / closable because it would be nice to collapse the information while we go through the steps / forms. Additionally, we should try to automatically collapse the information card when the user starts interacting with the from.

---

**How do we trigger the new Modal to appear?**

To start with, this Modal will be triggered from the + icon at the top of the navigator, with a caveat.
<img width="358" alt="image" src="https://user-images.githubusercontent.com/20538711/206496007-d00807a8-a25c-4724-bacc-8d6bc68e7435.png">

Hovering the + icon should now show the following dropdown:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/20538711/206491667-5ce42460-bd57-4f04-90ab-10fea65855d0.png">

If the "New from scratch" option is clicked, then we open the `NewResourceWizard` modal (which what clicking on the plus icon is doing at the moment in 1.x versions).

If the "New from template" option is clicked, then we will open the new modal which is described above.

---

**Code suggestions**

The new modal could be named `TemplateExplorer` and it should be a new component in the `organisms_new` folder.

Info about our current components:
The `TemplateManagerPane` component can be used as an example to see how to list all the existing templates.
The `TemplateInformation` component will probably not be needed anymore since for listing the templates we will show a lot less information in the new design.
The current `TemplateModal` component will probably have to be renamed and it could be refactor to be used in the right part of the new `TemplateExplorer`.
The `TemplateFormRenderer` component could probably be used as is without any major changes, since this component is only responsible for rendering one of the template forms, and a template could have multiple forms.

Find the relevant models in `models/plugin.ts` and `models/template.ts` (they are written using `runtypes` which is a library that helps validating objects to match the typescript type, but it shouldn't be too important for this task since the logic of validating templates will not change).

**Comment by chargio** [comment]
Left side bar finalizing
Now working on the right side bar
