### ISSUE TITLE
Refresh Cluster Resources

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#287]
During a Cluster Preview I would like to be able to refresh cluster resources instead if having to exit and redo the preview... When refreshing I should keep the current resource selection. 

Perhaps a "Refresh" button next to the "Show Cluster Objects" one - similar to the Reload button in the file explorer?

**Comment by erdkse** [comment]
Every time we reload the kubeconfig. It generates a new `resourceMap` with different UUIDs. Even though I keep the selection history, the previous and the current UUIDs don't match. So It is not doable with the current implementation. Maybe we can consider setting a permanent ID to an individual resource. @olensmar
