### ISSUE TITLE
See the validation panel grouped by rule

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2919]
As a user, I want to be able to see what resources / files are failing a validation rule.
See the list of rules, and the files / resources that are failing that

**Comment by julioramosest** [comment]
find design, UX and functional notes:

validation errors by file: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1464%3A7957&t=JpqpZSbJ66YaXoBY-1
validation errors by rule: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1509%3A8147&t=JpqpZSbJ66YaXoBY-1
validation errors by resource: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1509%3A8379&t=JpqpZSbJ66YaXoBY-1
