### ISSUE TITLE
Show validation panel by resource

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2920]
As a user, i want to be the validation panel grouped by resource

**Comment by julioramosest** [comment]
find design, UX and functional notes:

validation errors by file: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1464%3A7957&t=JpqpZSbJ66YaXoBY-1
validation errors by rule: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1509%3A8147&t=JpqpZSbJ66YaXoBY-1
validation errors by resource: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1509%3A8379&t=JpqpZSbJ66YaXoBY-1
