### ISSUE TITLE
Add telemetry for following up on K8s documentation

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2947]
One of the features that we consistently learn is good for users is to be able to get links to the documentation. However, we don't have information about how many users are actually recurring to this.

Let's add the event when a user clicks on a K8s documentation

**Comment by devcatalin** [comment]
Done in https://github.com/kubeshop/monokle/pull/2963

The event is `help/open_link` with a payload of:

```
linkType: external_documentation
link: [the link the user navigated to]
```
