### ISSUE TITLE
Monaco component refactor

### ISSUE THREAD

**Issue by catalinhoha** [kubeshop/monokle#295]
**Describe the enhancement you'd like to see**
The component is getting large and harder to manage. I suggest we do the following changes to it:
- extract code intelligence logic into a custom hook `useCodeIntel`
- extract actions for keybindings to a separate module, see issue: https://github.com/kubeshop/monokle/issues/294

**Comment by olensmar** [comment]
this could perhaps also fix the "flashing" issue?! it seems the editor is re-rendered for every keystroke!?
