### ISSUE TITLE
Installation without Windows admin account

### ISSUE THREAD

**Issue by philippe-granet** [kubeshop/monokle#2958]
**Describe the enhancement you'd like to see**
I want to be able to install monokle without Windows admin account

**Additional context**
In our corporate company, we can't launch programs with admin rights (for security reasons)

**Comment by devcatalin** [comment]
Hi @philippe-granet, sorry for the delay!
In our latest release, [version 2.1.1](https://github.com/kubeshop/monokle/releases/tag/v2.1.1), we have addressed this issue. 
Now, the installer no longer asks for an admin account during the installation process.
If you have any further questions or encounter any issues, please don't hesitate to reach out.
