### ISSUE TITLE
Create RPM package for Monokle

### ISSUE THREAD

**Issue by Loki-Afro** [kubeshop/monokle#2960]
**Is your feature request related to a problem? Please describe.**
I do simply prefer rpms over flatpak or snap images :)
Can this be reconsidered since it already got mentioned here https://github.com/kubeshop/monokle/issues/1939

**Describe the solution you'd like**
build also rpms

**Comment by chargio** [comment]
We plan to fix it with Flatpak and Snap versions

**Comment by devcatalin** [comment]
We now have RPM packages in the new releases
