### ISSUE TITLE
Slow resource selection with many resources

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#299]
When there are many resources in the navigator (500+) there is a noticeable delay between clicking on a resource and seeing it in the source editor... judging from the react performance recording this is because react is re-rendering the entire navigator on selection change (virtually) - when filtering on namespace that only contains a few resources the selection is fast... 

Would it be possible to not render navigator resources that are outside the screen? Or bind each resource row directly to their corresponding resource so only affected resource-rows are updated on selection change!?

**Comment by erdkse** [comment]
I have tested it with 3100+ resources. The first load is significantly slow and the application freezes for some time but after filtering by namespace It is faster. As you guys say the performance issue can be solved by configuring react re-render mechanism. 

But there is also a freezing issue that we need to solve. As @kambydyne suggested we can make it more user friendly(maybe by showing the progress of the process)
