### ISSUE TITLE
New learn page

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3012]
Add the learn page where the user can see the different CTA to learn about the capabilities of Monokle.

See the onboarding pages
https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=0%3A1

**Comment by devcatalin** [comment]
@chargio we've built the page but we'll need from you the list of walkthroughs with titles and descriptions to be added in the app

**Comment by chargio** [comment]
Blocked until we can release with the new interface screenshots

**Comment by julioramosest** [comment]
This can be unblocked - all design is finished and featured illustrations for every learn popup are on the figma: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1934%3A8826&t=MeTrkCPUKIJ7S71j-1 - Please let me know if there is some issue exporting the featured images to SVG, I'll help.
