### ISSUE TITLE
New filter UI

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#3025]
As a user I would like to have the filters (resources and/or files) visually differentiated along the lines of Monokle Cloud.

find design and UX notes here: https://www.figma.com/file/piYTewRAVtQJRQreG6CECh/Filter-for-Resources-and-Files?node-id=0%3A1&t=xK8wHuAMsQrRYldt-1

<img width="1440" alt="search and filter combo - default status" src="https://user-images.githubusercontent.com/97731654/214014097-11513492-4cfb-4a95-9dab-05ae242af727.png"> 

<img width="1440" alt="search and filter combo - filter displayed" src="https://user-images.githubusercontent.com/97731654/214014116-7af6ff11-4a30-4e09-8db6-ce385d2089ab.png">

**Comment by chargio** [comment]
Copy the component in cloud
