### ISSUE TITLE
When hovering on errors/warnings on top of the navigator, we should link to the audit page.

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3033]
Hovering/clicking o n the top errors should link to the full list of them.

![image](https://user-images.githubusercontent.com/7500590/214252102-bdf7d5fb-e59b-477d-97db-02872afe516a.png)

- [ ] Link to the audit pane to make it easier to brwse
- [ ] Clicking on each of them will trigger filtering for that kind of warning
- [ ] It should be clear that the issues are filtered.

**Comment by topliceanurazvan** [comment]
This is implemented on the latest main.
