### ISSUE TITLE
Allow edit of resources in Cluster preview

### ISSUE THREAD

**Issue by catalinhoha** [kubeshop/monokle#306]
**Describe the enhancement you'd like to see**
When previewing the resources in the Cluster I would like to be able to edit the resources in the source editor and the changes should be applied to the Cluster on save.
I shouldn't have to save the yaml file locally, nor browse for a folder beforehand.

**Comment by olensmar** [comment]
how would this work in the regard to auto-save!? 
- disable debounce/auto-save
- enable apply/diff buttons once a change has been made
?

**Comment by catalinhoha** [comment]
That sounds good, we should also introduce hotkeys for save and diff
