### ISSUE TITLE
Create the Accordion in the new ExplorerPane

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3071]
Right now the Accordion in the new ExplorerPane doesn't work.
We're showing the Files but we cannot collapse them and the UI is out of bounds.

The other panes in the accordion have not been yet implemented.

We should create base components in the ExplorerPane/Accordion folder that will be used by the other panes for the TitleBar and collapsing logic... Monokle Cloud could be used as an example for those components.

Within the Helm/Kustomize/Image panes we should use the SectionBlueprints that we've used in the old panels.

After this Accordion is completed, we can remove the old panels that we had.

**Comment by chargio** [comment]
When you have both accordions, we should be able to tell the user which accordion is the one where the resource is available.

**Comment by chargio** [comment]
Also, understand what happens when the user select a file that is not currently visible in the accordion.

**Comment by julioramosest** [comment]
@chargio in your latest comment you mean when selecting a resource in the middle pane, right? (because selecting files can only happen in an open tab of the accordion itself)
