### ISSUE TITLE
UI review for 2.0 launch

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#3103]
(Please don't close this issue before 2.0 launch. Sub-tasks can be marked as completed. Grouped by section)

**SELECTION UI - 1ST TIME USE**
- [x] Release notes popup: remove for first time users (they should be focusing on starting quickly - tracking latest changes is not interesting to them) ( Razvan )
- [x] Implement the large tooltip pointing to Learn as designed here:  https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=2287%3A10135&t=BojHnYKqKJsI8PSo-1 ( Razvan )

**SELECTION UI - RECURRING USER**
- [ ] Header: Have the main search there as designed. We can mimic the same exact logic than the Ctrl+p search
- [x] Header: remove the action from the monokle icon. ( Razvan )
- [x] Recent projects: When that area its empty (1st time use or I deleted all projects): show a simple text that says: "Click on **New project** on the left menu to create a project" (adding the plus icon next to new project label) ( Razvan )
- [x] All projects: When that area its empty  (1st time use or I deleted all projects): show a simple text that says: "Click on **New project** on the left menu to create a project" (adding the plus icon next to new project label) ( Razvan )
- [x] Settings: all content below the tabs is contained on a grey box. Delete that box or have the color transparent or the same color as the background. ( Razvan )
- [x] Settings > Plugins manager: let's have the install action aligned left and within a grey box (as it is now, but aligned left). The templates can appear below, out of the box, as said above. ( Razvan )
- [x] Its great that we have the left menu column fixed and the middle column scrolling itself (settings, learning...). But can we have that scroll to the right of the whole page? maybe having the central column and the right empty one being just one element? ( Razvan )
- [x] Three dots menu on the top right: add a bit more padding overall (circa 10px) to the whole dropdown. Now text goes very to the right border of the dropdown element. ( Razvan )
- [x] "connect to cluster" label on the left menu. are we ok with that label? shouldn't it be "quick cluster preview" or "cluster preview"? more on cluster section below.

**CLUSTER DASHBOARD**
- [x] When connecting to a cluster the header with my current project stays there, but cluster connection is independent (since it has its own left menu also). The header  should not show the three lines and the name of the project, but a Back to projects button, as in design: https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?node-id=706%3A5593&t=c57A5cwmYo25iqEL-1
- [x] Related to previous one, when I exit cluster mode, the editor UI header stays in top of the selection UI, see illustration below. Fix. User should be in either editor UI or selection UI. It's even possible to change projects and you still see the cluster left menu - you get in a loop you can't scape from.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/97731654/217795975-2ac0bf89-5311-406e-b878-300a3bd43d59.png">

- [ ] Error count badges in resource groups list on the left. Now they are in a circle. Let's have them into an adaptative rectangle (16px height, adaptpative width) with sufficient radius (8px), so the tag nicely adapts to whichever long number.
- [ ] Same with error badges on the main area, in resources list.
- [x] Status module: it appears weirdly floating within its space with different margins than the rest of the modules. See illustration. Fix to appear as the others, same height as the one on the right, etc

<img width="349" alt="image" src="https://user-images.githubusercontent.com/97731654/217788457-ce0de06e-fb8c-4482-9603-90d24fa1a6f9.png">

**EDITOR UI**
**Validation tab (left pane)**
- [x] blue header: to the text "Visualize & fix errors according to your validation setup." lets add (in the same line): "Set up your validation policy, activate/deactivate rules, etc in the settings section from the left menu." being "settings" word a link to the settings, corresponding tab. ( Razvan )
- [x] Errors list: errors appear collapsed. Guess we want it like that for performance?
- [x] When no error is selected the editor appears empty. Let's have the same UI that in the View GIT operations tab (see image below) with the text "Select an error in the left to view it in the code, fix it, get fixing tips and more." ( Razvan )

<img width="229" alt="image" src="https://user-images.githubusercontent.com/97731654/217803131-828776c7-45c6-4d0e-9c7e-2326536513e0.png">

- [x] Errors list: do we want tooltips for items in the left or the error? validation source, severity, line of code... I would have them. (Razvan )
- [x] Errors list: lets have the error badge with same looks as in the resources pane (not totally round ones) ( Razvan )
- [ ] Code: we are briefly highlighting the line of code containing the error. Looks great but since its on the bottom of the code view (last visible loc) it kind of gets unnoticed a bit. Can we have the line of code in the center of the view instead or the bottom? or simulate that somehow?

**Files tab (left pane)**
- [x] Top title for middle pane (and content below) need to increase left padding so collapsing white button does not stick to the title (see image below). It's well resolved in the Validations pane. ( Razvan )

<img width="68" alt="image" src="https://user-images.githubusercontent.com/97731654/217836748-311ee3d9-0be3-447f-9341-7d3740758261.png">

- [x] changing item in the accordion changes pane width. It should stay the same unless user moves it.
- [x] hover/clicked item bg coloring in the file tree should go border to border of the pane. See current below: ( Razvan )

<img width="348" alt="image" src="https://user-images.githubusercontent.com/97731654/217842441-5d1ee30e-7096-4985-b385-64c8440c9986.png">

- [ ] Random app freezing when changing accordion item (monokle repo local)

**Git pane**
- [x] title header has the same visual issue with title bars sticking to the collapsing white icon (see image below). Fix according to design. ( Razvan )

<img width="98" alt="image" src="https://user-images.githubusercontent.com/97731654/217837918-4805be35-9e85-46ab-a1b4-8c4c6ed74f73.png">

**GENERAL**
- [x] Left main menu bar: icons within their circles are too small. Check out design. ( Razvan )

**Comment by chargio** [comment]
- [ ]  Accordion is hiding when you select Files

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/7500590/217823023-8c641f47-8b00-49e0-9e51-9f1ec7d946f1.png">

- [ ] Three dots still talk about "what's new in 1.13"
- [ ] Learn button is not available in the files view
