### ISSUE TITLE
Recent Folders

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#318]
I would like to be able to switch between recently parsed folders easily - instead of having to browse to them manually every time...

**Comment by tommywhitehead** [comment]
I'd propose that we take advantage of OS menus for recent folders. It's a common paradigm that should be obvious for most users and it looks like Electron has some documentation around how to build it already!

https://www.electronjs.org/docs/tutorial/recent-documents

**Comment by tommywhitehead** [comment]
Ideally we could also add an `Open recent` fly out in the File menu like this: 
![image](https://user-images.githubusercontent.com/4236167/131694200-d8d4b7d6-80e8-4ed2-b3f0-71075e08f6e9.png)

**Comment by olensmar** [comment]
thanks @erdkse - we should create separate issues for implementing/using these as applicable

**Comment by olensmar** [comment]
see #334
