### ISSUE TITLE
2.1 Code improvements 

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3181]
Created this issue to keep track of things that we should improve in the code for 2.1:

- use the new `fileEntry.rootFolderPath` to get the path of the rootFolder instead of `fileMap[ROOT_FILE_ENTRY].filePath`

- remove comments that disable the eslint react/no-exhaustive-deps check and fix the problems using refs

- Instead of using React state for showing something on hovering over a `div` or some html element, use CSS directly ( with display `none` and `block/flex` etc...`

**Comment by mortada-codes** [comment]
we need to move the read/write files from the reducers
Also, we need to move  `new KubeConfigManager()  `from reducers
