### ISSUE TITLE
Unable to set the default kubeconfig file

### ISSUE THREAD

**Issue by dhiguero** [kubeshop/monokle#3225]
**Describe the bug**
After trying to setup a custom kubeconfig file to be used with monokle, it still uses the default `${HOME}/.kube/config`.

**To Reproduce**

1. Go to 'Settings' and select a kubeconfig

![Screenshot 2023-02-16 at 13 43 00](https://user-images.githubusercontent.com/6400250/219368298-6581e4b1-5b9a-48fe-93e9-ecddad1a13d6.png)

3. Click on 'Quick cluster preview'
4. The list of contexts still shows the ones in the default kubeconfig. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Monokle Version: 1.13.4

**Additional context**

**Comment by topliceanurazvan** [comment]
Hello @dhiguero, and thank you for reporting this. We have just released `2.0.1` which should fix the problem that you had. 
Please let us know if everything works as expected.
