### ISSUE TITLE
Monokle Cloud Redirects To Localhost After Choosing a GitHub Repo

### ISSUE THREAD

**Issue by techmaharaj** [kubeshop/monokle#3232]
**Describe the bug**
When I log in to Monokle cloud and try to import a GitHub repo, it redirects me to localhost:1001

**To Reproduce**
1. Head to Monokle Cloud available at [app.monokle.com](https://app.monokle.com)
2. Login using GitHub
3. Create a new organization
4. Create a new Project
5. Add a Repository to the Project
6. Under GitHub Account (_Shows me Add an Organization or Account in the drop down_)
7. Select that option. opens a new window with GitHub and asks me to choose my account _(I have multiple org and personal accounts)_
8. Choose an account, select all repositories & click on Install & Authorize _(notice the redirect text below the button, screenshot attached)_
9. It leads to 404 and the URL redirect takes me to localhost:3001

**Expected behavior**
I should be able to add a repo and post that the app should redirect me to Monokle. I've tried it multiple times and always getting the same issue.Even on different browsers.

**Screenshots**
Screenshot 1: 
Choosing the repo, notice the redirect text
![image](https://user-images.githubusercontent.com/10296271/219563755-568f0225-0f36-4d62-8140-758e5977e795.png)

Screenshot 2:
Redirected to localhost
![image](https://user-images.githubusercontent.com/10296271/219563801-67c51d75-0a1d-4a26-a290-e35e66f6732c.png)

**Comment by WitoDelnat** [comment]
Hello @techmaharaj,

Thank you for reporting this issue. It has been resolved in the meantime.

Please let us know if you run into any other issues and we'll swiftly remediate them.
