### ISSUE TITLE
Something went wrong during the creation of a file

### ISSUE THREAD

**Issue by SawantDarshan** [kubeshop/monokle#3242]
installed windows monokle.
opened my existing folder with kubernetes templates.
existing templates are showing up as  like this 
��a��a��a��a��a��a
i tried create new file its showing up 
Creating failed
Something went wrong during the creation of a file

**Comment by chargio** [comment]
Looking at it. Thank you for reporting.

**Comment by topliceanurazvan** [comment]
Hello @SawantDarshan, and thank you for reporting this. We have just released `2.0.1` which should fix the problem that you had. Please let us know if everything works as expected.

**Comment by SawantDarshan** [comment]
Thanks for reply i will check on my side and let you know.

Darshan Sawant
