### ISSUE TITLE
Helm Charts browser + repo support

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3251]
I would like to be able to browse and search for helm charts an install them to my cluster or download locally.
- [ ] I should be able to configure charts repositories (add/remove)
- [ ] I should be able to see a list of all charts in my configured repositories 
- [ ] I should be able to search for a chart by name
- [ ] Once i've found a chart I should be able to see some kind of information panel (similar to what we have for images)
- [ ] There should be actions to either install a chart to an active cluster or download to local project - if these aren't available the corresponding action should be disabled for now (we can have prompts to create a local project for a Helm Chart later)
- [ ] When downloading to a local project I should be able to specify to which folder I want to download the chart
- [ ] When installing to my cluster I should be able to specify the namespace
- [ ] After downloading I should be taken to the Explorer with the Helm section expanded and the Chart file selected 
- [ ] After installing in my cluster I should be taken to the "Helm Charts" section of the Dashboard (separate issue)
- [ ] If Helm is not installed we should prompt the user to do so before using this feature

Implementation notes:
- Operations for fetching the list , downloading, updating etc, should happen in the main thread.
- Find design and UX notes here: https://www.figma.com/file/OUQvnjZXPXYiTjtIL1eCeM/Helm?node-id=0%3A1&t=IGU7OcbrzFeDpq0e-1

**Comment by mortada-codes** [comment]
https://helm.sh/docs/helm/helm_repo/

**Comment by mortada-codes** [comment]
https://helm.sh/docs/topics/chart_repository/

**Comment by julioramosest** [comment]
find designs here; https://www.figma.com/file/OUQvnjZXPXYiTjtIL1eCeM/Helm?node-id=0%3A1&t=IGU7OcbrzFeDpq0e-1

**Comment by ypoplavs** [comment]
Helm management is quite important for my daily activities as well - ability to list, install, upgrade release is an indispensable part when you work with k8s. Commenting to speed up this feature :)
