### ISSUE TITLE
Change Cluster connect message

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3273]
![Image](https://user-images.githubusercontent.com/20538711/220123409-511e8b48-926a-44f8-b493-03af92b79c01.png)

We should change the above message to:

"Click on Connect to load the resources from your cluster and watch for changes."

**Comment by julioramosest** [comment]
@devcatalin search in this section should have the same look&feel as in files search and the rest of the accordion elements. Should I create a separate issue for this?

**Comment by devcatalin** [comment]
@julioramosest I've updated the Screenshot because I added the wrong one to this issue.
You can create a new issue for the search of images
