### ISSUE TITLE
Git loading stuck

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#3309]
Sometimes when you open a project the git loading is getting stuck so you can't use the git features anymore.

**Comment by chargio** [comment]
Do we have an example for this?

**Comment by chargio** [comment]
Ask @WitoDelnat to see if we can reproduce it again

**Comment by WitoDelnat** [comment]
Didn't realise there was already an existing issue. This is a duplicate of [unhandled git errors](https://github.com/kubeshop/monokle/issues/3540)

**Comment by olensmar** [comment]
closing since it's a duplicate
