### ISSUE TITLE
Click outside resource label doesn't select it

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#3310]
If clicking on the resource row outside of the label, the resource doesn't get selected

![image](https://user-images.githubusercontent.com/47887589/220897238-1ffbae4a-1419-4471-ad35-5df07c408ffa.png)

**Comment by KarthikRaju391** [comment]
Hey @topliceanurazvan, I would like to work on this issue. I am not sure what the problem might be but I would like to look into it.

**Comment by topliceanurazvan** [comment]
Hey @KarthikRaju391, I will assign you to this issue.

The problem is that if we now try to click outside of the label ( `happy-cms` in the screenshot above ) the item doesn't get selected. We should select it whenever we click anywhere inside the hovered item. This logic should be happening inside the `ItemRenderer.tsx` component.

Let me know if need any help. Best of luck! 🤞🏻

**Comment by KarthikRaju391** [comment]
@topliceanurazvan, I wanted to know if there was a project template I could use to be able to use all the functionalities in the application...

**Comment by topliceanurazvan** [comment]
I would suggest working with the monokle-demo repo https://github.com/kubeshop/monokle-demo
