### ISSUE TITLE
Monokle Desktop 2.0 - Create Resource From Template Dialog Doesn't Disappear After A Resource Is Created

### ISSUE THREAD

**Issue by techmaharaj** [kubeshop/monokle#3328]
**Describe the bug**
After I choose a template, fill in the details, and click on the done button, it takes me back to the custom resources form. I don't know if the resource is created or not. 

**To Reproduce**
1. Launch Monokle Desktop 2.0 & create a new project
2. Choose Start from a template
3. Provide a name to the project and click ok
4. In the `Create Resource from a template` dialog box, choose `Basic Pod` template and fill in the details
5. Click on Done

**Expected behavior**
The dialog should disappear and the resource should be created.

**Screenshots**
Creating  a resource using Basic Pod Template
![image](https://user-images.githubusercontent.com/10296271/221772927-14d8a846-b44f-4f9a-ac04-19a27d589ab1.png)

Fill in the details and click on done
![image](https://user-images.githubusercontent.com/10296271/221773130-56132778-b20d-46c9-b963-f563e3d1289e.png)

Clicking on Done takes me back to the Create resource from the template page
![image](https://user-images.githubusercontent.com/10296271/221772506-54bd4e82-4485-4e87-884e-a579ae37868b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Workaround**
Close the dialog box manually and navigate to projects to see the resource being created.

**Comment by topliceanurazvan** [comment]
Hello @techmaharaj,

For this behavior, we thought a user might want to use multiple templates before interacting with their resources, so we decided to keep the modal open. That way, they can seamlessly select templates and create resources without any interruptions. Once you've used a template, we show you the resources that have been created and you can quickly select them by clicking on the icon next to their name (check out the screenshot).


![image](https://user-images.githubusercontent.com/47887589/221794775-67ce74c2-b376-40f3-8567-60b3d2fcf985.png)

We really appreciate your feedback and want to know if you find this feature confusing or annoying. Do you think the modal should close after successfully using a template?

**Comment by techmaharaj** [comment]
If that's the case, it should show a dialog to check if I want to create another resource. If I say No, take me to the Projects page, if I say yes, take me back to this modal.

Currently, it feels like nothing happened after done is clicked.

**Comment by cerebro31** [comment]
If there is already a project created using a template and we want to create a new project using a template, the resource manifest is not created for the same.

https://user-images.githubusercontent.com/125909758/221801046-e5857884-cf5d-4913-b912-5d651a167b9b.mp4

I have attached a video where I am creating a new project but the files and folders for it are not getting created. Though Monokle shows that the manifest is created but there is no file as you can see.

**Comment by topliceanurazvan** [comment]
> If there is already a project created using a template and we want to create a new project using a template, the resource manifest is not created for the same.
> 
> I have attached a video where I am creating a new project but the files and folders for it are not getting created. Though Monokle shows that the manifest is created but there is no file as you can see.

It seems like this is another issue ( bug ), we will fix it asap. Thank you for your feedback!

**Comment by julioramosest** [comment]
So do we think creating another resource right away would be a regular  behaviour? I guess users would be more into create one and then go check it. So I would:
- Make the text box containing the creation successful message with less height. Couple of lines high or so.
- Have the Done button in blue (primary)
- that button closes the dialogue. The new resource appears below in yellow, as it already does
