### ISSUE TITLE
Provide system menu

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#334]
We should have a system-menu for Monokle - suggest the following items/subitems to start with (on Mac - not sure how this translates to Windows/Linux standards)

- Monokle
  - About Monokle -> Show Monokle Launch Dialog
  - Check for Updates... -> Checks for update
  -  -sep- 
  - Preferences -> Open Settings Slider
  - -sep-
  - Hide Monokle
  - Hide Others
  - -sep-
  - Quit
- File
  - Browse Folder -> shows the folder dialog
  - Refresh Folder -> Refreshes current folder
  - -sep-
  - Recent Folders -> submenu containing recent folders - selectable
  - -sep-
  - New Resource -> Opens "New Resource" dialog (enabled/disabled as in Monokle)
  - -sep-
  - Exit Preview -> as applicable
- Edit (enabled when Monaco is in focus - shortcuts to built-in Monaco actions)
  - Undo
  - Redo
  - -sep-
  - Cut
  - Copy
  - Paste
  - -sep-
  - Find
  - Replace
  - -sep-
  - Apply
  - Diff
- View 
  - Previous Resource -> navigate back
  - Next Resource -> navigate forward
  - -sep-
  - Toggle Navigator
  - -sep-
  - default items
- Window - same as default
- Help
  - Documentation -> open documentation in Browser
  - -sep-
  - GitHub -> open GitHub repo in Browser
  
See https://www.electronjs.org/docs/api/menu#examples

**Comment by olensmar** [comment]
Alternatively we could have a "Cluster" top-level menu containing
- Select Context -> submenu with available contexts, check the current one
- Preview -> Retrieves cluster objects from selected cluster
- -sep-
- Apply -> Applies current Resource/File
- Diff -> Diff...
?

**Comment by erdkse** [comment]
I leave `Cluster` menu to do after we implement context selection etc. I couldn't find `Toggle Navigator` action. Except it the PR is ready.
