### ISSUE TITLE
"Nothing in the editor" area rework

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#3343]
New features and detected user behavior suggest we need to rework a bit the illustration+claim happening in the right pane (editor area) when nothing is selected in resources.
- The illustration is reworked to include CLI and text labels are shortened
- Text below includes calling for clicking on some resource to populate that area
- Now all labels are clickable and take the UI to corresponding section.

Find design here: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=2793%3A12270&t=rV3eE1sTOHrbTcr7-1

![nothing in the editor](https://user-images.githubusercontent.com/97731654/222491459-1d8d9630-7002-406e-bfc3-055977b82959.png)

**Comment by julioramosest** [comment]
Hey @KarthikRaju391 Julio here, Product designer for Monokle. Very glad that you are going to work on this one! Yes, you should be working on that and also changing the top image (it has been slightly revisited). You should also keep layout responsiveness (for both the image and the text) as it is today - it works nicely on all resolutions. So, in a nutshell:
- Update texts including link and hover effect
- Update image on top (SVG)
- Make sure responsiveness is kept as it is today and looks nice in all resolutions.

**Comment by julioramosest** [comment]
@KarthikRaju391 here you have the SVG for the top image in SVG format. As for the destination of the links below (what sections need to be opened) hopefully the texts themselves are self-explanatory enough - let me know if that's not the case. Thanks for contributing!

![nothing-in-the-editor](https://user-images.githubusercontent.com/97731654/223146467-3e8a93b3-2ce2-46b4-95ed-640774c2dc98.svg)

**Comment by KarthikRaju391** [comment]
@julioramosest, thanks for letting me know! I will start working on it and get back to you if I have any issues.

**Comment by chargio** [comment]
Great!

**Comment by julioramosest** [comment]
Hey @KarthikRaju391 let's see if any of the FE engineers can help you with that. @devcatalin ?

**Comment by topliceanurazvan** [comment]
Hey @KarthikRaju391,

The current code for displaying the placeholder can be found in `MonacoPlaceholder.tsx` component https://github.com/kubeshop/monokle/blob/main/src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx

Please let us know if you need any further help.
