### ISSUE TITLE
cannot connect my k8s cluster

### ISSUE THREAD

**Issue by randychen2046** [kubeshop/monokle#3347]
**Describe the bug**
cannot connect my k8s cluster

 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/29883352/223120589-fed44461-aa99-42e4-aa3c-9cc413548978.png)
**Desktop (please complete the following information):**
 - OS: window 11
 - Version 2.0.2

**Comment by mortada-codes** [comment]
Hey @randychen2046 , thank you for reporting this! 🙌🏻

Can you help us with some more information? Could you let me know if you did any specific actions to be given this error?

**Comment by randychen2046** [comment]
> 

my steps follows：
1、create  a new project
2、add kubeconf  and connect
3、connect fail
4、the same kubeconf，in Lens，it works

**Comment by Jeansen** [comment]
@randychen2046  It simply fails or do you get any specific error message?

**Comment by chargio** [comment]
Thanks for reporting this. We are working on the kubeconfig management and reviewing the code to make this work. If you are willing to try and give us feedback, we will make sure that the tool works with your setup

**Comment by Jeansen** [comment]
@chargio Let me know, how I can help and I'll check it against our setup.

**Comment by chargio** [comment]
Team,, please contact @Jeansen to work on this / test the solution

**Comment by Jeansen** [comment]
In 2.0.9 I now get "Connot connect to the cluster ... An unknown problem occured."
When I check the "View debug logs", there is only on line: `Starting to server on 127.0.0.1:30001`

**Comment by topliceanurazvan** [comment]
Hello @Jeansen, the cluster connection was improved in our latest patch release, version `2.0.10`. Can you update Monokle and let us know if you still encounter the problem?

**Comment by Jeansen** [comment]
@topliceanurazvan Nope, I am sorry. Problem still persists and nothing has changed. Any way to get some more, detailed logs to better track down the issue?

**Comment by topliceanurazvan** [comment]
Hey @Jeansen, we are sorry for the problems you are still experiencing while using Monokle. Would you be available for a call with us to troubleshoot the issue together? We would be happy to assist you through Discord at https://discord.gg/kMJxmuYTMu or any other platform that works best for you.

**Comment by Jeansen** [comment]
@topliceanurazvan That's a very nice offer. I'll be back at work in about 2 weeks. I am on vacation right now ;-)
After that I'll get back to you. Because it is a system I use at work, I'll first have to check if I am allowed to accept your offer.

**Comment by olensmar** [comment]
Hi @Jeansen are you still having this issue? If so would you be available for a call do debug with us?

**Comment by Jeansen** [comment]
Hi @olensmar Sorry, for the delay. I've tried some couple of things in the meantime. Turned out, our VPN/Proxy was the culprit. From my side, this ticket can be closed.

**Comment by olensmar** [comment]
thanks @Jeansen for this - we would love to hear about your general experience with Monokle - (good or bad!) - would you be up for a short call to share some feedback?
