### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by DavenAaron** [kubeshop/monokle#3379]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/20857689/224604528-03b73194-ec33-4129-ae88-3cb301b1ca0e.png">

**Comment by erdkse** [comment]
Hey @DavenAaron , thank you for reporting this issue, Do you get this error when you connect to a cluster? What kind of cluster do you have?

Could you please give us more information?

**Comment by Jeansen** [comment]
I also have a cert. problem. Connecting to a cluster at work gives me: Certificate expired, Cluster Resource Field. Other applications, like Lens or kubectl work just fine. I checked the kublet cert, it's valid until 2024. And all other certs I could find were also valid.

Unfortunately, at work I have to use a MacBook and I have no clue where I could get some more log output to provide here.

**Comment by chargio** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/7500590/227477644-f624b1a3-38ed-4356-a0b4-44b73c3cde6a.png">

**Comment by devcatalin** [comment]
hey @DavenAaron , we've reworked the cluster connection logic, could you try the [latest release](https://github.com/kubeshop/monokle/releases/tag/v2.0.9) to see if it works for you now? Thank you!

**Comment by devcatalin** [comment]
Closing this issue, let us know if you still encounter any problems!
