### ISSUE TITLE
base64 encoded ssh public_key stored via custom resource template form in Secret manifest shows cannot be handled

### ISSUE THREAD

**Issue by cerebro31** [kubeshop/monokle#3392]
**Describe the bug**
the base64 encoded public key, when entered via template [form](https://github.com/cerebro31/monokle-resource-template/tree/main/ssh_pod) and then the Secret manifest which is generated, has some issue with storing it correctly. Both kubectl and Monokle Desktop throw the following error.  If I once click on Form in Editor in Monokle Desktop, the format somehow gets corrected and then I can deploy the secret successfully.
```
sonali@SONALI-SRIVASTAVA:~/Monokle/ssh_enable$ kubectl apply -f ssh-secret.yaml
Error from server (BadRequest): error when creating "ssh-secret.yaml": Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 76
```
**To Reproduce**
1. Go to https://github.com/cerebro31/monokle-resource-template/tree/main/ssh_pod
2. Install this plugin and create new project using it.
3. Provide image: cerebro31/monokle-helloworld:1.5
port: 80
ssh-public-key: base64 encoded public key
4. Select secret manifest, save it and click on deploy.
5. See the error
6. Click on Form in Editor
7. Now click on deploy

**Expected behavior**
Directly the base64 encoded public key should be stored properly so that it can be directly deployed

**Screenshots**
Here is the video showing a complete demonstration to recreate the issue

https://user-images.githubusercontent.com/125909758/225030040-f4429c97-4722-483d-9952-f935814e144c.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Comment by topliceanurazvan** [comment]
Fixed in https://github.com/kubeshop/monokle/pull/3403.
