### ISSUE TITLE
Form editor removes leading 0 from octal values - mode and default mode not parsed correctly

### ISSUE THREAD

**Issue by cerebro31** [kubeshop/monokle#3393]
**Describe the bug**
when CRT created the deployment manifest, the defaultMode and mode value gets changed to 644 and 600  even though when I hard coded the value in [template.yaml](https://github.com/cerebro31/monokle-resource-template/blob/main/ssh_pod/template.yaml#L37) as 0644  and 0600. This prohibits me to deploy both using Monokle Desktop as well as kubectl. Here is the error:
```
sonali@SONALI-SRIVASTAVA:~/Monokle/ssh_enable$ kubectl apply -f ssh1.yaml
The Deployment "ssh1" is invalid: 
* spec.template.spec.volumes[1].secret.defaultMode: Invalid value: 644: must be a number between 0 and 0777 (octal), both inclusive
* spec.template.spec.volumes[1].secret.items[0].mode: Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive
* spec.template.spec.containers[0].volumeMounts[1].name: Not found: "ssh-keys"
```
Although this is not related to custom resource template. If we have any manifest that has mode set, if we open it via Form Editor, Monokle is editing the manifest and updating the mode from `0644` to `644`

So I manually updated the deployment [manifest](https://github.com/cerebro31/kustomize-helm-monokle/blob/master/enable_ssh_app/test.yaml) and corrected the mode values. I am able to deploy via kubectl then but still unable to deploy via Monokle because it still can not understand the mode values are correct and throw the same error as shown in screenshot.

**Expected behavior**
The permission should be stored correctly and after updating Monokle is still unable to understand it and then deploy

**Screenshots**
Error in Monokle
![monokle_error_permission (1)](https://user-images.githubusercontent.com/125909758/225032981-d145cd51-3ded-48bd-b873-03fe8ef6b417.png)

Successfully able to deploy via kubectl once fixed the mode and defaultMode manually
![manual_manifest (1)](https://user-images.githubusercontent.com/125909758/225047548-899d543b-0d87-4657-91bc-7f593e0b46da.png)

Video showing the error and steps to recreate both for CRT generated manifest and via Form:

https://user-images.githubusercontent.com/125909758/225050661-a0d012f8-1ba5-4815-b63d-dcb70b65fc0f.mp4

https://user-images.githubusercontent.com/125909758/225050542-6b8d8c0f-d4c2-4089-afbd-18c13a8534d0.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**

**Comment by olensmar** [comment]
Hi @cerebro31 - Thanks for reporting! Could you share your deployment YAML so we can play around with it to see whats going on? Does this happen only if you use the form-editor to edit this value?

**Comment by cerebro31** [comment]
Hi @olensmar Please find the attachment. It also happens when we create the resources using the custom resource template. [Here](https://github.com/cerebro31/monokle-resource-template/tree/main/ssh_pod) is the link to the repo that has CRT that I have used to create the manifest.
[devs_app.zip](https://github.com/kubeshop/monokle/files/11218442/devs_app.zip)

**Comment by olensmar** [comment]
more context - the k8s schema unfortunately defines `defaultMode` as 

```
        "defaultMode": {
          "description": "defaultMode is Optional: mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.",
          "format": "int32",
          "type": "integer"
        },
```

which technically means that 644 is a valid value.. perhaps we should dynamically change the type to string!? (since JSON Schema doesn't seem to have support for octal numbers) - or perhaps there is something we can do with the rjsf ui-schema to override the default behaviour!?

**Comment by olensmar** [comment]
i'm trying to figure this out with the author of our yaml library - see https://github.com/eemeli/yaml/discussions/465

**Comment by olensmar** [comment]
@cerebro31 the upcoming 2.0.8 release should have a fix for this - let us know!
