### ISSUE TITLE
Enable manifest editing in Cluster Dashboard

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#3397]
**Describe the enhancement you'd like to see**
I find it confusing having an `Update` CTA on Editor in Cluster Dashboard screen since editing is disabled.

Either it should be removed or editing should be enabled

![Screenshot 2023-03-14 at 23 21 17](https://user-images.githubusercontent.com/2957624/225127811-700717e2-2351-4f30-b81f-78387cac1641.png)

**Comment by topliceanurazvan** [comment]
This is not reproducing anymore on the latest main ...
