### ISSUE TITLE
Difficult to see the errors of resources in the Dashboard

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3430]
When I look at the resources in the Cluster Dashboard, to see the errors I have to hover a little colored dot.

How can we improve the usability here?
Should we show the errors popup if the user hovers anywhere in the Errors cell, not necessarily on the small icon?

Or should we add some text, maybe with the number of errors for that resource?

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/20538711/226852867-6084cd24-4fbd-489d-911b-9feb9d088573.png">

**Comment by julioramosest** [comment]
Original design had a larger badge that included numbers - so larger active area (see below).

Lets's stick to new badge, but lets:
- [ ] Increase active area of the badge (using a transparent image 16x16)
- [ ] Add the label "X Errors" or "X Warnings" or both if it's the case in corresponding colors next to the badge, all texts active (cursor changing to hand)

<img width="1440" alt="2 0 - cluster management - pods" src="https://user-images.githubusercontent.com/97731654/227151310-ad7393d3-3932-4988-8e5a-dd86b70120f2.png">
