### ISSUE TITLE
Remove SectionBlueprints and refactor lists using tanstack/virtual

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3431]
We should remove all remaining SectionBlueprints and refactor each list using the tanstack/virtual library for best performance.

Remaining lists to be refactored:
- [x] Kustomizations
- [x] Helm Charts (this is pending a redesign)
- [x] Images

Finally:
- [x] Remove the blueprints redux middleware and any other related code

**Comment by chargio** [comment]
Performance related: high priority
