### ISSUE TITLE
Navigator Header does not match the design

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3433]
Currently the Navigator header looks like this:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/20538711/226855263-27a3fe72-eda8-4996-a529-a46da245b3c3.png">

But it should look like this: (we should keep the collapse all button)
![image](https://user-images.githubusercontent.com/20538711/226855219-8d557f0e-abfa-4d99-b8cf-a9d48b3084b7.png)

**Comment by julioramosest** [comment]
also let's review the distance between the white collapsing icon and the element, so it feels "breathing" space wise. That's tricky UI and we need to approach desing the more closely the better.
