### ISSUE TITLE
Add options to sort by name, last-opened to list of projects

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3441]
Suggest to add these to options to the below to make it easier to find recent projects that don't fit in the current recent-projects list

<img width="723" alt="image" src="https://user-images.githubusercontent.com/1917063/226877524-7f5f07d1-1c28-4829-86e8-e40354a504e8.png">

**Comment by chargio** [comment]
@julioramosest This can be added to the rework on the list of options that we discussed

**Comment by julioramosest** [comment]
@chargio we already have an issue for the reordering of the main left menu, so I guess this Ole's issue can stay and both tackled separately?
