### ISSUE TITLE
UI-rework of the validation tab in project settings

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#3443]
As a user I would like to see the UI reworked for that view so it better connects to the errors list view:
- Subsection title removed and changed by a regular text block with link and a CTA for checking errors, as in design below.
- since this is a 1-column view, content can look too wide and disconnected in large resolutions lets have that view width reworked
  - Left and right empty margins: 25% width each
  - center content: 50% width

Find design here: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=2937%3A12007&t=w9hFxeYPKBjzX9Ni-1

![validation tab in project settings](https://user-images.githubusercontent.com/97731654/226881465-b22dbaaf-88b2-40f3-81a9-ffef80a68633.png)

**Comment by devcatalin** [comment]
@ayushgml I assigned it to you! Let us know if you need any help

**Comment by ayushgml** [comment]
Thank you @devcatalin for assigning it to me! I worked on the UI part of of the column and I also added the text box and a "Checkout errors" button as shown in the image. My question is where should i route this link and button too? Or should i leave it without the routes?

<img width="1536" alt="Screenshot 2023-05-22 at 6 47 23 PM" src="https://github.com/kubeshop/monokle/assets/72748253/9be4326d-c197-4bb4-82a9-3b0c7fc515c4">

**Comment by ayushgml** [comment]
Also @julioramosest I made the width as 50%. Does it look okay or should i increase it to 55% maybe?

**Comment by julioramosest** [comment]
Hey @ayushgml looking good! Those call to actions need to both take the user to the validations tab (see screenshot below). Same effect as if user would click in that tab. As for width as 50% looks good enough for me. The goal was to ensure readability in wider screens.

<img width="1086" alt="image" src="https://github.com/kubeshop/monokle/assets/97731654/ba23466c-c44a-46fe-b7ee-67d37f747acc">

**Comment by julioramosest** [comment]
@ayushgml It is!

**Comment by ayushgml** [comment]
I have created a PR @julioramosest and @devcatalin . #3981
