### ISSUE TITLE
Input/Select full width

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#3447]
For some inputs/selectors from the settings, the width is only the max-content of the item selected, but it might look better if the width would take `100%` of the available space.

![image](https://user-images.githubusercontent.com/47887589/226923457-89ee9db4-234c-47af-8716-4c99b50044c5.png)

@julioramosest wdyt?

**Comment by julioramosest** [comment]
@topliceanurazvan I agree with you. Let's have them full width. Let's be consistent with that. Let's make sure this happens on restricted or 2-column UIs. In 1 column UIs that would be too large.
