### ISSUE TITLE
Bad image in the empty editor

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3470]
The empty editor shows a graphic that is referring to the old Monokle interface
<img width="623" alt="image" src="https://user-images.githubusercontent.com/7500590/226989474-a4c2459c-5dd2-457e-b71d-95459dfe7117.png">

We need to update it to the new interface, and show the three panels and their use

**Comment by julioramosest** [comment]
@chargio this one is UX ready. Find new image here: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=2793%3A12270&t=icWMCVZfoEekhdoG-1

(Im also attaching here the image alone in SVG)

![new-empty-editor-img](https://user-images.githubusercontent.com/97731654/231776172-d229e32b-c5fd-4a95-8621-0ffde4c87357.svg)

**Comment by devcatalin** [comment]
@julioramosest the Github Extension and the CLI do not interact with Desktop at all

**Comment by julioramosest** [comment]
@totally right - I will take them out

**Comment by julioramosest** [comment]
@devcatalin fixed, also removed the sharing capability

![new-empty-editor-img](https://user-images.githubusercontent.com/97731654/231782845-cc5a1938-b1e9-4bfc-a8fb-8976e64c12a8.svg)
