### ISSUE TITLE
New project section reworked

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#3495]
New project section is reworked to include 2 more options:
- [ ] Sample project. Expected behaviour: the user gets a new project with sample resources just by clicking there. Not through git clonning since users going there may not have even git installed. The straightforward the better. This needs further definition @chargio @devcatalin ?
- [ ] Cluster preview (users can also find it in the left menu, but let's have it also here).

ordering of cards can be re-discussed. 

Find design here: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=2945%3A12175&t=C8rzVvXDam84X0XD-1

<img width="1440" alt="new project" src="https://user-images.githubusercontent.com/97731654/227192935-12e38e5d-82e8-4f88-b3ef-2757695a08be.png">

**Comment by olensmar** [comment]
@julioramosest let's go with cloning for now, so we can update the project without have to do a new release.. users not having git is unlikely, and if it becomes an issue we can always package it later on

Suggest we add a note (requires git and an internet connection) with a link to the repo itself (so they can check it if they want) - and a prompt - "This will clone our demo repository to a local folder - proceed?"

**Comment by julioramosest** [comment]
@olensmar addressing this with Razvan. I suggested:

let's add a text block on top of that dialogue (on top of repository URL) to give context to the user. Sort of "In order to create your Sample Project we are going to clone our GitHub sample repo into a local folder of your choice. Tweak location if desired and click OK to procceed"


if having Git is mandatory, we should note that. Sort of "Note: you need to have Git installed to perform this operation. Download Git here"

**Comment by olensmar** [comment]
suggest we only show the git message if git is actually missing..

**Comment by julioramosest** [comment]
note that correct illustration for sample repo card is this one (ok on the fima), not above one's in the screenshot:

![image](https://github.com/kubeshop/monokle/assets/97731654/29baee95-43c2-4f39-bf8c-c813e3fdb0a2)
