### ISSUE TITLE
Remove unnecessary notifications

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3500]
We should remove the following notifications because they do not add any value and they quickly become annoying:
- folder import
- cluster load

What else?!

**Comment by chargio** [comment]
Verify that the count is ok.  In my cluster I see a message with 19 resources, and the list in the overview shows 19

**Comment by chargio** [comment]
We can keep in the log if we can do this without notifying the user. The message should be updated speficying the context:
- Processed 532 files in folder x, found 100 resources, 3 Helm charts and 2 Kustomize overlays configurations
- Processed 1234 resources in cluster y using context a from file b
