### ISSUE TITLE
The default clone repo should be different

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3521]
When you try to clone a repo, the default one used is:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/7500590/227534459-9a0002a0-3801-4d0c-a3f6-b552899e6735.png">

It should be https://github.com/kubeshop/monokle-demo, that is more suited for this, so new users don't clone a bad example repo

**Comment by julioramosest** [comment]
also, it should be prefilled by clicking tab or other. That sample text is just sample, user needs to fill it

I would add below the first field a simple text link with "Use Monokle Sample Repo" or "Select Monokle Sample Repo" being clicking there a shortcut to continue with that repo right away
