### ISSUE TITLE
Error pop-up during manifest update

### ISSUE THREAD

**Issue by ypoplavs** [kubeshop/monokle#3525]
**Describe the bug**
Error pops up when I update the manifest of the deploymnet. Is it an expected behaviuor? 

**To Reproduce**
1. Connect to a cluster.
2. Select a Deployment
3. Make a change in Manifest (i updated image tag)
4. Press Update

**Expected behavior**
No error pop-up

**Screenshots**
<img width="1031" alt="Screenshot 2023-03-24 at 16 47 31" src="https://user-images.githubusercontent.com/45286051/227558127-93829e5a-e8dc-4537-a50a-fdf33829cd36.png">

**Desktop (please complete the following information):**
Version: 2.0.5 on MacOS

**Additional context**
When I press `Update` again it's showing green window, saying - `Title: Applied testkube-operator-controller-manager to cluster gke_testkube-328312_us-central1-a_arm successfully. Description: deployment.apps/testkube-operator-controller-manager configured`
.

**Comment by chargio** [comment]
Related to #3564
