### ISSUE TITLE
Running multiple kubtctl proxy

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/monokle#3532]
We can only initiate one kubectl proxy, but it doesn't fit some cases. 
 
Use cases need multiple `kubectl proxy`:
- Running multiple Monokle windows 
- Running multiple clusters diff

**Comment by chargio** [comment]
Can we run different proxies in different ports?

**Comment by mortada-codes** [comment]
yes, we can.
to solve the problem:
1- run a node-pty process
2- pass the target kube config path
3- set the context
4- run the proxy
