### ISSUE TITLE
Change the way that Kubeconfig setting are managed at the project level to reduce confusion

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3543]
Let's keep only the Global Settings for configuring the Kubeconfig file because it seems to be confusing setting up a kubeconfig file.

**Comment by chargio** [comment]
We will reintroduce this in #3541 with better config management

**Comment by devcatalin** [comment]
Investigate if we can fix the underlying problem

**Comment by devcatalin** [comment]
Possible solution: When we go back to the starting page after opening a project, if we go to the "Connect to Cluster" option, we should see the header using the Global Kubeconfig file, not the one from the project.

**Comment by devcatalin** [comment]
We should implement a redux action that can reset the state of the app to remove the currently opened project

**Comment by devcatalin** [comment]
Closing this because we've made a popup that notifies the user the connection will be closed when switching projects.
