### ISSUE TITLE
Empty resource navigator actions behave odd

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#3544]
The resource navigator shows a yellow circle **and** executes the action. It seems like one of the two is a leftover from a previous iteration? Also I'm not sure why the opening the resource modal is so sluggish - it seems to trigger much rerendering which it should not do. 

note: this is with my Apple M1 / 32GB so sluggish for me = unusable for lower end computers.

https://user-images.githubusercontent.com/7761005/228215081-26d668af-92e3-47e4-a82e-5431e0582bbf.mov

**Comment by chargio** [comment]
Test if this continue happening after the virtualization of resources

**Comment by erdkse** [comment]
I created a Draft PR for it, It doesn't look like it is rendering a lot when the component is created for the first time, but after it there were needless re-renders, I memoized the component to prevent it, and I anyway would like to test it together @WitoDelnat, 

For the actions that are triggered on click, We trigger them after 1 sec., maybe we can remove it. We wait probably to show the yellow circle more.
