### ISSUE TITLE
Unexpected cluster indicator

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#3545]
It's not a bug but it continuously confuses me. The green checkmark indicates this cluster is okay, but this cluster is in fact unreachable.

<img width="1192" alt="Screenshot 2023-03-28 at 13 02 02" src="https://user-images.githubusercontent.com/7761005/228216081-610b7510-b299-4880-9dec-9bb26e995637.png">

The error handling is also a bit too aggressive / unpolished / not aggregated. It's a simple non-existing cluster - make it easy for a user to deal with this: "Cannot connect to cluster. Please check if the cluster is up and try again." Then a button "see more" shows the more technical errors.

<img width="1173" alt="Screenshot 2023-03-28 at 13 03 33" src="https://user-images.githubusercontent.com/7761005/228216771-cfef6dac-e157-4200-b8ad-1a2440c7e6a8.png">

**Comment by julioramosest** [comment]
cluster connection in the left pane fixes big portion of that sense of success for a found cluster https://www.figma.com/file/DvKYcHMYMcx0lhjBtmWR0Y/Cluster-pane?node-id=0%3A1&t=6eOv4csV1IXB4oDw-1

Agree on your solution for level-down the notification. Also, to change the error icon by a blue info one.
