### ISSUE TITLE
Adding a performance note notification

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#3550]
We are letting the recurring user know about performance issues acknowledgment. We go with a medium profile, sort of casual, notification for this communication.

- Regular alert: pops up in the top right corner and gets nested in the notification area afterwards.
- Appears after app loads (getting started page) ONLY for users who already have a previous version installed (does not appear to new users).
- Text TBD.
- Testing: review recurring first use experience - making sure there are not other popups happening, no telemetry notification, etc. Just this one.

Figma with design and UX notes: https://www.figma.com/file/F1JYylIDzsOTXxDlUSla8k/Monokle---release-featured-image?node-id=42009%3A2961&t=s3f49ZEz1Um4Mclu-1

<img width="1440" alt="desktop - performance note" src="https://user-images.githubusercontent.com/97731654/228491764-4e73a9c2-285d-49d2-a5fa-d36236646bac.png">

**Comment by julioramosest** [comment]
Proposed text added to the figma file

**Comment by chargio** [comment]
- For users of Monokle 2.0.x (any version), that are using a version previous to 2.0.4 (with known errors).
- Not applicable to new users that are not updating the tool. We don't want new users to worry about errors when they haven't interacted with the tool
- Message will be included as a notification, non blocking, at the first start of the tool (after the upgrade event), defined in the figma file.
