### ISSUE TITLE
Improving outgoing/incoming link hover popup

### ISSUE THREAD

**Issue by julioramosest** [kubeshop/monokle#3556]
We improve the outgoing/incoming link hover popup
- Increase of height for hover header and footer.
- we take out the incoming or outgoing icon of the header title
- we add a graph CTA in the bottom. Clicking on it should select the resource and open the graph view for it in the left pane.

Design: https://www.figma.com/file/HOx9fsNedtkR2G0bCpHDX9/Resource-actions%2C-previewing-and-more?node-id=420%3A1299&t=ywmj7vFiJELwlNvT-1

![Link hover popup rework](https://user-images.githubusercontent.com/97731654/228554060-6de1ec9e-f360-45ab-abfb-8304048823f4.png)

**Comment by chargio** [comment]
Related to #2515
