### ISSUE TITLE
Add additional events to Telemetry

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3557]
- [x] Add an event when the user exists the tool without a crash. (EXIT)
- [ ] Add a parameter to the SESSION_START event when there was a crash before

**Comment by olensmar** [comment]
I don't think we can detect if there was a crash before!? @devcatalin ?

**Comment by olensmar** [comment]
@chargio I'm also adding the number of kustomize overlays and helmCharts to the project-open event. Anything else we're missing?

**Comment by chargio** [comment]
If we can send a SESSION_END event when the user stops the session properly, we could have some information. I don't know if we store information about crashes in the logs that we can use to know if it is a clean start.
