### ISSUE TITLE
Duplicate copy of repos displaed in Monokle cloud

### ISSUE THREAD

**Issue by cerebro1** [kubeshop/monokle#3559]
**Describe the bug**
Monokle cloud is displaying a duplicate copy of recent repositories that i opened

**To Reproduce**
1. Go to app.monokle.com
2. Login and Click on Recent repositories
3. See duplicate repos

**Expected behavior**
Only a single input should be visible for unique repository

**Screenshots**
![duplicate_repos](https://user-images.githubusercontent.com/10183232/228727074-fe339338-f2f1-441f-988e-65aae6f1a092.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - Browser: Google chrome

**Additional context**

**Comment by chargio** [comment]
Thanks @cerebro1, working on it

**Comment by WitoDelnat** [comment]
Hello @cerebro1, thank you for reporting this. We've made several changes to recent repositories in the last week and this will no longer happen. It should also feel much faster.

Do note that some of your old recent repositories might no longer show - simply open the repository again on a new commit to get them back in your list.

I'm going to close this issue, please feel free to get back to us if it still does not work as expected and we will gladly reopen it again!
