### ISSUE TITLE
Missing folder actions for root folder..

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3569]
the folder-popup seen below is not available for the root folder - making the corresponding actions unavailable..

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1917063/229082709-b58e984f-62c7-4c38-b9be-f3505c1c3fbb.png">

**Comment by julioramosest** [comment]
@olensmar what other actions would we want root level beside new folder, file and resource creation? also the copy path and reveal in finder maybe? Guess excluding, deleting and renaming would not make much of a sense?

**Comment by olensmar** [comment]
sounds good @julioramosest
