### ISSUE TITLE
The macos version mentioned in the root readme file leads to a page that doesnt exist

### ISSUE THREAD

**Issue by adamma-da** [kubeshop/monokle#3574]
**Describe the bug**
macos dmg release link is broken

**To Reproduce**
1. Go to the root readme file
2. Click on the link which leads to https://github.com/kubeshop/monokle/releases/download/downloads/Monokle-mac-universal.dmg
3. Nothing downloads, you get a 404

**Comment by chargio** [comment]
Hi,
We were releasing a minor version 2.0.6, that is now available. During the process we get this error as the new version is being built.
It should be working now
