### ISSUE TITLE
cluster namespaces not shown in namespace selector

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3584]
see below

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/1917063/229470033-bd26f8fe-b66b-4fb5-90ca-813f077c5c86.png">

**Comment by erdkse** [comment]
I am not able to reproduce this one, how can I reproduce? @olensmar

**Comment by olensmar** [comment]
the following still happens:
- connect to your cluster - the list of namespaces should show all namespaces
- disconnect from your cluster
- deploy a simple resource (ConfigMap) to a new namespace - i.e. one that doesn't exist - Monokle should create it for you
- connect to your cluster
- the new namespace is not shown in the namespace-dropdown - but it is shown in the list of namespaces in the cluster dashboard

**Comment by topliceanurazvan** [comment]
Can't reproduce after cluster rework, @olensmar ?

**Comment by olensmar** [comment]
neither can I - thanks - closing!
