### ISSUE TITLE
Gradually retrieved cluster resources are not parsed 

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3594]
Monokle doesn't re-evaluate broken links as new resources are retrieved from my cluster - resulting in broken links which are actually fine, i.e. resource A with link to resource B that hasn't been retrieved yet will continue show as broken even when resource B has been retrieved.. 

You can reproduce this by deploying the resources at https://gist.github.com/UntouchedWagons/30a39dbd73b435a0fd256229431345a2 and then connecting to the cluster:
- Monokle will first retrieve the PersistentVolumeClaim, which will contain a broken link to the PersistentVolume, which hasn't been retrieved yet
- Eventually Monokle reads the corresponding PersistentVolume - but doesn't update the link in the first resource to now be fulfilled

**Comment by devcatalin** [comment]
This should be fixed by https://github.com/kubeshop/monokle/issues/3783
