### ISSUE TITLE
Resource action plugins

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#365]
I would like to create a plugin that adds an action to the resource-popup menu for specified kind(s) of resources - for example if I want to add some special processing for a ConfigMap. My plugin should be able to display visual components (for example a modal dialog) to prompt for input from the user - and it should have access to the state of the selected resource (and preferably all other resources)

**Comment by devcatalin** [comment]
Closed this in favor of https://github.com/kubeshop/monokle/issues/177
