### ISSUE TITLE
excessive space between accordion sections

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3695]
see below - there is some additional space at the bottom of each section before the next header

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1917063/230892396-0b36c8bf-5c6e-4ad9-a46b-cad7c36e59dd.png">

**Comment by itsajay1029** [comment]
Can you assign this to me @olensmar ?

**Comment by olensmar** [comment]
sure - thanks!!

**Comment by itsajay1029** [comment]
Where will I find the deployment Patches section @olensmar ? Can you ellaborate a little on the issue please ?

**Comment by olensmar** [comment]
sure @itsajay1029: there is some empty space above the headers of each accordion section (except the first one) - as outlined in the below image - the actual content of the section above (in this case "Deployment Patches") doesn't matter - you just need to find the styling in the accordion that needs to be adjusted accordingly.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1917063/231080348-901a14ed-f928-46a5-9004-62d5fe7a6743.png">

**Comment by ayushgml** [comment]
@olensmar I want to work on this please assign me this issue. Thank you!

**Comment by ayushgml** [comment]
Hey @olensmar I worked on it and this is how the gap is(Like the first section):

<img width="354" alt="Screenshot 2023-05-29 at 4 01 37 PM" src="https://github.com/kubeshop/monokle/assets/72748253/81e3d9b6-c3b3-4ab3-b18e-ed88d3845697">

What I did was: I used display flex and justify-content as space-between(for Accordion Panel). Then I went to increase the Accordion height by 12px.

**Comment by topliceanurazvan** [comment]
Hello @ayushgml, can you create a PR for this fix so we can give it a try too? Also, the spacing should be a little bit more, with some padding between the actually opened accordion and the next one.

**Comment by olensmar** [comment]
@julioramosest can you provide an exact number for the spacing? (in pixels!?)

**Comment by ayushgml** [comment]
Yeah @topliceanurazvan I will create a PR so you can try it too!

**Comment by julioramosest** [comment]
@olensmar @ayushgml @topliceanurazvan space between the end of open accordion and the next one is only 2px, same distance between closed accordions. This is very well implemented in cloud, see screenshot below. What I see in your screenshot Ayish is that there is some coloring to the scrollbar - we need to avoid that. The scroll bar height must be invisible until the actual scrollbar cursor goes to the bottom. I recommend you to visit for example https://app.monokle.com/explore/github/kubeshop/monokle-demo?view=explorer&section=files (you need to join with gh to properly access) and play with accordions to see how that is layouted. 
<img width="229" alt="image" src="https://github.com/kubeshop/monokle/assets/97731654/155e3598-1192-4a6b-899b-3e0a9f5435e1">

**Comment by ayushgml** [comment]
Hey @julioramosest! That scrollbar was visible there just because i just scrolled and took the screenshot. It disappeared after a while. The colouring to the scrollbar is already there. Currently I'm on main branch and still it shows the scrollbar like this:

<img width="1536" alt="Screenshot 2023-05-29 at 4 56 52 PM" src="https://github.com/kubeshop/monokle/assets/72748253/eadc5963-d6ba-4d0d-a325-1e4ff7254cc4">

Is it a system issue or everyone is seeing the scrollbar like this? @topliceanurazvan @olensmar. I will try to fix the scrollbar after exploring a bit through the given link.

**Comment by julioramosest** [comment]
@ayushgml right, I just saw that myself! We don't need to do changes on the bar, is ok as it is now. So let's stick at the 2px space, no matter the accordion element is closed or opened. Thank you!

**Comment by ayushgml** [comment]
@julioramosest I made the changes regarding the 2px space and asked @topliceanurazvan for a review.
