### ISSUE TITLE
transient resources not cleared when switching projects

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3713]
steps to reproduce:
- create a new resource in an existing project without saving it
- switch to another project

expected the new resource to be discarded/lost, but instead it showed up in the new project also.. 

we should also ask the user when switching from a project with unsaved resources - i.e. "your project has unsaved resources which will be lost" - i'll create a separate issue for that

**Comment by erdkse** [comment]
related https://github.com/kubeshop/monokle/issues/3649
