### ISSUE TITLE
Excluded folders are disabled

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#3715]
**Describe the enhancement you'd like to see**
I would like to see what is inside an excluded folder and I would like to include it by a quick CTA, now I can't do it because it is disabled

<img width="356" alt="Screenshot 2023-04-11 at 22 07 44" src="https://user-images.githubusercontent.com/2957624/231264669-f69749b9-8a44-4762-aa72-dfc5237cbb33.png">

**Comment by erdkse** [comment]
Monokle Cloud is doing this in that way, files and folders are disabled, and you can't see what is inside a folder, but actions like expanding a folder, or menu items are available.

I would like to have the same.

<img width="359" alt="Screenshot 2023-04-11 at 23 14 20" src="https://user-images.githubusercontent.com/2957624/231278120-e0777970-603f-4d6c-a28c-60adea64ee61.png">

**Comment by olensmar** [comment]
agree with @erdkse

**Comment by mortada-codes** [comment]
blocked by #3680
