### ISSUE TITLE
Release Date in About Modal is wrong

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#3716]
**Describe the bug**
The release date is wrong, we should be updating it in a dynamic way.

**To Reproduce**
1. Go to the About section in Monokle

**Expected behavior**
See the correct date.

**Screenshots**
<img width="397" alt="Screenshot 2023-04-07 at 20 37 15" src="https://user-images.githubusercontent.com/2957624/231264908-508291b3-f90e-4d96-984f-b0442389f9d4.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: -

**Comment by topliceanurazvan** [comment]
The release date is the one from the major-minor release ( in this case the `2.0.0` ). We are currently storing information about those releases ( e.g. `2.0.json`)... Not sure we should also treat the patches ones since we don't show any info about them, learn more URL, etc...

**Comment by devcatalin** [comment]
Closing this, I've changed the text on the modal:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/20538711/235647297-2a068f77-238e-491b-9c52-693247f4d50d.png">
