### ISSUE TITLE
Show list of used Docker images

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#372]
When debugging a local installation of kusk it would be very helpful if Monokle could somehow/where provide a list of all used images across all resources (filters applied)
- for each image show "incoming links" with clickable links to referring resources 
- for each resource add the contained images to the list of outgoing links - and make them clickable in the editor
- for each image show a link to the corresponding image in its repository (dockerhub, quay, etc)
- provide an action to "change" an image - and update all corresponding references
- ?

**Comment by olensmar** [comment]
maybe this should be a plugin?

**Comment by devcatalin** [comment]
See image for more info:

![image](https://user-images.githubusercontent.com/20538711/166466807-b671d8c7-3aa3-4972-9ff2-8641b58b71e2.png)

**Comment by julioramosest** [comment]
Find here finished design for this: https://www.figma.com/file/ZmervM0fC8vjKMp58gjMGQ/%23372-Docker-images?node-id=0%3A1
