### ISSUE TITLE
kubeconfig fails to browse and select kubeconfig for default and current project settings

### ISSUE THREAD

**Issue by cerebro1** [kubeshop/monokle#3778]
**Describe the bug**
kubeconfig browse option is opening the window to select the kubeconfig but it is not loading the selected file for the default and current project settings in Monokle Desktop

**To Reproduce**
1. Go to Settings
2. Click on Default project settings
3. Select Browse in KUBECONFIG section
4. See the selected file does not load in Monokle

This is also broken for the project specific kubeconfig.
1. Select the project
2. Click on Open settings
3. Click on Current project settings
4. 3. Select Browse in KUBECONFIG section
5. See the selected file does not load in Monokle

**Expected behavior**
Monokle Desktop should be able to load the kubeconfig

**Screenshots**
**For default project settings:** 

https://user-images.githubusercontent.com/10183232/233961216-7b19a8a0-793d-4507-9e6f-b5c61a8f4901.mp4

**For current project settings**

https://user-images.githubusercontent.com/10183232/233961543-8d64ed42-5e24-4bf8-a227-9494ebf82856.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**

**Comment by topliceanurazvan** [comment]
Hey @cerebro1, thank you for reporting this. We will take a look at what is going on and get back to you asap!

**Comment by chargio** [comment]
As the .kube folder is hidden, the navigation should:
- allow you to show hidden folder (due to the fact that this is configuration it should be the default)
- specify a folder
- open by default in .kube
- have a CTA to use the default configuration file (when you change the configuration file there is no current way of going back to the original one)
- have a list of recently used configuration files so you can reuse one of them
-

**Comment by cerebro1** [comment]
@chargio I agree that navigation allows us to select a folder and choose a kubeconfig but with this version of Monokle Desktop, something is not right. I can recreate this issue a couple of times. If I am doing a fresh install of Monokle Desktop, then the issue is not there for a short while[Not sure how we can define how short is short], but it starts after some time. Here is the video of what I can just recreate for default and current project settings.


https://user-images.githubusercontent.com/10183232/234444375-daadb6ee-a263-4d24-897a-e5bfe821a2a0.mp4
