### ISSUE TITLE
Status should refect the namespace selector

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3781]
Currently the status reflect the resources independently of the namespace selected, showing an inconsistency of the number of resources that you can see

<img width="267" alt="image" src="https://user-images.githubusercontent.com/7500590/233976750-43577891-66bf-471b-81d0-5b041e143970.png">

<img width="253" alt="image" src="https://user-images.githubusercontent.com/7500590/233976770-53ec65dc-c578-4480-bd9d-98f8d52981f4.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7500590/233977044-a0954eca-d809-44f6-8459-e38b2b611e0c.png">

Status should reflect the namespace being shown, the text should be 
- "2 (of 203) resources"
- Pods should be 0, not 9
- There should be an inventory stating "Other 2", as there is a COnfigMap and. a ServiceAccount

- CPU and memory should be for the namespace. In this case is empty:
  * CPU = 0 / 4.00 
  * Overall (0.13 / 4.00)
  * Memory =  0 / 11.67 GB
    Overall = 1.22 / 11.67 GB

Actually, the 0 / x should be the quota , while the overall is the resources, but we can do it later.
  
 errors and warning should be 0 as there are 0 errors in the namespace

**Comment by devcatalin** [comment]
This seems to be fixed on main.
