### ISSUE TITLE
validation errors for timestamp fields from cluster

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3812]
whenever connecting to a cluster I get a massive amount of validation errors related to incorrect timestamp fields - although they are ok 

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1917063/234970860-b615379e-5f5a-4d81-8b72-ec808f853d2a.png">

**Comment by UntouchedWagons** [comment]
Is the rest of the message that the values should be strings? I get that too.

**Comment by olensmar** [comment]
@UntouchedWagons yes - the k8s schema define these as 
```
    "io.k8s.apimachinery.pkg.apis.meta.v1.Time": {
      "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
      "format": "date-time",
      "type": "string"
    },
```

so I'm not exactly sure why/where the parsing of these fields is failing - digging in..

**Comment by chargio** [comment]
There is another user in Discord complaining that something similar happend to him


![Image](https://user-images.githubusercontent.com/7500590/235074537-a83ed161-f86f-4806-9a59-23d4f87c0da8.png)

**Comment by olensmar** [comment]
@UntouchedWagons this should be fixed now - thanks for reporting - will be in next nightly-build and upcoming release

**Comment by olensmar** [comment]
@UntouchedWagons we release 2.0.10 today which should include this fix - please let us know if you're still having troubles with this or anything else!

**Comment by UntouchedWagons** [comment]
Yup it's good now.
