### ISSUE TITLE
Add missing actions on resources info panel in cluster

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3931]
The Info panel of a resource in cluster mode should show actions for:
- Scale
- Restart
- Delete
- any other action that we already have implemented? (maybe Diff to local? or a quick compare?)

<img width="1209" alt="image" src="https://github.com/kubeshop/monokle/assets/20538711/32d2e975-cedb-41c4-a3d5-6991bbc89ea3">

**Comment by olensmar** [comment]
@julioramosest could we have these actions directly in the resource-table? either in a popup menu - or with buttons!?

**Comment by topliceanurazvan** [comment]
I'm not sure if this would be a WOW moment ( maybe the Diff to local 🤔 ). But we could have some main actions for the `Deployment` - the Scale/Restart. The Delete and Diff should be for all of them. @olensmar wdyt?

**Comment by julioramosest** [comment]
UX Ready
- In the listing https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?type=design&node-id=1011%3A5884&t=BkVjFh4skYMLbQTy-1xxxx
- In the details slider https://www.figma.com/file/YrcAzt79dPB2keqt2QDft7/Cluster-management?type=design&node-id=1011%3A6221&t=BkVjFh4skYMLbQTy-1



<img width="1440" alt="actions in resource listing - cluster view" src="https://github.com/kubeshop/monokle/assets/97731654/cec8aca4-7fb1-4591-89d1-3f4918983407">
<img width="1440" alt="actions in resource detail slider - cluster view" src="https://github.com/kubeshop/monokle/assets/97731654/2f14f0c2-6edc-49dd-9fcd-fdab73ccc39a">

**Comment by olensmar** [comment]
thanks @julioramosest - could we not have the buttons on the top of the details panel - above the tabs? (like we do in the editor panels)

<img width="1190" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/528e35d2-fa75-43b8-8772-a6e7a339dfcd">

**Comment by julioramosest** [comment]
@olensmar done (same figma link). better place to have them given this UI is right to the tabs - I had them somehow button-type looking, since text links got confusing with the tabs. 

<img width="1440" alt="actions in resource detail slider - cluster view" src="https://github.com/kubeshop/monokle/assets/97731654/6e82c458-c75a-459f-857c-9c391fa89b01">

**Comment by julioramosest** [comment]
We can work out the logic for what is the highlighted action vs the ones behind the three dots. We can have even 1 more highlighted action out there, but no more than 2 given the space...
