### ISSUE TITLE
Missing tooltip and confirm action in compare dialog

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3966]
the deploy actions in the screenshot below are missing tooltips and confirm action. Guessing they're missing telemetry also!?

<img width="1559" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/3935ebf1-47bd-4f94-9687-fbc078a2a847">

**Comment by olensmar** [comment]
Same goes for the update button in the dashboard manifest editor: 

<img width="821" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/1534cb89-b147-49e3-b5f2-ef2c4b16e910">

**Comment by topliceanurazvan** [comment]
Confirm dialog for `Update` was added in this PR https://github.com/kubeshop/monokle/pull/3979
