### ISSUE TITLE
Wrong resources shown in Navigator when switching project with cluster connected

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3968]
This is weird one and might be hard to reproduce:
1. Load a local project with many resources/files 
2. Connect to a cluster, select a namespace (or all) with many resources
3. Go back to load a new project with few files/resources (without first disconnecting from your cluster)
4. You will be prompted that the cluster connection will be terminated - selected ok
5. Expected behaviour: Explorer shown with new project Navigator containing resources in new project
6. Actual behaviour: Explorer shown with new project, Navigator shows resources in previous project (!)

<img width="1143" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/d2c793df-9383-4e69-a896-ad7cd2b86136">

reloading the folder with the "Reload" button on top of the explorer loads the correct resources into the navigator

**Comment by olensmar** [comment]
judging from the console log - what seems to be happening is that when exiting the cluster:
- the previous project gets handled by the validation listener
- the newly loaded project also gets handled - but is cancelled
- the validation result for the previous project comes back - and replaces the resources of the newly loaded project

**Comment by topliceanurazvan** [comment]
This is still happening sometimes, will keep an eye on it and try it again after the local/cluster issue https://github.com/kubeshop/monokle/issues/3757
