### ISSUE TITLE
"Start from Helm Chart" new project option

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3982]
I want to start a new project from a Helm Chart in a Helm repository - this option would prompt me for 
- the Helm Chart (not sure how we can reuse the Helm Browser) 
- to which folder it should be extracted locally

Alternatively we (only?) have a "Create local project" option in the Helm Chart Browser when a Chart has been selected - which would only prompt for the local folder?

**Comment by julioramosest** [comment]
@olensmar so the user should be able to , sequentially: 1) browse for a helm repo 2) select a chart from that repo? Or do we provide a default repo?

**Comment by olensmar** [comment]
thanks @julioramosest  - LGTM!

**Comment by olensmar** [comment]
as discussed - I think having a "Browse Helm Charts" option in the left menu (taking you to the Helm Panel) is a good start - before we add a dedicated panel.
