### ISSUE TITLE
Changes to values file lost when previewing

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3998]
Steps to reproduce:
- make a change to values file in a Helm Chart
- preview the values file

expected: 
- the change to the values file is saved and used when previewing

actual:
- the change is lost and the preview uses the "old" values file

Same happens when editing a values file during a preview and running "Reload"

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle/pull/4001
