### ISSUE TITLE
Ending path terminator in Helm preview causes escaped quote on Windows

### ISSUE THREAD

**Issue by Cervator** [kubeshop/monokle#4002]
**Describe the bug**

If you prepare to preview a Helm chart on Windows the crafted `helm template` command ends in a way causing an escaped quote to become part of the path, leading to an error finding said path.

Example Helm command: `helm template -f "D:\Dev\Terasology\ArtifactoryMigration\helm\values.yaml" terasology-artifactory-chart "D:\Dev\Terasology\ArtifactoryMigration\helm\"`

Note that being on Windows the path separator is a backslash and it appears that the last one plus the ending `"` for the path causes that `\"` to become an escaped part of the path instead, yielding the following error:

`Error: path "D:\Dev\Terasology\ArtifactoryMigration\helm"" not found` 

**To Reproduce**

1. Be on Windows in a context where backslash is your path separator
2. Open any workspace with a Helm chart in it, maybe a values file too
3. Create a Helm Preview Configuration and select it so its command shows up on the side
4. Attempt a preview

**Expected behavior**

The Helm Preview functionality triggers.

**Screenshots**

![image](https://github.com/kubeshop/monokle/assets/1063833/46d7b900-45b5-4f0b-89ac-129c953138e4)

![image](https://github.com/kubeshop/monokle/assets/1063833/3e12b748-4b32-4bcc-8681-178ccbeb0229)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

The same issue appears to have come up as part of a problem in a Discord support thread at https://discord.com/channels/884464549347074049/885184532830126100/1064846182423208017 which was linked to #3010

**Comment by olensmar** [comment]
awesome - thanks so much for reporting this @Cervator - we'll aim to have this fixed in the upcoming 2.2 release next week!
