### ISSUE TITLE
Possibility to hide navigation

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/monokle#4034]
I want to work with Monokle with half of my screen, I would like to hid the menu bar so I can focus on editing my files. You can see the struggle in the video below

https://github.com/kubeshop/monokle/assets/27779735/7b976d2e-d298-4ac8-b2c1-fda4b1daf975

I feel like this button usually serves this exact purpose, instead of taking back to the main menu: 

![CleanShot 2023-06-04 at 19 17 50](https://github.com/kubeshop/monokle/assets/27779735/90376bb0-6f48-4426-b7b2-6896121a5181)

**Comment by julioramosest** [comment]
Find UI design and UX notes here: https://www.figma.com/file/HOx9fsNedtkR2G0bCpHDX9/Resource-actions%2C-previewing-and-more?type=design&node-id=1052%3A9282&t=GRwoA81GZhm0O54t-1

additional note: panes width stickiness is important. When displaying back, user should find their panes as they had previously set up.

also related to https://github.com/kubeshop/monokle/issues/4040
