### ISSUE TITLE
Monokle fails to sync helm [chart - value] file when editing from an external editor

### ISSUE THREAD

**Issue by mortada88** [kubeshop/monokle#4041]
**Describe the bug**
Monokle fails to sync the helm chart file and helm value file when editing from an external editor like Vscode.

**To Reproduce**
1. open a helm file in Monokle
2. open the same file in another editor and edit the file
3. See the error

**Expected behavior**
Monokle should sync the file and load the content

**Desktop (please complete the following information):**
 - OS: Macos
 - Version main branch

**Comment by mortada-codes** [comment]
https://github.com/kubeshop/monokle/pull/4048
