### ISSUE TITLE
Order of options to create a new resource

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#4056]
The order of options for creating a new resource should be the same in the navigator ( when there is no resource in the current project), as well as in the `New` dropdown...

![image](https://github.com/kubeshop/monokle/assets/47887589/35625740-2dd8-4974-bec6-ab8e126bdda0)

Also in the navigator `from` should be replaced with `using`, and the `New resource from model` might be better to be something like `New resource using form` or something similar. @devcatalin @olensmar @julioramosest wdyt?

**Comment by julioramosest** [comment]
@topliceanurazvan it sounds good to me - my english is not good enough to tell what sounds more natural ("from" or "using"). Which ever it does. My only briefing is that of having "new resurce from/using..." so the user is framed into the action when in the resources pane.
