### ISSUE TITLE
collapse/expand all in validation panel

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#4082]
i have a lot of files / rules - which currently results in a lot of scrolling.. would be great if there was an easy way to collapse all sections in the validation panel. Also suggest to collapse all by default.

<img width="1424" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/07d403cb-d0a1-4f95-b2cb-b10c8d6893c5">

**Comment by devcatalin** [comment]
<img width="631" alt="image" src="https://github.com/kubeshop/monokle/assets/20538711/238198b7-6519-40e6-b88f-8c07786a287e">

This was implemented in core recently and it's available in Desktop as well.
