### ISSUE TITLE
Monokle is mixing versions of the same helm chart but from different repositories

### ISSUE THREAD

**Issue by folleymcklaukyn** [kubeshop/monokle#4100]
**Describe the bug**
In the same drop-down menu, Monokle is combining the helm chart versions of bitnami/kube-state-metrics and prometheus-community/kube-state-metrics.

**To Reproduce**
1. Go to the 'Helm menu'.
2. Verify that you have the same helm charts in different repositories, like Bitnami and prometheus-community
3. Click on 'bitnami/kube-state-metrics'.
4. Then, click on 'prometheus-community/kube-state-metrics'.
5. In the install button (showing Bitnami version 3.5.5), click on the drop-down menu, and you will see both versions together out of order.

**Expected behavior**
The install button and drop-down menu only display the repository helm chart's versions.

**Screenshots**
<img width="502" alt="Screenshot 2023-06-21 113340" src="https://github.com/kubeshop/monokle/assets/11838905/394815c4-ffc4-431a-8c50-b58da9e99c58">

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 - 10.0.22621 Build 22621
 - Monokle Version 2.2.0

**Additional context**

**Comment by olensmar** [comment]
thanks for reporting @folleymcklaukyn - we're on it!
