### ISSUE TITLE
Monokle doesn't parse multiple-files KUBECONFIG variable. Separated by ":".

### ISSUE THREAD

**Issue by fog1985** [kubeshop/monokle#4142]
**Describe the bug**
Monokle doesn't parse multiple-files KUBECONFIG variable. Separated by ":".
E.G.:
env | grep -i kube
KUBECONFIG=/Users/user/.kube/config:/Users/user/.kube/config_personal:/Users/user/.kube/config_other

it just says "No cluster detected".

**To Reproduce**
1. Create multiple kubeconfig files. With server/context in each. 
2. Create env variable: export KUBECONFIG=/Users/user/.kube/config:/Users/user/.kube/config_personal:/Users/user/.kube/config_other
3. Run monokle.
5. Go into cluster discover mode.

**Expected behavior**
it parses multiple files in tha path and extracts all the possible contexts. 

**Screenshots**
<img width="326" alt="image" src="https://github.com/kubeshop/monokle/assets/3924436/e36128a7-2103-44b5-9d3e-f4a8341f570b">
<img width="736" alt="image" src="https://github.com/kubeshop/monokle/assets/3924436/1ff012c2-8c10-4085-abbe-b2ccadc759ca">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version [13.4.1 (22F82) - Ventura]

**Additional context**

**Comment by olensmar** [comment]
Thanks @fog1985 - digging in..

**Comment by 0x07dev** [comment]
Sorry, but:

![image](https://github.com/user-attachments/assets/698601e7-c273-4243-8112-cc3de48f1a13)

OS: Linux Debian
OS version: 12.1
Source: .deb package

Monokle version: 2.4.8
