### ISSUE TITLE
Helm preview not working in 2.3

### ISSUE THREAD

**Issue by Anemun** [kubeshop/monokle#4145]
**Describe the bug**
When I make a preview of my current helm configuration (under Helm Dry-run configurations) in version 2.3, I got error 
```
undefined - W0721 10:20:05.656292    3841 loader.go:221] Config not found: [object Object]
W0721 10:20:05.684761    3841 loader.go:221] Config not found: [object Object]
```
Error itself doesn't tell what's wrong and it worked fine on Monokle before v2.3. Also if I run corresponding helm command in terminal it works fine.
Helm command (generated by Monokle):
```
helm template my-app "/Users/myuser/Desktop/REPO/helm-supply/Helm/my-app" --values "/Users/myuser/Desktop/REPO/helm-inventory/inventory/dev/Helm/my-app/values.yaml,/Users/myuser/Desktop/REPO/helm-inventory/inventory/dev/Helm/my-app/secret-values.yaml" --set "global.apps.version=4.2.3"
```

**To Reproduce**
1. Create new Helm Dry-run configuration
2. Click Dry-run
3. See error

**Expected behavior**
Preview k8s resources created with helm preview

**Screenshots**
![monokle helm error](https://github.com/kubeshop/monokle/assets/15797528/5b3527d4-91fe-4d34-a345-782e46da6767)

**Desktop:**
 - OS: macOS Ventura 13.4.1
 - Monokle version 2.3
 - helm 3.6.2

**Comment by devcatalin** [comment]
hi @Anemun , thanks for reporting this issue!
I was able to reproduce the error, will dig in an keep you updated.

**Comment by devcatalin** [comment]
I've implemented a fix for this issue and built a test release here: https://github.com/kubeshop/monokle/releases/tag/test
You can try it out if you'd like to let us know if the problem still persists.
This fix will be available in our next patch release (most likely on Monday or Tuesday)

**Comment by Anemun** [comment]
@devcatalin thank you, now it works!
