### ISSUE TITLE
crash when directory exists for new project from git

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#4154]
When I try to create a new project from Git and provide a project for which a path already exists I get:

<img width="1118" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/f14ff0de-264c-46e7-a025-be44028c06e5">

Closing the error reveals:

<img width="681" alt="image" src="https://github.com/kubeshop/monokle/assets/1917063/a5d9cdbd-7985-4702-bcd0-97c9d3141ce3">

the initial crash seems uneccessary :D

**Comment by devcatalin** [comment]
I tested this and it doesn't crash in production. There's an uncaught error in a `validator` promise used by AntD and the popup we see in dev mode is from webpack. I don't see an easy way to ignore this in dev mode..
