### ISSUE TITLE
Waterfall, changelist on the left. This is fine?

### ISSUE THREAD

**Issue by freexmonster** [kubeshop/monokle#4193]
Kubuntu 23.10

Monokle 2.4.2 App Image

[Peek 2023-11-20 08-16.webm](https://github.com/kubeshop/monokle/assets/16123893/49e167ec-6008-4835-b0dc-4bafb6091852)

**Comment by olensmar** [comment]
Hi @freexmonster - thanks for reporting - that looks more like a bug than a feature - digging in!
