### ISSUE TITLE
show descriminator for duplicate resources

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#424]
when working with complex kustomize setups it can be common to have the same resource defined in multiple files/overlays - which would show them with the same name. Not sure what the right solution is - possible suggestions:
- show the folder/filename next to the resource name (might be lengthy)
- show the "containing" overlay name next to the resource (if this is in a kustomization)
?

an example with multiple configmaps with the same name (need to be sorted - see #423 )

![image](https://user-images.githubusercontent.com/1917063/135296545-fa9be150-7d8a-40f6-848e-2f0ba7cfdf86.png)

**Comment by olensmar** [comment]
we could solve this in a couple of ways - need your input @tommywhitehead

**Comment by olensmar** [comment]
discussed alternative solution to show discriminator on hover - to avoid too much text - could be a setting

**Comment by tommywhitehead** [comment]
Let's bring this back up with the group on our next UX call...

**Comment by olensmar** [comment]
let's try adding a tag after the name with the namespace - with a setting to toggle, resources should be grouped by namespace, namespaces alphabetically ordered.

**Comment by olensmar** [comment]
for file-based resources (i.e. not a preview resource) I think a hover showing the filename would be helpful!? The hover could show more data (i.e. resource kind/version, labels and annotations) - in line with #184 !?
