### ISSUE TITLE
Create resource from unsatisfied link

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#439]
When referencing a non-existing object in my resource I would like an action to create that object - for example if I add a configMap reference to a Deployment to a configMap that doesn't yet exist - I would see the reference marked as an invalid link and should also have a "Create..." action that would open the "Create New Resource" dialog prefilled with the selected name, type of object, etc..

**Comment by olensmar** [comment]
there could be other actions - for example "Select existing..." - perhaps we can have a generic UI for "intention actions" - in line with 

![image](https://user-images.githubusercontent.com/1917063/135844105-02a75e59-e7b8-437b-93c0-e9628bc7bad8.png)

**Comment by tommywhitehead** [comment]
This should be relatively easy using the right click (context) menu for unresolved links.

**Comment by tommywhitehead** [comment]
https://ant.design/components/dropdown/#components-dropdown-demo-context-menu
