### ISSUE TITLE
massive memory comsumption on manifest repos with 3000+ resources

### ISSUE THREAD

**Issue by dodwmd** [kubeshop/monokle#470]
**Describe the bug**

memory leak causes app to continue to request more ram even when app isn't in active use (minimized)

**To Reproduce**

Installed app, it loaded, opened manifests repo that we used to control our infra has multiple directories with 200-300 resources in each file (template generated outputs). Seemed to operate fine (minimized for later), few hours later, computer starts to chug, noticed that monokle is using over 10G of ram. Uninstalled.

**Expected behavior**

Don't try and allocate memory for no conceivable  reason.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by olensmar** [comment]
Thanks for reporting - we'll try to reproduce... unfortunately this isn't something we've seen during testing on our end :-( 

Do you know if any of the resource files in those folders were updated by some external tool while Monokle was minimized? (thinking our background sync might be causing this...)

**Comment by kambydyne** [comment]
Hi Michael.

Thank you for taking the time to write a bug report. It's really great to get feedback on things we aren't aware of. 

We have quite a lot of teamies loading very large manifest repos today, seeing a bunch of different challenges, that we want to handle better.

We use electron with react, so we arent really intentionally allocating any memory ourselves. But we are trying to figure out where something isn't being cleaned up (eventlisteners, garbage collection, threads, etc). We are also updating electron to the latest version, where they actually did some memleak bugfixes, but I dont think those could account for 10gigs worth of ram. Do you remember if you were in one of our view modes(cluster, helm or kustomize), when your pc was idling?

The team will update this thread on our findings and solving the issue.

Best regards,

Steen from the Monokle team.

**Comment by dodwmd** [comment]
I believe I was in kustomize view. I'll try and reproduce over the coming days.

**Comment by dodwmd** [comment]
> Do you know if any of the resource files in those folders were updated by some external tool while Monokle was minimized? (thinking our background sync might be causing this...)

Isolated git checkout just for monokle. No outside changes should be occurring.

**Comment by olensmar** [comment]
ok thanks @dodwmd - really appreciate your effort and patience!

**Comment by olensmar** [comment]
I've engaged with the folks at wallaby.js to try out their profiler on this - unfortunately it throws an error when the amount of objects in memory gets "too big" - awaiting their feedback - follow the discussion on their discord servers support channel...

**Comment by olensmar** [comment]
this could also be related to #760

**Comment by olensmar** [comment]
de-prioritizing until we get more evidence that this is still an issue
