### ISSUE TITLE
Add "coach mode" to UI for displaying context-sensitive help

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#478]
To help users understand what different components in the UI do...

**Comment by tommywhitehead** [comment]
This is potentially a huge one that would likely go alongside #619 

We can talk more about this.

**Comment by olensmar** [comment]
need to identify aha-moments so we can guide users to them:
-

**Comment by olensmar** [comment]
@tommywhitehead i've added a couple of possible aha moments in the comment above - is this something you can work with?
