### ISSUE TITLE
Simplify writing manifests from scratch

### ISSUE THREAD

**Issue by kylehodgetts** [kubeshop/monokle#492]
**Is your feature request related to a problem? Please describe.**
Writing manifests from scratch is always a pain. I either have to lookup the reference each time or try to remember fields that perhaps aren't in every manifest that you see deployed to Kubernetes

**Describe the solution you'd like**
I would like to see functionality where I can choose to create a new resource and be told what fields could be included + the value I'd like to insert there. Both optional and mandatory fields. At the end, i'd like to have a manifest as a starting point that I can then edit or have it be ready out of the box with all the other nice Monokle features.

**Describe alternatives you've considered**
There are snippet generators but they include lots of fields that I don't necessarily need.

**Comment by devcatalin** [comment]
Related #195
