### ISSUE TITLE
Unable to preview when using yaml file on a windows network volume (\\wsl$)

### ISSUE THREAD

**Issue by ngauje** [kubeshop/monokle#521]
**Describe the bug**
Unable to preview Kustomization when accessing yaml files on a shared drive on windows to access files from a wsl2 distro.

**To Reproduce**
1. Have some yaml files on a wsl2 distro
2. Open Monokle on windows
3. Access the yaml files on \\wsl$\<distro_name>\<project_dir>\
4. Clic preview to launch `kustomize build`
5. Error

**Expected behavior**
Kustomize preview

**Error message**
```
Kustomize Error
Error: Command failed kubectl kustomize ./'\\wsl$\<distro_name>\<project_dir>\' CMD.EXE [...] not compatible with UNC paths [...] Unable to find kustomization.yaml [...]
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Monokle v1.2.2

**Comment by olensmar** [comment]
fantastic! 

branch is https://github.com/kubeshop/monokle/tree/olelensmar/fix%2Fkustomize-path-sep - you might have to run `npm install` depending on if you've run from the source before or not... 

looking forward to hearing back from you...

**Comment by ngauje** [comment]
Unfortunately it doesn't work any better :(

**Comment by olensmar** [comment]
Hi again @ngauje - i have another branch for you to try out - https://github.com/kubeshop/monokle/tree/olelensmar/fix/tool-cwd-fix - this one should hopefully work; i've tested it with manifests on a windows share on my local network (although not WSL) - let me know if you have time to try it out! Thanks in advance..
