### ISSUE TITLE
Better separate helm/kustomization resources in the UI

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#545]
the current UI is confusing - especially when previewing a helm chart or kustomization - in regard to separating helm/kustomization resources and (possibly generated) k8s resources

**Comment by olensmar** [comment]
Let's move Helm and Kustomize section to dedicated left-toolbar buttons/panels - containing the corresponding sections that are currently in the middle.

**Comment by olensmar** [comment]
@tommywhitehead need icons for the toolbar!

**Comment by tommywhitehead** [comment]
<img width="1440" alt="#545 Better separate helm kustomization resources in the UI 1" src="https://user-images.githubusercontent.com/4236167/142090567-70493097-3965-440e-a4b8-691773eb45af.png">
<img width="1440" alt="#545 Better separate helm kustomization resources in the UI 2" src="https://user-images.githubusercontent.com/4236167/142090569-927ff0b1-5c9e-4b42-99c5-67a5555194e2.png">
<img width="1440" alt="#545 Better separate helm kustomization resources in the UI 3" src="https://user-images.githubusercontent.com/4236167/142090572-1ccf189c-d289-400f-bb02-b808617c9f30.png">

https://www.figma.com/file/HEST7fM35bd6rVTGT0ffAx/%23545-Better-separate-helm-kustomization-resources-in-the-UI?node-id=0%3A1
