### ISSUE TITLE
change filter icon when a filter is active

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#572]
Sometimes I don't see any resources because I have a filter active which I have forgotten to reset - would be nice if the filter-icon somehow shows that it is currently active - perhaps with a number showing how many filters that are set? or just a highlight?

**Comment by catalinhoha** [comment]
I agree that we should highlight the icon and/or show the number of filters. 
We can also display a text in the navigator that says something along the lines "No resources found for the current filters"
