### ISSUE TITLE
Styled scrollbars

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#578]
**Describe the enhancement you'd like to see**
I would like to be able to see the scrollbar on all containers which can be scrolled, but the default style doesn't look good so we should find a way to style it

**Comment by olensmar** [comment]
@tommywhitehead can you suggest some styling for this?

**Comment by tommywhitehead** [comment]
<img width="1440" alt="#578 Styled scrollbars 1" src="https://user-images.githubusercontent.com/4236167/145915305-805c2c9d-eff4-451c-b602-c5021f1bd2ab.png">

Figma:
https://www.figma.com/file/uIXi9k6EXaHf0mUp9HfWWj/%23578-Styled-scrollbars?node-id=0%3A1
