### ISSUE TITLE
Function to remove k8s added properties

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#581]
When diffing a local resource to one retrieved from a cluster we need to remove properties added by the cluster itself (timestamps, metadata, etc) before comparing - since those properties will never be present in the local resource manifest.

**Comment by catalinhoha** [comment]
The easiest way to do this is to make an array of all object paths that need to be removed and then remove those with a method similar to lodash' .unset from the resource.content property which contains the parsed yaml as a js object. We can theb update the text by parsing the content back to yaml
