### ISSUE TITLE
Make current cluster context more prominent!?

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#587]
the currently selected cluster context is used for all cluster-related operations (diff, apply, retrieve, etc) - could we make this more prominent in the UI so it is always visible/selectable?! Perhaps in the top toolbar? 

We should also have a single place for setting the kubeconfig path - not multiple as today!?

**Comment by tommywhitehead** [comment]
<img width="1440" alt="#587 Make current cluster context more prominent 1" src="https://user-images.githubusercontent.com/4236167/142094979-35568766-a5ef-4702-915d-3d4efd0231b1.png">
<img width="1440" alt="#587 Make current cluster context more prominent 2" src="https://user-images.githubusercontent.com/4236167/142094986-c760c075-3699-439b-bdb2-273a28e01c50.png">
<img width="1440" alt="#587 Make current cluster context more prominent 3" src="https://user-images.githubusercontent.com/4236167/142094988-552f5157-6eee-4e88-bcd3-fa18f7afce4d.png">
<img width="1440" alt="#587 Make current cluster context more prominent 4" src="https://user-images.githubusercontent.com/4236167/142094991-fc48cbc2-fbfd-4792-b5bb-f2720a76f357.png">

Figma:
https://www.figma.com/file/YlLyefbOI1n8J73pybf7SE/%23587-Make-current-cluster-context-more-prominent?node-id=0%3A1

Animated Highlight Pen:
https://codepen.io/tommywhitehead/pen/rNzomeK
