### ISSUE TITLE
Different filters are shown in Cluster Diff mode

### ISSUE THREAD

**Issue by Toxer10** [kubeshop/monokle#614]
**Describe the bug**
When the user in Cluster Diff mode tries to filter by namespace using the Namespace dropdown, then opens the filters modal, the Namespace dropdown in this modal shows the wrong value. If the user tries to filter by namespace in the filters modal, the outside Namespace filter shows the needed value.

**To Reproduce**
1. Be in Cluster Diff mode.
2. Click on Namespace dropdown.
3. Choose default for example.
4. Open Filters modal.
5. Observe the value in the Namespace dropdown.

**Expected behavior**
Namespace dropdown in the Filters modal shows the needed value.

**Screenshots**
![image](https://user-images.githubusercontent.com/25991946/140932112-6d8b1151-bfe9-4f9b-be9c-d36398064448.png)
![image](https://user-images.githubusercontent.com/25991946/140932139-2bee4eb2-abf2-49c2-b9b9-3c60bc159813.png)
![image](https://user-images.githubusercontent.com/25991946/140932205-88774bde-4ae4-4304-8c63-401858121c1a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 1.3.0

**Comment by olensmar** [comment]
thanks @Toxer10  - @catalinhoha does this apply to your updated cluster-diff UI ?
