### ISSUE TITLE
Getting started page

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#619]
When starting Monokle without a folder or cluster configured we should show a welcome page with options to
- select an existing folder/project
- create a new folder / resource
- configure a context/kubeconfig

with links to documentation

**Comment by tommywhitehead** [comment]
Some new flows here... we'll want to talk through at the UX call.
<img width="1440" alt="#619 Getting started page 1" src="https://user-images.githubusercontent.com/4236167/145924831-3ddb474d-8427-48c1-b7ef-b46f0c8d4029.png">

Figma:
https://www.figma.com/file/h2p93QZ0Q6toI4wb4Q37EL/%23619-Getting-started-page?node-id=3%3A2050
