### ISSUE TITLE
Monokle dependency check is not working on production build.

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#620]
**Describe the bug**
Dependency check for 'kubectl', 'helm', 'kustomize' doesn't work on production build for MacOS.

**To Reproduce**
1. Take build version of the application and start it.

**Expected behavior**
Dependency check should be working as it is on development environemnt.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Version Monokle 1.22

**Additional context**
It is probably a permission issue.

**Comment by olensmar** [comment]
could this be specific to MacOS 12 ?

**Comment by erdkse** [comment]
I am not sure. I remember that It was working before I upgrade the OS. But I am not sure 100%

**Comment by olensmar** [comment]
no - i get this on MacOS 11.6 also..
