### ISSUE TITLE
"Apply all/selected" action for Cluster Comparison

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#631]
Once i've checked that all seems ok in the Cluster Compare dialog I would like to either apply all or a selection of resources at once to my cluster, instead of having to apply them one-by-one - for example in this screenshot:

![image](https://user-images.githubusercontent.com/1917063/141808579-7be7d2b9-a8c9-4119-91d2-1205dd46f5a6.png)

I would like to select the bottom three resources and deploy them; could we have checkboxes to the far left or right? Once any are selected we enable  "Deploy all" "Download all" buttons at the top or bottom?

**Comment by tommywhitehead** [comment]
Let's do a few things here:
1. Move the `Refresh` button to the right side (similar to where all other actions are)
2. Add two buttons: 1: `Download All` and 2. `Deploy All`

The Download/Deploy All buttons would require a confirmation explaining that all objects would overwrite any existing objects.

As a next step, we could reorganize the layout slightly to include checkboxes.

**Comment by olensmar** [comment]
half-way done - download is in issue #729
