### ISSUE TITLE
Recalculate resource-refs on preferences change

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#646]
Automatically recalculate refs when changing the "Ignore optional refs" setting in preferences - instead of having to reload the current set of resources..

**Comment by catalinhoha** [comment]
Similar to this, when changing `fileExcludes` in the settings, we shouldn't require a full reload of the folder to apply the changes.

We can check which existing files should be removed from the `fileMap` and their corresponding resources. Then, we will reprocess the refs on the resource kinds that might've been affected by this.
