### ISSUE TITLE
When a file changes through Monokle, file monitor catches it and creates a reflection.

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#655]
**Describe the bug**
So the file is updated two times for no reason. And sometimes It causes data losses. We need to understand If the files are changed through Monokle and do not trigger an update in fileMonitor.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by olensmar** [comment]
thanks @erdkse - we had a timestamp-based mechanism in place to handle this situation - i.e. Monokle saves the timestamp when updating a file and ignores and external changes older than this... is this still in place?

**Comment by erdkse** [comment]
File monitors interval time was 2000ms. After reducing it to 1000ms the problem is solved. So maybe 2000ms is just to high and this issue is invalid.

**Comment by olensmar** [comment]
ok - let's close the issue when that fix is merged
