### ISSUE TITLE
consider hiding/moving Kustomization Patch "resources"

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#660]
Kustomization Patches show up as resources in the navigator - although they really aren't resources which might be confusing? Should we keep them there? Add a setting/filter to hide them? Or move them to a separate section under each kustomization!? (once we move kustomizations to the their own panel in the left toolbar perhaps)

**Comment by catalinhoha** [comment]
We could have a new section called `Kustomize Patches` under the current `Kustomizations` section. 
Users could see the highlights we already have to know which patch is used by which kustomization.

**Comment by olensmar** [comment]
Suggest doing this as part of #545
