### ISSUE TITLE
Create separate Form editor for common metadata properties

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#666]
Since every Resource Kind has a metadata section with the same properties we can put these in a separate Form in the Form Editor - this form would be in a collapsable "Resource Metadata" section at the top of the panel - with the unique resource properties shown in a separate Form below

**Comment by olensmar** [comment]
as discussed - lets move this into a separate tab instead of a section on top of the existing form editor

**Comment by mortada-codes** [comment]
https://user-images.githubusercontent.com/20525304/151196553-2818d44a-eb41-42d3-aa3b-ae53c765a838.mp4
