### ISSUE TITLE
Option to ignore certain fields when validating resources

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#668]
Certain resource properties often contain an invalid value when retrieved from a cluster - for example creationTimestamp in the screenshot below:

![image](https://user-images.githubusercontent.com/1917063/141810526-d692d3e1-de10-4e6f-84bf-c8dc42380283.png)

To avoid this error cluttering up the interface and "hiding" any real errors it would be helpful if Monokle could maintain a list of paths to ignore during validation

**Comment by olensmar** [comment]
a couple of questions here - should we:
- make this list configurable?
- only ignore when validating cluster resources?
- add a setting to enable/disable?

A possible solution could be:
- add a setting "Ignore properties during validation" with the values "alwasy, never, cluster-preview only" 
- add a configurable list of properties (as we have for the file includes/excludes) - default values being ["lastProbeTime", "creationTimestamp"]

thoughts @devcatalin @fog1985 @erdkse @kambydyne ?

**Comment by devcatalin** [comment]
I'd like a combination of both solutions: having a configurable list of properties where you can set one of the values "always, never, cluster-preview only" for each of the configured property
