### ISSUE TITLE
Add Hover menu with Delete action to Unknown objects

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#682]
Unknown objects currently don't have a hover menu (see below) - which will be provided by custom KindHandlers in the future.. perhaps we can have a generic menu with a Delete action for those unkonwn resources that don't have KindHandlers? We can use `deleteClusterCustomObject` to implement this generically

![image](https://user-images.githubusercontent.com/1917063/142168732-182ed987-38ad-47da-9548-4d8ddaa9da83.png)

**Comment by mortada-codes** [comment]
https://user-images.githubusercontent.com/20525304/151199212-7e6ffa4b-f144-4390-856e-d7887a05bb8e.mp4
