### ISSUE TITLE
Monokle can't find `kustomize` command

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#712]
**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1 (M1)
 - Version 1.3.2

**Additional context**
Monokle can't find 3rd party commands if they are installed at different paths. Adding paths to Monokle settings would be the fastest solution.

**Comment by olensmar** [comment]
Suggest we add path settings for helm, kustomize and kubectl - could come in handy anyway if a user wants to override the default version..!?

**Comment by olensmar** [comment]
should be fixed in #716
