### ISSUE TITLE
Git Integration

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#720]
It would be great if Monokle could work directly with my git-repositories - allowing me to use it for both direct and GitOps workflows. 

I think I would like the following workflow:
- Select "Browse Git Repo"
- Monokle prompts for the git repo URL
- Monokle clones the repo and browses it as a folder 
- Any changes I make are "tracked" - once I am done I can select either "Create PR" or "Commit to Repo" to perform the corresponding action with my changes
- If I create a PR that PR would be shown as pending in the UI - preferably Monokle would "see" when it gets merged and update accordingly

I'm fine if the folders are in a "private" folder to Monokle - i.e. a folder that isn't easily available for me to mess with from the command-line

**Comment by chargio** [comment]
We have this already on the works. Should we close it?

**Comment by olensmar** [comment]
yes!
