### ISSUE TITLE
Cannot select text in error alerts

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#725]
![image](https://user-images.githubusercontent.com/20538711/142644519-13159467-049d-4931-9aa7-7720ac3c241b.png)

In the picture above we can see two error alerts, I would like to be able to select the text of the error.

At the same time we should add a `copy text` button similar to the one we have in the Notifications Center.

~~Lastly, let's make the errors disappear after 5 or 10 seconds, right now I have to close them manually.~~ (Done)

**Comment by Toxer10** [comment]
Couldn't reproduce it on macOS, Catalin will look into it on Windows

**Comment by erdkse** [comment]
Is this fixed? I am able to copy the text of notifications on the notification drawer, but not on the toast message

**Comment by topliceanurazvan** [comment]
Solved in https://github.com/kubeshop/monokle/pull/1757
