### ISSUE TITLE
multi-resource actions

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#730]
I would like to perform certain actions on a set of resources instead of one at a time:
- delete
- apply
- save to file/folder (for cluster/preview resources)
- cluster-compare

**Comment by tommywhitehead** [comment]
Some examples that we talked about...
<img width="1440" alt="#730 Multi-resource actions 1" src="https://user-images.githubusercontent.com/4236167/145318012-6cbfe58e-b931-4b3c-9f45-b740e85e2854.png">
<img width="1440" alt="#730 Multi-resource actions 2" src="https://user-images.githubusercontent.com/4236167/145318017-afa37dfe-697d-4622-b81b-3e2831f4f5be.png">

Figma:
https://www.figma.com/file/YF9aMbC8MMDUOjSE16q3s0/%23730-Multi-resource-actions?node-id=0%3A1

**Comment by olensmar** [comment]
@topliceanurazvan what is left on this?

**Comment by topliceanurazvan** [comment]
@olensmar - For now, we have only the `Deploy` functionality. The `Delete` button is showed also, but no functionality for it.

**Comment by olensmar** [comment]
ok thanks - anything stopping us from implementing it? (for both local and cluster resources)

**Comment by topliceanurazvan** [comment]
I don't think so. As far as I remember, @devcatalin said he will implement the remaining functionalities.
