### ISSUE TITLE
Improve multi-project UX

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#747]
Its currently hard to understand how to work with multiple projects (i.e. use multiple windows and/or the "recent folders" menu item) - could we make recent-folders available directly in the File Explorer and/or somehow handle multiple open projects in one window? 

From Discord in regard to this..

"Well, I would simply have expected to have the option of adding several projects and browsing them directly. The file explorer is basically empty if the folder is collapsed, so there would be enough room there.
That I suppose would be an option.
But if I really were looking for 'recent projects', I would probably expect it to be somewhere near 'Browse', because that belongs more or less to the same category, I guess?"

**Comment by olensmar** [comment]
see #178

**Comment by tommywhitehead** [comment]
Designs (to start, more on the way):
<img width="1440" alt="#747 Improve multi-project UX 1" src="https://user-images.githubusercontent.com/4236167/149844007-75a2bcdb-4fbb-44fe-8b7c-d8e793bc9d39.png">
<img width="1440" alt="#747 Improve multi-project UX 2" src="https://user-images.githubusercontent.com/4236167/149844012-14bc569b-f8a4-476e-87d9-5a53ef30b46a.png">

Figma:
https://www.figma.com/file/yDHgTrMIKMhgati9Qt1h5i/%23747-Improve-multi-project-UX?node-id=0%3A1
