### ISSUE TITLE
"Add folder" menu item in File Explorer

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#759]
I need to be able to add a new folder to my files - we should have a corresponding "Add folder" action on existing folders in the explorer. This would prompt for a folder name and validate that it is valid and doesn't already exist.

**Comment by mortada-codes** [comment]
https://user-images.githubusercontent.com/20525304/151197365-e0aafc8b-b1fc-457e-a71c-c9904a86dc3f.mp4
