### ISSUE TITLE
Add hotkeys to improve pane navigation

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#770]
I would like to be able to use hotkeys to open each of the panes from the left menu.

For the File Tree I suggest adding CTRL(or Cmd)+Shift+E to match VSCode's default hotkey

What hotkeys should we add for Helm pane, Kustomize pane and Clusters pane?

**Comment by Toxer10** [comment]
I suggest adding:

- cmd+shift+c for the Cluster pane
- cmd+shift+k for the Kubernetes pane
- cmd+shift+h for the Helm pane
