### ISSUE TITLE
Switch to FileTree pane on startup under certain conditions

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#778]
Monokle remembers the last pane that was selected on the left before it's closed.

Right now, if we open Monokle and we had the Helm or Kustomize panes open before, we might get an empty pane and we need to go to the FileTree to open a folder.

Expected behavior:
When opening Monokle, if the automatic loading of a folder is not set and the last opened pane was Helm or Kustomize, then switch to the FileTree pane.

**Comment by olensmar** [comment]
I think this also applies to when loading a new folder - which might not contain any Helm charts or Kustomizations - in which case we should switch to the File Explorer if any of these panes is selected (and now empty)
