### ISSUE TITLE
Adding resources to an existing or new file by help of context menu

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#787]
**Is your feature request related to a problem? Please describe.**
Creating a new resource can be easier.

**Describe the solution you'd like**
I would like to use the context menu to create a new resource.

* I want to be able to create a new resource by right-clicking on a file and selecting `Add New Resource`. The modal will open and so on..
* Also I want to be able to create a folder and file in it. Then again adding resources to it.

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by erdkse** [comment]
Related #788

**Comment by mortada-codes** [comment]
https://user-images.githubusercontent.com/20525304/151197110-c29fa467-405e-4eee-a2d5-a7d9aca51b64.mp4
