### ISSUE TITLE
make filter dialog a panel instead

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#812]
I really like the immediacy of filtering from the source editor - would be great if the main filter settings were equally "interactive"; now I have to close the dialog every time I make a change to work with the results... would it be possible to instead of showing the filter-options in a dialog, show them in a panel on top of the navigator that pushes the navigator down while it is visible? in this case I would be able to make changes to the filter interactively - which speeds up my exploratory workflow...

**Comment by devcatalin** [comment]
I like this idea!
