### ISSUE TITLE
Action to save cluster resource locally

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#841]
I would like to save resources in my cluster or during a preview to a local file via a dedicated "Save to file.." action in the resource actions popup

**Comment by olensmar** [comment]
cc @kylehodgetts

**Comment by olensmar** [comment]
this could be part of #730

**Comment by devcatalin** [comment]
For the similar action in Cluster Compare:

We decided to show details about what actions we'll do to each resource in the confirm modal:
- list the resources that will be replaced
- list the resources that will be saved + options to save to a folder, or a file, or leave them as unsaved resources

@tommywhitehead

**Comment by tommywhitehead** [comment]
@devcatalin can I see what you have so far?

**Comment by mortada-codes** [comment]
@jfermi 



https://user-images.githubusercontent.com/20525304/150302615-dbd7bf28-5c9a-4eae-b80a-1ca20f6a1571.mp4
