### ISSUE TITLE
Add new resource to existing file

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#847]
Instead of adding new resources to a folder I would like to add a new resource to an existing manifest file via a "Add New Resource" action on the file popup menu. This would open the New Resource dialog - with the chosen file selected 

We would need to add an "Add to file" option to the new resource dialog - with a dropdown of all resource files in the project, the user should be able to select either Add to file or Save to folder - and then select either from a list of files or folders

**Comment by mortada-codes** [comment]
@jfermi 

https://user-images.githubusercontent.com/20525304/150299254-c06a7d24-09a3-4d27-b54b-83e7fd65a1ce.mp4
