### ISSUE TITLE
Support for extensions like Istio

### ISSUE THREAD

**Issue by mar1ged** [kubeshop/monokle#859]
Monokle is really helpful and I used it for an assortment of manifest files that I use for our Kubernetes.

Some of my projects reference Istio. Those resources (DetinationRule and VirtualService) are listed but there is no dedicated support and as far as I can see the links between the other manifests and those istio manifests are not detected.

![image](https://user-images.githubusercontent.com/16045549/145175649-d695455b-05e7-494a-93f0-2c869386f1d9.png)

If I can make a wish (Xmas is coming soon ;-)) I would like to have support for at least Istio and probably other extensions that might exist.

**Comment by erdkse** [comment]
Hey, @mar1ged thanks for your feedback - We are currently working on the plugin feature that will help us to support other kinds of resources. You will be able to visualize Unknown Resources better with help of some supported or 3rd party plugins.

We will be looking into creating a plugin for Istio as your Xmas wish 💝 🚀 

Here are the relates issues; https://github.com/kubeshop/monokle/issues/302 https://github.com/kubeshop/monokle/issues/365

**Comment by olensmar** [comment]
hey @mar1ged - we've been talking to Santa about this and his elves are looking into it - are there any specific links to/from/between Istio resources that you are keen for Monokle to support? (so the elves don't miss them...)

thanks in advance!

**Comment by mar1ged** [comment]
Greetings to the elves ;-)

So far I only use those shown in the screenshot but more will be used in the future. Whatever you or the elves can provide will be very much appreciated

**Comment by olensmar** [comment]
Hi @mar1ged - the latest nightly build at https://github.com/kubeshop/monokle/releases/tag/untagged-a6fea99e5c85648ecf44 includes initial support for all Istio networking resources - you'll see them in the navigator as shown below - and should have validation and link-identification as expected... let us know if you have time to try it out and how if it works as expected! Happy Holidays!

![image](https://user-images.githubusercontent.com/1917063/147057667-85a68869-81fd-4808-9a87-0fcff6edf24d.png)

**Comment by mar1ged** [comment]
Thank you, but I didn't find a way to download this nightly (the link leads me to a 404) and unfortunately I don't have the time to compile it myself because I have to sacrifice a bit more of my lifetime to log4j ;-)

**Comment by erdkse** [comment]
Hey @mar1ged sorry for the broken link, you can try via this URL as well https://github.com/kubeshop/monokle/releases/tag/v1.4.1-20211222.0

**Comment by mar1ged** [comment]
Thanks again, this one looks good. Obviously I unwrapped my first present already ;-)
