### ISSUE TITLE
Add terminal window like in VSCode

### ISSUE THREAD

**Issue by exu** [kubeshop/monokle#863]
**Is your feature request related to a problem? Please describe.**

I want to have quick access to terminal panel like in VSCode when working on my cluster

**Comment by olensmar** [comment]
thanks @exu - maybe we can integrate https://github.com/xtermjs/xterm.js/ - seems to be used by vs-code, etc...!?

**Comment by olensmar** [comment]
would be cool if we could somehow add monokle commands to this terminal - for example

preview <contextname>
create <resourcetype>

perhaps using some prefix doesn't interfere with regular cli commands!?

**Comment by tommywhitehead** [comment]
<img width="1440" alt="#863 Add terminal window 1" src="https://user-images.githubusercontent.com/4236167/152885029-c392da52-4f0c-4cc7-9130-34ebca8a76a4.png">


Figma:
https://www.figma.com/file/7xpHVhsOgnljr6sYUcJdvG/%23863-Add-terminal-window?node-id=2%3A5261
