### ISSUE TITLE
Show hover with base64 decoded values

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#869]
for Secret properties - as for example below - so I don't have to base64 decode them manually:

![image](https://user-images.githubusercontent.com/1917063/145559260-26eeb293-eedc-4f38-ac00-44b2a8643dbe.png)

**Comment by mortada-codes** [comment]
@jfermi  
- open `argo-cd` project 
- navigate to secrets from the navigator pane 
- select secret file 
- in editor go to the secret form 
- continue as the video

https://user-images.githubusercontent.com/20525304/150298886-56150ca6-963f-4231-9852-3d5f46f6086d.mp4
