### ISSUE TITLE
Make it possible to resize the diff modal

### ISSUE THREAD

**Issue by ioandev** [kubeshop/monokle#877]
Hi there,

Great work on monokle so far. I was using the diff option earlier and it was very useful.

Is it possible to make the modal resizable?

It would be useful to see more of the configs if the display size allows for it

When resizing the modal, it should store the size of the modal in % respective to the overall window size. This is so if you have monokle in full screen, resize the modal to 90% width of the window, then resize monokle to be smaller, the modal won't be bigger than the monokle window itself.
The maximum width of the modal should be 90% or 95% such that there is some space on the side.
The modal's width should be stored for future modals to use.

![image](https://user-images.githubusercontent.com/9282777/145696118-35867c19-83d6-4872-8c83-8ee78162ee04.png)

Thanks!

**Comment by erdkse** [comment]
hey @ioandev that is a really good idea. We will certainly look for it.
