### ISSUE TITLE
Selecting bottom resources in preview hides the preview panel at the top

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#892]
see below screenshot - when doing a preview (cluster/helm/kustomize) and selecting a resource in the bottom of the navigator the top panel is (partially) hidden

![image](https://user-images.githubusercontent.com/1917063/146178706-67b9d94c-4f76-4fd5-9a15-e58cfd2f2401.png)

**Comment by devcatalin** [comment]
I think this got fixed in my PR related to scrolling into view of selected/highlighted resources.

But, related to this, the Footer gets hidden when I am in preview mode:

![image](https://user-images.githubusercontent.com/20538711/146954627-6c53010f-1e78-4dde-91ca-0549a582630e.png)
