### ISSUE TITLE
Form editor support for NetworkPolicy 

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#897]
as requested at https://www.reddit.com/r/kubernetes/comments/rh03fw/comment/honr4uw/?utm_source=share&utm_medium=web2x&context=3

**Comment by olensmar** [comment]
perhaps we could have a custom widget for podSelectors - allowing the user to select from a list of available pod labels (extracted from all pod-specs) and showing which pods that are selected? see #890

**Comment by andreiv1992** [comment]
Fixed in https://github.com/kubeshop/monokle/pull/1043
