### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#900]
the documentation is lagging behind - need to go through it an make sure it's up to date for 1.5.0

January 31, 2022 Update doc for the following issues:

- [x] #170
- [x] #287
- [x] #306 
- [x] #283 
- [x] #308
- [x] #587
- [x] #589
- [x] #609
- [x] #617
- [x] #660
- [x] #692
- [x] #722 
- [x] #730
- [x] #812 
- [x] #819
- [x] #828 
- [x] #841 
- [x] #847 
- [x] #873 
- [x] #891 
- [x] #905 
- [x] #907 
- [x] #923 
- [x] #937 
- [x] #992 
- [x] #993

January 19, 2022 Update doc for the following issues:

- [x] #265
- [x] #266 
- [x] #280 
- [x] #283 
- [x] #439
- [x] #444
- [x] #660
- [x] #692
- [x] #722 
- [x] #770
- [x] #792

January 18, 2022 Update doc for the following issues:
- [x] #172 
- [x] #176 
- [x] #179 
- [x] #223 
- [x] #229 
- [x] #231 
- [x] #317 
- [x] #341  
- [x] #507 
- [x] #543 
- [x] #545 
- [x] #607

**Comment by dimonlex** [comment]
To add to this - many good features have been delivered by you over the last several weeks. If we wanted to share the full scope of Monokle to date with someone or point them to the documentation that would be a challenge

**Comment by olensmar** [comment]
fantastic work @jfermi !
