### ISSUE TITLE
Quick-navigate/select hotkey/popup

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#905]
Sometimes when I open a set of resources I know exactly what I want to look at - for example a specific resource or resource kind, currently it takes me several clicks/scrolls to set up a corresponding filter or navigate to achieve this - what I'm instinctively looking for is:
- press a hotkey to open a "navigate" popup 
- start typing which interactively presents me with matching lists of namespaces, resourcekinds and resources (based on name)
- when i've typed enough to select only one of these I can simply press return and depending on the type of object
  - namespace; set the namespace filter (or change the exiting one)
  - kind: set the resourceKind filter (or change the existing one)
  - resource name: navigate to that resource
- if there are multiple matching I can click on one of these with the mouse to select them instead

**Comment by tommywhitehead** [comment]
<img width="1440" alt="#905 Quick-navigate select hotkey popup 1" src="https://user-images.githubusercontent.com/4236167/147700825-64cfdf32-313f-4ff0-afe8-9b39016d22a5.png">
<img width="1440" alt="#905 Quick-navigate select hotkey popup 2" src="https://user-images.githubusercontent.com/4236167/147700828-f9cc4f48-2afa-438c-912d-9fc3a80b6dda.png">

Figma:
https://www.figma.com/file/gxgVBJ0P089rcySTfxy9vs/%23905-Quick-navigate-select-hotkey-popup?node-id=0%3A1
