### ISSUE TITLE
Select namespace for resource diff

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#907]
If a resource is deployed on a namespace different than `default` and that namespace is not specified in the resource's content, then the diff fails.

We should show a modal similar to the one for Deploy where we can select the namespace that we want to diff to.

Additional notes:
- if the namespace is specified in the file then we don't have to show the modal and do the diff directly
- if there's a filter on a namespace, should we use that namespace for diff and don't show the modal ?!

**Comment by olensmar** [comment]
Let's look for the resource in all namespaces in the cluster - and show a list of namespaces where the user can select those that contain the resource being diffed. Default namespace should be one of:
- what's in the resource manifest
- the current filter
- whatever namespace the resource exists in
