### ISSUE TITLE
Template field for New Resource Wizard shows resource ID instead of name

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#912]
![image](https://user-images.githubusercontent.com/47887589/146944533-59de598d-12ad-414d-a0e0-9373b8242aeb.png)

**Comment by olensmar** [comment]
hm..  I can't reproduce this locally... did you do anything "special" before this happened

**Comment by topliceanurazvan** [comment]
It is really strange, it also works fine for me now, maybe I was in a broken state and just needed to refresh Monokle.
