### ISSUE TITLE
Show kustomization in file explorer

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#924]
Now that we show kustomizations/patches/helm-charts in a separate panel it is no longer possible to immediately see the corresponding file. I can open the file-explorer which will have the corresponding file selected - but it wont scroll to it if not visible - could we (for example) have a hover-popup for kustomizations with a "Show file" option that would open the file-explorer and select the corresponding file? Or is there some better way to achieve this?

**Comment by olensmar** [comment]
@tommywhitehead thoughts on how to do this ?

**Comment by devcatalin** [comment]
if we just set the `selectedPath` to the kustomization file, the File Explorer icon will get highlighted and opening the tab should scroll to the selected path

**Comment by tommywhitehead** [comment]
Maybe the action should be `Go to file`, which automatically switches over to the file explorer, selects the file, and scrolls to make it visible?

Is it problematic that you lose selected state of wherever you came from?

**Comment by topliceanurazvan** [comment]
I think we should be ok, we will go with your suggestion. Thank you @tommywhitehead

**Comment by mortada-codes** [comment]
@jfermi 

https://user-images.githubusercontent.com/20525304/150304154-c9e5e23c-477e-4dbf-b963-310df34a66b0.mp4
