### ISSUE TITLE
Clean up Diff Resource modal

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#930]
The diff modal looks very busy to me - see below - could we "clean this up" somehow? 
- move all buttons/options to the top?
- improve alignment of buttons/labels?
- change Local/Cluster to not look like buttons?

if this is just me we can ignore :D

![image](https://user-images.githubusercontent.com/1917063/147454286-d35f9d83-858e-4ff6-b383-03b0c235be9f.png)

**Comment by devcatalin** [comment]
The modal has been slightly redesigned since
