### ISSUE TITLE
UI gets broken when resetting the filter.

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#951]
**Describe the bug**
UI gets broken when resetting the filter.

**To Reproduce**
Steps to reproduce the behaviour:
1. Preview a cluster
2. Select a resource (preferably Deployment) 
3. Filter for anything and be sure the `Deployment` tab is selected
4. Reset the filter

**Expected behavior**
- 

**Screenshots**

<img width="1437" alt="Screen Shot 2022-01-05 at 01 16 41" src="https://user-images.githubusercontent.com/2957624/148131770-f78bc165-76a2-4fa1-aea6-d2cb7786e045.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 1.4.0

**Comment by olensmar** [comment]
thanks @erdkse - i've seen this also but forgot to report...
