### ISSUE TITLE
highlight incoming link targets in editor

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#953]
I would like the source editor to highlight/mark values or properties that are the target for an incoming link - for example a property pair that is targeted by a selector - or the name of the resource. This makes it easier for me to understand that things might break if I change those values.

**Comment by devcatalin** [comment]
Maybe we should also change the margin icon for the outgoing links and add one for the incoming as well.

I'm thinking of something like this: (using the same icons from navigator)

![image](https://user-images.githubusercontent.com/20538711/148246128-56a97a2b-6f1b-4e28-81d9-725f441a7e63.png)

**Comment by olensmar** [comment]
nice suggestion @devcatalin ! What do you think @tommywhitehead ?

**Comment by tommywhitehead** [comment]
I love it! Let's go with it.

**Comment by mortada-codes** [comment]
I did some progress here. i can complete it once i get along with the refs relation 
<img width="1199" alt="Screen Shot 2022-01-13 at 9 56 15 AM" src="https://user-images.githubusercontent.com/20525304/149288960-96285898-1556-4761-b1a8-bef70c2ffb5c.png">

**Comment by olensmar** [comment]
@mortada-codes great! please assign this to yourself if you are working on it and move it to the in-progress column in the 1.5.0 project
