### ISSUE TITLE
Show existence of Kustomizations/Helm Charts on toolbar buttons

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#954]
When I load a folder I don't immediately know if it contains any kustomizations or Helm Charts - would be nice if the icons in the left toolbar somehow indicated this so I don't have to click on them to find out... - either with a number of how many - or some other indicator!?

**Comment by olensmar** [comment]
@tommywhitehead i think you meant to add this to #956

**Comment by tommywhitehead** [comment]
Ooops yes.

**Comment by devcatalin** [comment]
Whenever we load a folder we should show a blue dot/badge on the kustomize and helm charts panes icons (if there are any existing)
