### ISSUE TITLE
Hints / New Feature walkthroughs

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#963]
As a user I would like to get a short guided tour of new features in the current release - similar to what i get in other tools.

Examples

Get started
![Screenshot 2022-03-04 at 11 56 10](https://user-images.githubusercontent.com/1978959/156750972-1e436c27-e7b5-4bb4-9246-ad904e123cac.png)
Playground
![Screenshot 2022-03-04 at 11 56 26](https://user-images.githubusercontent.com/1978959/156750977-a7806360-ec7f-4b1d-8237-bd44fc31a9d8.png)

**Comment by chlete** [comment]
@tommywhitehead the idea behind is how to get users aware of the features that Monokle offers without reading the whole manual. 
Suggestion: Onboarding + playground / exercises?
What are your thoughts?

**Comment by julioramosest** [comment]
@olensmar @chlete Here I share a guided tooltip proposal for new features in a release. I include there not only UI design but UX logic. Let me know your thoughts - feel free to share and comment.
https://www.figma.com/file/xogpkKnXBIwa7Znw0KGJvq/Monokle---new-features-quick-guide?node-id=0%3A1

**Comment by julioramosest** [comment]
@olensmar @chlete @tommywhitehead @devcatalin guys, have a look at UI proposals for both modal and right display slider to showcase new release's features, along the lines we commented yesterday: https://www.figma.com/file/F1JYylIDzsOTXxDlUSla8k/%23963---new-features-walkthrough?node-id=0%3A1 
Illustration on the right would exemplify each release's key feature(s). Claim would be copywrite-reviewed. Audience, persistence & triggering would also need discussion. Feel free to comment.
<img width="1440" alt="New release - modal" src="https://user-images.githubusercontent.com/97731654/157872222-b7c4ea4d-a749-49fe-8497-854e688b5e11.png">
<img width="1440" alt="New release - right display" src="https://user-images.githubusercontent.com/97731654/157872242-d14fdf6f-6297-4420-9dd8-b929cf52b420.png">

**Comment by julioramosest** [comment]
This is now design ready, per latest UX discussion. Layouting of tooltips can begin and referred animated screenshots will be provided later.

Figma file: https://www.figma.com/file/CKixGN2hCosAX0t6EClITn/Onboarding-users?node-id=0%3A1

step 1 tooltip screenshot:
<img width="1440" alt="Step 1" src="https://user-images.githubusercontent.com/97731654/161789716-db273d93-a212-424e-857f-b4f069679844.png">

**Comment by julioramosest** [comment]
I also added the ability of replaying anytime the tooltip guide through CTA in the help menu:
![Re-play utility for the tooltip guide](https://user-images.githubusercontent.com/97731654/162249199-c49ed6c4-e6d2-4621-8930-cbbcfe2a724a.png)
