### ISSUE TITLE
Add support of "helmCharts" in kustomize

### ISSUE THREAD

**Issue by ZakharZakharov** [kubeshop/monokle#993]
Starting from April 2021, kustomize supports "helmCharts" and "helmGlobal" attributes (https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.1.0).

Straight way to use kustomize and helm together is to pass "**--enable-helm**" command line parameter to **kubectl kustomize** command.
However, monokle doesn't support these attributes, highlighting them in UI. When I click "preview", it shows me an error
![image](https://user-images.githubusercontent.com/1910974/149385494-177133e1-91fd-4425-9afc-b396a7982c57.png)

It would be perfect if user could manipulate the attributes of command line tool used for preview, e.g. add command line parameters.

**Comment by devcatalin** [comment]
Hi @zakharovzakhar ,

We were thinking about this a few days ago and it's super valuable for us to get this feedback from you.
Thanks for opening this issue!

We decided to add configurable previews for both Kustomize and Helm in the near future. 
This will allow you to pass arguments for the preview and save the configuration to easily use it again at a later time.

Let us know if you have any other ideas or suggestions!

**Comment by olensmar** [comment]
thanks @zakharovzakhar - as an intermediate solution which we could add to the upcoming 1.5.0 release, could we by default simply always add --enableHelm when invoking kustomize? Perhaps have a "Enable Helm with Kustomize" global setting to ensure compatibility with older versions of Kustomize that don't support this setting?

**Comment by zakharovzakhar** [comment]
I think having a global setting should work. If it is possible for closest release, could you please also fix the validation rules for kustomize to prevent red highlighting of these attributes ?

**Comment by olensmar** [comment]
I've added the updated kustomization schema in #1009 - will be in the upcoming nightly build and release. We'll add a global "Enable Helm with Kustomize" setting in the settings drawer which will add the corresponding cmdline argument when invoking kustomize

**Comment by olensmar** [comment]
@ZakharZakharov do you know of any public repos that contain kustomizations with these properties?
